### ISSUE TITLE
Transform fails when Api StageName contains '_'

### ISSUE THREAD

**Issue by hikerninja** [awslabs/serverless-application-model#1002]
If an AWS:Serverless::Api resource has a StageName that contains `_` the transform fails with the following error:

```
Failed to create CloudFormation change set: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 2. Resource with id [Apivendor_apiStage] is invalid. Logical ids must be alphanumeric. Resource with id [ControllerFunctionPostHRResultsPermissionvendor_api] is invalid. Logical ids must be alphanumeric.
```

Below is a snippet of the template that was used:

```
Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: vendor_api
```

The template successfully deploys with a StageName that does not contain `_`.  The documentation for API Gateway specifies that a stage name can contain `_`, and we are currently getting around this issue by using a different stage name, then deploying to the `vendor_api` stage using an additional script.

I believe this is a result of the transform using a Cloudformation logical resource id derived from the AWS::Serverless::Api logical resource id and the stage name, and logical resource ids cannot include non-alphanumerical characters.

**Comment by keetonian** [comment]
Correct, the CloudFormation logical ID of the ApiGateway::Stage resource that SAM creates is derived from the `StageName` property and the name of the `Serverless::Api`.

**Comment by praneetap** [comment]
If anyone is interested in contributing this fix, [here](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/api/api_generator.py#L188) is where the fix would need to be made.

**Comment by eduardovra** [comment]
So the solution should be to not concatenate the StageName string in the ApiGateway::Stage logical ID anymore. Is this correct ?

**Comment by ShreyaGangishetty** [comment]
Closing this issue as v1.15.0 is released
