### ISSUE TITLE
Circular test dependency with cfn-lint

### ISSUE THREAD

**Issue by glaubitz** [awslabs/serverless-application-model#1008]
In #888, a test dependency was added on ```cfn-lint``` which poses a problem for distributions packaging ```cfn-lint``` due to the circular dependency this introduces (in my case openSUSE/SLES).

Since we are always running the testsuites for all the packages we are maintaining, we are now stuck in the situation that ```cfn-lint``` cannot be built because it depends on ```aws-sam-translator``` which in turn depends on ```cfn-lint```.

So, we're now stuck in the situation that we can't update neither ```cfn-lint``` nor ```aws-sam-translator``` as the update would introduce a circular build dependency.

Do you have any suggestion on how to sort this issue out besides just disabling the testsuites for both packages?

I will also try to find out whether there is a possibility to sort out the circular dependency in SUSE's OBS by first building the ```aws-sam-translator``` without the testsuite enabled.

**Comment by keetonian** [comment]
This is a problem. I had assumed that, since it was added as a dev dependency, this conflict might not happen. I will investigate this issue.
