### ISSUE TITLE
Using parameters in SAM file in DefinitionUri

### ISSUE THREAD

**Issue by 8357753** [awslabs/serverless-application-model#101]
Hi, FYI in my SAM file this works:
      StageName: !Ref "Env"
      DefinitionUri: "swagger-dev.yml"

But this doesn't work:
      StageName: !Ref "Env"
      DefinitionUri: !Sub "swagger-${Env}.yml"

And this also doesn't work:
      StageName: !Ref "Env"
      DefinitionUri:
        Fn::Join:
        - ''
        - - "swagger-"
          - !Ref: "Env"
          - ".yml"

The error I get is:
"FAILED - Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [Api] is invalid. 'DefinitionUri' requires Bucket and Key properties to be specified"

My parameter is defined as:

Parameters:
  Env:
    Description: The environment id.
    Type: String
    ConstraintDescription: Can contain only one of the supported environment ids.

**Comment by sanathkr** [comment]
I don't see `aws cloudformation package` command supporting full CloudFormation Intrinsics spec anytime. It is a good use-case to use intrinsics for local paths, but very hard for a local tool to provide full fidelity support to intrinsic functions
