### ISSUE TITLE
Include es:ESHttpPut to ElasticsearchHttpPostPolicy 

### ISSUE THREAD

**Issue by Gaurav2Github** [awslabs/serverless-application-model#1010]
**Description:**

Policy Template List currently includes ElasticsearchHttpPostPolicy Template only.

```es:ESHttpPut ``` action is required for certain tasks in Elasticsearch.
eg: 
Creating manual snapshot uses Put request.
https://www.elastic.co/guide/en/elasticsearch/reference/6.7/modules-snapshots.html#_snapshot

It will be useful to make it available in Policy Template List as a separate template 
or 
part of ElasticsearchHttpPostPolicy template.

**Comment by praneetap** [comment]
Pending release v1.14.0

**Comment by ShreyaGangishetty** [comment]
Closing this issue as this is released in v1.14.0
