### ISSUE TITLE
deploy doesn't recognize the updated Zip

### ISSUE THREAD

**Issue by sathiyas** [awslabs/serverless-application-model#102]
I have created new Zip file and uploaded to S3. When I ran I get the following

"No changes to deploy. Stack deploy-lambda is up to date"

How do I force the function update code? I had to destroy and recreate the stack.

**Comment by vikrambhatt** [comment]
What command did you run? Did you manually upload zip to s3?

**Comment by jolexa** [comment]
The Path of the artifact (zip) must change in order for CloudFormation to know it should update.

**Comment by sanathkr** [comment]
@jolexa Yeah, you're right. CloudFormation doesn't read the file again. The path has to change to trigger an update. If you use `aws cloudformation package` CLI command it will do it for you based on ZipFile's hash

**Comment by markwaddle** [comment]
if anyone happens to run across this:
i've found that if the template parameters change then it will update. so i add a required parameter of VERSION and pass in the git SHA.

**Comment by ajsjunior** [comment]
When template has only a `AWS::ApiGateway::RestApi` with a swagger file in the `BodyS3Location`, the `sam deploy` does not detect swagger file has changed, and `sam package` does not upload anything.
