### ISSUE TITLE
[Question] Scripting SAM CLIs and Lambda Versioning best practice

### ISSUE THREAD

**Issue by simon10says** [awslabs/serverless-application-model#1028]
Hi. Newbie here and hope someone can provide some guidance.

I originally posted my question [here](https://github.com/awslabs/aws-sam-cli/issues/1274), but has some follow-up questions.

I uses `Visual Studio SAM project` to create multiple lambda functions, and I've written a script that:
```
sam build
sam package
sam deploy
```
Everything works great. However:
1. `sam package` generates and upload to S3 {UUID} package zip files (one per function). Can I give it a more meaningful name instead of {UUID}?
2. Running my script will always generate and upload new package files even thought I've made no changes to my function. Is there a way/method where it will only build or package IFF there is changes to my function?

Now, I'm planning on the CI/CD to bring it to the team and faces a few dilemma. I'm using the `3 stacks (dev, QA, prod) - 1 template - {stacks}functions` model. When in production, I want my Lambda functions to be backward compatible with my app; so that if I've breaking change in my Lambda function and user has not updated the app, the app still works. So:
### 1. First, I thought of using Lambda Alias:
Everytime I deploy, I will set my `AutoPublishAlias` to a particular alias. In my app, I will use the ARN to the alias. **However,** because `AutoPublishAlias` always removed the previously set alias, this doesn't work
### 2. Then I though of using the Version:
I would use the ARN that points to the particular version. **But,** thinking ahead of cleaning up the artifacts in S3, it will be impossible. I managed to find a [solution](https://lumigo.io/blog/a-serverless-application-to-clean-up-old-deployment-packages/) that delete the artifacts if it is not referenced by any alias. So, this option is not too good too.

Any advice is much appreciated?

**Comment by keetonian** [comment]
Approach 2 is correct, but would need a modification to the `lambda-janitor` application that you linked to check if a version has been invoked recently before deleting it. This can be done by querying CloudWatch metrics for the lambda function.
