### ISSUE TITLE
deploy docs for --parameter-overrides incorrect, Default values requred 

### ISSUE THREAD

**Issue by DALDEI** [awslabs/serverless-application-model#103]
Related to #33 I found 2 issues.

1) Parameters _require_ a Default value or I get the error 

> 
An error occurred (ValidationError) when calling the CreateChangeSet operation: Cannot specify UsePreviousValue on Parameters when ChangeSetType is CREATE

Workaround: provide a Default value for all parameters

2) The --parameter-override arguments are not space `separated` "name=value" pairs as documented, nor are they comma separated.  I have not been able to pass more than one parameter.

Example:

Fails -- Documentation says to use a single space seperated argument.
This provides one parameter "Handler" with the value "email_notify.handler EndPoint=http://myEndpoint" 

```
aws cloudformation deploy --template-file serverless-emailLambdaNotify.yaml --stack-name, TEST2, --capabilities CAPABILITY_IAM --parameter-overrides  "Handler=email_notify.handler EndPoint=http://myEndpoint" 
```

Also Fails

```
aws cloudformation deploy --template-file serverless-emailLambdaNotify.yaml --stack-name, TEST2, --capabilities CAPABILITY_IAM --parameter-overrides  "Handler=email_notify.handler,EndPoint=http://myEndpoint" 
```

**Comment by claudobahn** [comment]
1. That's expected behavior, see first paragraph here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
2. Don't put quotes around the parameter list and do use spaces to separate.

**Comment by alanwill** [comment]
@DALDEI I was running into the same error and it turned out that there was a typo in my YAML file, nothing to do with the actual command or functionality. Looking at your commands you have commas after the `--stack-name` that doesn't look quite right.

**Comment by sanathkr** [comment]
This is tracked here aws/aws-cli#2599. 

Until we fix this bug, you can override the parameter explicitly when you add a new parameter with default value. Just once when you first update the stack. Afterwards, UsePreviousValue should work as expected

**Comment by sanathkr** [comment]
Closing this one and in favor of tracking using the AWS CLI Issue
