### ISSUE TITLE
iot_backend Event properties are incorrect

### ISSUE THREAD

**Issue by singledigit** [awslabs/serverless-application-model#1058]
**Description:**

iot_backend example does not function properly.

**Steps to reproduce the issue:**
1. cd examples/2016-10-31/iot_backend
2. run `sam validate -t template.yaml`
3.

**Observed result:**

Error: [InvalidResourceException('IoTLambdaFunctionIoT', "Type of property 'AwsIotSqlVersion' is invalid.")] ('IoTLambdaFunctionIoT', "Type of property 'AwsIotSqlVersion' is invalid.")

**Expected result:**

template.yaml is a valid SAM Template

**Comment by jlhood** [comment]
@singledigit Hi Eric! Thanks for opening this issue and submitting a PR to fix it! 😊

**Comment by ShreyaGangishetty** [comment]
Closing this issue as v1.15.0 is released
