### ISSUE TITLE
S3FullAccess Policy doesn't grant access to tags

### ISSUE THREAD

**Issue by andreineacsu** [awslabs/serverless-application-model#1063]
Hello,

I am currently working on a SAM application that requires full access on an S3 bucket. 
I'm setting the S3FullAccess policy on the Lambda function that requires full access but it doesn't work because this policy doesn't have access to file tags. Can this policy be modified so that it includes access to file tags and metadata? 

Also, is there any way to define custom SAM policies? 

Thanks,
Andrei

**Comment by keetonian** [comment]
@andreineacsu yes, it is possible to define custom policies on a `Serverless::Function` resource. You can put a policy document into the `Policies` property. Here is an example; please scope it down to the permissions and resources you need.

```yaml
      Policies:
        - Statement:
          - Action: [ 's3:*' ]
            Effect: Allow
            Resource: '*'
```

As for updates to [S3FullAccess policy](https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/policy_templates_data/policy_templates.json#L844-L899), there are several actions that deal with tagging. I think all of these are necessary to support tagging on both objects and object versions, can you confirm this?
* DeleteObjectTagging
* DeleteObjectVersionTagging
* GetObjectTagging
* GetObjectVersionTagging
* PutObjectTagging
* PutObjectVersionTagging

(Taken from the [S3 permissions documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html))

**Comment by andreineacsu** [comment]
@keetonian Thank you for your reply! Everything looks good now. 
The tag related permissions you listed and all needed - at least in my case.

**Comment by keetonian** [comment]
To add these extra permissions, we need to update the [S3FullAccess Policy Template](https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/policy_templates_data/policy_templates.json#L856-L861) with the permissions I listed above in my comment, and update any failing tests.

**Comment by ShreyaGangishetty** [comment]
Closing this issue as v1.15.0 is released
