### ISSUE TITLE
Throw error if Serverless::Application does not reach READY state

### ISSUE THREAD

**Issue by keetonian** [awslabs/serverless-application-model#1070]
**Description:**
If a Serverless::Application resource from the Serverless Application Repository does not reach a ready state soon enough, SAM can time out causing a malformed response to be sent to CloudFormation. SAM should stop polling SAR and either return the resulting template to CloudFormation or throw an error explaining that the SAR application did not enter an available state fast enough and the user should try the deployment again.

Similar to #793

**Steps to reproduce the issue:**
1. Deploy a template with many different SAR applications (bigger the better)

**Observed result:**
Sometimes errors (Malformed response error) the first or second attempt, then starts working

**Expected result:**
Should return a better error message explaining the problem.

**Comment by praneetap** [comment]
We do return the correct error message [here](https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/plugins/application/serverless_app_plugin.py#L297-L298) but internally our Lambda timeout was set too low. We fixed the configuration issue internally, and its currently rolling out.
