### ISSUE TITLE
SSMParameterReadPolicy should include ssm:GetParametersByPath

### ISSUE THREAD

**Issue by studds** [awslabs/serverless-application-model#1071]
**Description:**

The SSMParameterReadPolicy does not include ssm:GetParametersByPath

**Expected result:**

It would be useful to include ssm:GetParametersByPath in SSMParameterReadPolicy.

**Comment by jlhood** [comment]
@studds Totally agree. Thanks so much for bringing this up. This would be a very quick PR for anyone who wants to contribute the change. Update the permissions [here](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json#L1526), then fix failing unit tests to match the new policy template.

**Comment by ShreyaGangishetty** [comment]
Closing this issue as v1.15.0 is released
