### ISSUE TITLE
AWS::AccountId not resolved in FindInMap resolver

### ISSUE THREAD

**Issue by keetonian** [awslabs/serverless-application-model#1075]
**Description:**

`AWS::AccountId` is not resolved when we attempt to resolve FindInMap. This caused a bug when a customer attempted to use the DeploymentPreference property of a Serverless::Function.

**Steps to reproduce the issue:**
1. Create a mapping to `AllAtOnce` (or any CodeDeploy default lambda config) using AWS::AccountId
2. Create a function with `DeploymentPreference: !FindInMap [...]`
3. Deploy

**Observed result:**
SAM doesn't configure the deployment preference properly, and the stack fails deployment
**Expected result:**
Stack should deploy with expected deployment preference.

**Comment by keetonian** [comment]
To fix:

Add AWS::AccountId pseudo parameter here: https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/sdk/parameter.py#L61-L67

Add tests for DeploymentPreference using a mapping with AWS::AccountId as a mapping parameter.

Need to review if it is possible to find this value using boto3 without using extra permissions or if the library needs to be passed the account id value somehow.

**Comment by ShreyaGangishetty** [comment]
Closing this issue as this is released in v1.14.0
