### ISSUE TITLE
SAM Creates Permission by default for Test and Stage Why ?

### ISSUE THREAD

**Issue by ashishusoni** [awslabs/serverless-application-model#1083]
I am seeing SAM is creating multiple aws lambda permission and not sure why 
For every AWS::Serverless::Function defined in the YAML i am getting two permission which is taking away resource how we can avoid this ..

We have named our Stage to something else instead of STAGE and TEST so why would it create permission for stage and test
 

CreateClientModuleFunctionGetEventPermissionStage
CreateClientModuleFunctionGetEventPermissionTest

**Comment by Michael1d** [comment]
Hi @ashishusoni I have read on other posts that the "Test" permission is required by the "Test" button in API Gateway. There has been some discussion around an option for opting out... sorry I don't have the link at hand.

I also find it crazy that with a strict 200 resource limit in CloudFormation, why we are forced to accept extra resources that are not required.

Cheers,

Mike

**Comment by jlhood** [comment]
@Michael1d is correct. The existing issue is #285. Please feel free to +1 it to help us prioritize adding an opt-out of creating the test permission. Closing this issue as a duplicate.
