### ISSUE TITLE
NotificationARNs in Serverless::Application don't accept !Ref

### ISSUE THREAD

**Issue by keetonian** [awslabs/serverless-application-model#1087]
**Description:**

You should be able to !Ref a SNS topic 

**Steps to reproduce the issue:**
1. Create a Serverless::Application that !Refs a Sns topic
2. Try deploying or transforming the template

**Observed result:**
Error
**Expected result:**
Should deploy/transform

**Comment by ShreyaGangishetty** [comment]
Closing this issue as v1.15.0 is released
