### ISSUE TITLE
Confusing Error message for defining S3 event

### ISSUE THREAD

**Issue by rowanu** [awslabs/serverless-application-model#109]
Was getting this error message on a `deploy` command:

```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ResourceFile] is invalid. property Event not defined for resource of type S3
```

The text makes it sound like I'm missing the `Event` property, but the property I was missing was `Events`. Changing my incorrect property name made the error go away.

**Comment by sanathkr** [comment]
The error message is complaining that you specified a property called `Event` that it doesn't recognize. This is indeed confusing given the error message. I have made the required code change.  Will get it deployed in the next release. 

Closing this bug for now because the change is made.
