### ISSUE TITLE
"Invalid permissions on Lambda function" on path parameter

### ISSUE THREAD

**Issue by brettstack** [awslabs/serverless-application-model#110]
If you specify a path like `/users/{userId}`, SAM creates a permission for the source arn ending with "/users/{userId}". I believe this should be "/users/*". Setting path to `/users/*` works, but not documented/obvious.

**Comment by sanathkr** [comment]
Makes sense. This should happen because the wildcard path can be anything. SAM has to parse out wildcards and replace them with '*'.

**Comment by brettstack** [comment]
Solution is to replace variables with * similar to how we are doing for `{proxy+}` https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/eventsources/push.py#L431

**Comment by jlhood** [comment]
Pending v1.14.0 release

**Comment by ShreyaGangishetty** [comment]
Closing this issue as this is released in v1.14.0
