### ISSUE TITLE
quotes removed after transformation

### ISSUE THREAD

**Issue by jameszh** [awslabs/serverless-application-model#1135]
**Description:**
The quotes in  strings:  '08' and '09' are removed when sam-transformed.
But seems only have the issues with '08' and '09', quotes in  '01' ,'02', ... '07' are kept.

**Steps to reproduce the issue:**
Just put in Outputs section of the template.

```yaml
TestValue:
     Value: '08'
```

**Observed result:**
in the packaged.yaml

```yaml
TestValue:
    Value:  08
```

after deployed, it shows as 8.0 (converted to float)

**Expected result:**
in the packaged.yaml

```yaml
TestValue:
     Value: '08'
```

the problem was noticed when I try to create Glue partitions using CF, month '08' and '09' become 8.0 and 9.0 ..

Thanks,
James

**Comment by keetonian** [comment]
This is a bug inside of CloudFormation. Closing in favor of #200
