### ISSUE TITLE
Slack invite link is broken in README.md

### ISSUE THREAD

**Issue by vladibb** [awslabs/serverless-application-model#1163]
**Description:**

While carefully and optimistically navigating into the GitHub landing page of the SAM project, scrolling through the text and finding URL "Join the SAM developers channel (#samdev)" and clicking on it, leads to an expired Slack URL.

Have the community moved somewhere else? which slack? or everybody migrating to Teams?

**Steps to reproduce the issue:**
1. Navigate to https://github.com/awslabs/serverless-application-model
2. Press on "Join the SAM developers channel (#samdev)"

**Observed result:**
This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available.

**Expected result:**
🍺

**Comment by kvasukib** [comment]
Observed the same behavior today. When can an active link be placed?
