### ISSUE TITLE
batch window support for DynamoDB and Kinesis event sources

### ISSUE THREAD

**Issue by rgarcia** [awslabs/serverless-application-model#1168]
**Description:**

https://aws.amazon.com/about-aws/whats-new/2019/09/aws-lambda-now-supports-custom-batch-window-for-kinesis-and-dynamodb-event-sources/

Mentioned in the docs under `MaximumBatchingWindowInSeconds`:
https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html
https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html

**Steps to reproduce the issue:**

1. Open the latest docs for SAM: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
2. Notice that neither DynamoDB nor Kinesis support specifying a batch window

**Comment by praneetap** [comment]
@rgarcia Thanks for reaching out! Good news, this feature was implemented recently https://github.com/awslabs/serverless-application-model/pull/1120, and will be released shortly https://github.com/awslabs/serverless-application-model/issues/1147. Track our releases [here](https://github.com/awslabs/serverless-application-model/projects/3)

**Comment by rgarcia** [comment]
@praneetap awesome, thanks!
