### ISSUE TITLE
Add Secondary Indexes to SimpleTable

### ISSUE THREAD

**Issue by bjinwright** [awslabs/serverless-application-model#118]
Please add the ability to specify secondary indexes and provisioned throughput.

**Comment by jolexa** [comment]
You can set `ProvisionedThroughput` already https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable

Further, the docs specify that if you need a non-"simple" table to drop out to traditional cloudformation instead, for things like secondary indexes. I can see both points, to be honest.

**Comment by sanathkr** [comment]
Yeah, so you should just use `AWS::DynamoDB::Table` if you need all the jazz of DDB. If you want something quick and easy, use `AWS::Serverless::SimpleTable`.
