### ISSUE TITLE
add KMSEncryptPolicy policy template

### ISSUE THREAD

**Issue by jlhood** [awslabs/serverless-application-model#1186]
**Description:**

SAM policy templates has a [KMSDecryptPolicy](https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/policy_templates_data/policy_templates.json#L774), but no KMSEncryptPolicy that allows `kms:Encrypt` action. This issue is to add a KMSEncryptPolicy that is almost identical to KMSDecryptPolicy, but has `kms:Encrypt` action instead of `kms:Decrypt` action. Should be a simple update. Here's an example of a past PR that added a new policy template for reference: #904

**Comment by john-aws** [comment]
Is this policy actually useful as written? It can't be used to encrypt data to an SNS topic, for example, because the `KMSEncryptPolicy` policy doesn't include `kms:GenerateDataKey`.
