### ISSUE TITLE
Any way to avoid duplicating API code across all Lambda functions?

### ISSUE THREAD

**Issue by jccrowley** [awslabs/serverless-application-model#120]
Hello!

I've been playing around with this model and one of the things I'm noticing if that if you ~~define~~ implement your entire API in one file, the whole API is duplicated across every Lambda function that gets created (such as in the api_backend example), which seems cumbersome if there are many endpoints. Is there a way to have the convenience of implementing the API in one file while simultaneously distributing it across all Lambda functions without duplication? Or are there other best practices in place that I'm unaware of?

Any help would be much appreciated!

**Comment by mpilar** [comment]
@jccrowley you can define the API on it's own as a `Resource` then `Ref` the resource. There is an example of this on `api_swagger_cors` [here](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/template.yaml).

**Comment by jccrowley** [comment]
My apologies, I misspoke in the description of my question. I actually meant "I'm noticing if that if you **implement** your entire API in one file, the whole API is duplicated across every Lambda function that gets created." So, suppose you have a .js file with many API endpoints implemented. Is it possible to create many Lambda functions which execute these endpoints, without each Lambda function containing the entire .js file?

**Comment by sanathkr** [comment]
@jccrowley I don't quite understand your question. If you want each API to use a separate .js file, then you should do the split yourself. SAM can't do anything here. 

Reopen if I misunderstood your question.
