### ISSUE TITLE
SAM API Usable Across Stacks

### ISSUE THREAD

**Issue by gakinson** [awslabs/serverless-application-model#1206]
**Description:**
I created two stacks in CodePipeline, one beta and one prod. When the SAM template file gets executed, it creates TWO separate APIs in ApiGateway with the exact same name,  but different identifiers.

What I actually wanted was one API, but with two different stages, one beta and one prod.

It would be nice if cloudformation would fine the API based on name and if the API already exists then just reuse that and add the stage.

**Steps to reproduce the issue:**
1. Create SAM template with API resource
2. Set the name to be the same
3. Set stage to be reference to the stage variable
4. Create two deployment stages, one for beta and one for prod
5. Execute code pipeline

**Observed result:**
Two Separate APIs in Api Gateway with the same name
**Expected result:**
One Api with two stages, one beta and one prod

**Comment by keetonian** [comment]
@gakinson we recommend to make different APIs in different stacks for preprod/prod environments. There is a larger discussion in #198 about this.

What is your use case? Does it not work to separate your preprod and prod APIs?

**Comment by praneetap** [comment]
Here is another thread you can read for recommended safe deployment practices https://github.com/awslabs/serverless-application-model/issues/304#issuecomment-366113061

**Comment by gakinson** [comment]
Thank you for the responses.
It makes sense, but I was primarily trying to leverage stages, one for beta and one for production. I didn't really need there to be two separate API's. They both accomplish what I want, but I thought there should be someway to leverage an existing API in SAM if you wanted.

Feel free to close this.
