### ISSUE TITLE
SNS event's new SqsSubscription option does not follow recommended configuration

### ISSUE THREAD

**Issue by ljacobsson** [awslabs/serverless-application-model#1209]
When setting `SqsSubscription: true` on an SNS event, SAM will put a queue without any properties set in front of the lambda function. 

According to AWS docs, the VisibilityTimeout should be set to give lambda's retry logic a chance to retry twice before the message becomes available:

https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html
> To allow your function time to process each batch of records, set the source queue's visibility timeout to at least 6 times the timeout that you configure on your function. The extra time allows for Lambda to retry if your function execution is throttled while your function is processing a previous batch.

Would also be nice if there were optional properties to build a `redrivePolicy` and a DLQ so messages don't retry relentlessly for 4 days.

**Comment by jlhood** [comment]
@ljacobsson Thanks for bringing this up. The current `SqsSubscription: true` feature was part of the solution proposed in #854. There is additional work to do to support further configuration of SQS, but it should be tracked under that issue. You bring up a good point though that SAM should allow use cases where more advanced SQS queue configuration is needed. I'll update #854 with this additional requirement.
