### ISSUE TITLE
AWS::Serverless::SimpleTable  - Primary Key Type 'Number' creates table with 'String' Primary Key

### ISSUE THREAD

**Issue by jiravani** [awslabs/serverless-application-model#121]
This template creates a DynamoDB Table with a Primary Key of Type `String` instead of `Number`
```
MySimpleTable:
    Type: 'AWS::Serverless::SimpleTable'
    PrimaryKey:
      Name: id
      Type: Number
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
```
Unless I am misreading the documentation (below), this isn't intended behavior.

<img width="884" alt="screen shot 2017-04-11 at 17 09 26" src="https://cloud.githubusercontent.com/assets/5256796/24934706/766c75de-1eda-11e7-8012-9026998ce160.png">

https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#primary-key-object

**Comment by schallis** [comment]
I'm having a similar issue and it seems like the PrimaryKey parameter is ignored entirely. I have it set to `Name: button` and it still creates pk as `id`

**Comment by vikrambhatt** [comment]
PrimaryKey should be under properties: 

```
MySimpleTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: button
        Type: Number
```

**Comment by sanathkr** [comment]
I will update the spec to include `Properties` key in examples because many people are tripping over it.
