### ISSUE TITLE
V1.20.0 Release Tracker

### ISSUE THREAD

**Issue by ShreyaGangishetty** [awslabs/serverless-application-model#1212]
### Public Release tracker
To get a look at where this release is in our internal pipeline look at our Github [release board](https://github.com/awslabs/serverless-application-model/projects/3)

### Changelog
1. fix: actually exclude test files from being installed (#1132) 
1. docs: fix link to Github issues (#1149) 
1. docs: updated MethodSettings from API Gateway (#1170)
1. feat: custom domains Api Gateway support (#1144) 
1. feat: Custom domains route53 support (#1165)
1. chore: fix slack channel link (#1177)
1. fix(policy-templates): update DynamoDBCrudPolicy (#1173)
1. fix: fix sns publish (#1200)
1. feat (policy template): added KMSEncryptPolicy policy template and related test changes (#1192)
1. docs: fix CORS documentation regarding API Gateway literal values (#1198)
1. ~~fix: allow Authorizer: NONE when using custom swagger (#1211)~~ **Reverted in #1357**
1. docs: update Greengrass Hello World examples (#1191) 
1. docs: change references to Swagger to OpenAPI (#1199) 
1. fix: add intrinsic support for deployment preference enabled (#1196) 
1. docs: fix yaml code block for authorizers (#1214) 
1. chore(deps): bump pillow in /examples/2016-10-31/image_resize_python (#1215)
1. feat: add support for TriggerConfigurations in DeploymentConfiguration (#1195)
1. fix: adding support to point to api gateway distribution (#1230)
1. feat: function role tag propagation (#1194) 
1. chore: typo in swagger.py (#1220)
1. fix: failed tests (#1234) 
1. chore(docs): fix a cognito event source example (#1233) 
1. fix: throw better error for improper api reference (#1224) 
1. feat: adding VPC Access Policy when VpcConfig is present (#1228) 
1. fix: throw error when method authorizer is present and api auth is not defined (#1282)
1. docs: correct spelling in README (#1243)
1. fix: destination config link (#1270)
1. feat: add sqs and sns policies based on destination config (#1299)
1. fix: transform cognito events to a eermission with `sourcearn` (#1260)
1. chore: add Python 3.8 as supported version (#1256)
1. docs: prettify generated_resources document (#1247)
1. examples: add Lambda ARN to inbound-ses-spam-filter outputs (#1294)
1. feat(EventBridge): add new EventBridgeRule SAM Function EventSource (#1241)
1. feat(policy-template): adding cloudwatch:describeAlarmHistory policy (#1264)
1. fix: update failing tests(#1306)
1. build: add AppVeyor config to move away from Travis (#1263)
1. feat(policy-template): allow kinesis:DescribeStreamSummary for Kinesis CrusPolicy and KinesisStreamReadPolicy (#1259)
1. fix(policy-templates): update arn format of DynamoDBStreamReadPolicy (#1222)
1. feat: add authorizationscopes (#917)
1. chore: merge pull request #1306
1. feat(policy-templates): add AthenaQueryPolicy template (#1137)
1. chore: fix failing tests (#1312) 
1. chore: fix the SAM Slack Community link (#1318) 
1. fix: amend provisioned concurrency examples and templates to work for false condition (#1288)
1. feat: Add an existing SQS queue option to SNS event (#1231) 
1. fix: remove unsupported options for openapi3.0 (#1316)
1. feat: add AssumeRolePolicyDocument to AWS::Serverless::Function (#1311)
1. fix: handle explicit null in nested app SemanticVersion (#1334)
1. Remove SAR example applications (#1341)
1. fix: updated the lambda permission with the correct case (#1319)
1. feat: support for lambda event destinations (#1321)
1. chore: Adopt black formatting (#1322)
1. docs: adding official docs page in versions.md (#1340)
1. fix: redeploy api when function name changes (#1235)

**Comment by 140eight** [comment]
Do intrinsic functions supported in v1.16? (#1179 )

**Comment by unscriptable** [comment]
Looks like 1.16.0 was [released](https://github.com/awslabs/serverless-application-model/releases/tag/v1.16.0)?  But I don't see release notes about the features above.  Can somebody clarify?  Thanks!

**Comment by praneetap** [comment]
@140eight I don't think that change is going to make the cut for v1.20 unfortunately. But it's on top of the list for the next release.
@unscriptable There were four releases for the new launch announcements during re:invent, which bumped the release version up to 19. You can find the release notes for each release [here](https://github.com/awslabs/serverless-application-model/releases)

**Comment by keetonian** [comment]
#1211 (fix for #984) was rolled back (#1357) due to finding regressions in the fix.

**Comment by praneetap** [comment]
https://github.com/awslabs/serverless-application-model/pull/1371
