### ISSUE TITLE
SAM Template spec missing section for Parameters

### ISSUE THREAD

**Issue by mikelax** [awslabs/serverless-application-model#1219]
**Description:**

After spending some time reading up on SAM and reviewing the documentation on github, the aws docs site, and the template file I found that there is several items missing from the documentation, In particular there is no documentation (that I found) that talked about the `Parameters` top-level section. I was able to figure it out after a short time with some googling, but that was mainly also aided by my experience with the serverless framework and cloudformation. 

**Steps to reproduce the issue:**
1. Review the [Template Spec](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md), the [aws docs website](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template.html)
2. Observe there is no documentation in any of these locations

**Observed result:** There is no mention of the `Parameters` section

**Expected result:** There should be documentation that describes Parameters with the supported attributes:  type, description, allowedvalues, default. At the very least the section could point to the corresponding documentation on CFN.

**Comment by mikelax** [comment]
I'm happy to open a quick PR for the template or updating any other docs to add this information, or point to the corresponding cloudformation docs.

**Comment by keetonian** [comment]
@mikelax thank you for reporting this! We are working on a major documentation refresh and I just verified that this is part of it!
