### ISSUE TITLE
Stack createion fails when using --parameters-override

### ISSUE THREAD

**Issue by duckboy1981** [awslabs/serverless-application-model#122]
When using the `cloudformation deploy` command with `--parameter-overrides`, stack creation fails with the following message -

> An error occurred (ValidationError) when calling the CreateChangeSet operation: Cannot specify UsePreviousValue on Parameters when ChangeSetType is CREATE

I'm using the following command -

    aws cloudformation deploy \
        --template-file template.yaml \
        --stack-name "TestStack" \
        --region eu-west-1 \
        --parameter-overrides \
            Environment="BVT"
            S3BucketName="bvt-dump-payload-test-eu-west-1"

My template contains the following Parameters definition -

    Parameters:
      Environment:
        Type: String
        Description: The environment that is being deployed to, such as BVT, UAT, etc.
      S3BucketName:
        Type: String
        Description: The S3 Bucket to which the Lambda Function will output payloads.

I had found an issue on here suggesting tha tyou needed to declare a default value in the template, but that also produces the above error.

**Comment by digitalfiz** [comment]
If your paste is correct then you missed a `\` after `Environment="BVT"` which would leave the `S3BucketName="bvt-dump-payload-test-eu-west-1"` out of the command. It would actually run `S3BucketName="bvt-dump-payload-test-eu-west-1"` as a separate command.

**Comment by duckboy1981** [comment]
Ah, that is indeed the issue!

Fooled by the red herring returned by AWS, I assumed the command was correct and didn't consider it as the source of the problem.

Thanks for posting.

**Comment by digitalfiz** [comment]
np!
