### ISSUE TITLE
Associating an API model to a Lambda function should enable a request body validator.

### ISSUE THREAD

**Issue by brysontyrrell** [awslabs/serverless-application-model#1232]
**Description:**

With the recent addition of `Models` to the `AWS::Serverless::Api` resource I began working on removing all of my Swagger definitions from an API and rely only on the SAM resources. I rely on request body validation with API Gateway to verify good JSON payloads are bing provided before my function code is invoked. To me, building a serverless API, this is the key feature, behavior, and reason for associating a model with a method-path.

When I went to test an API configured using only SAM resources I found that this is not the behavior when the API Gateway is created. The request body validator is not enabled even though I am supplying a model/schema. From my perspective I don't see how adding models provides functional value to my applications if they aren't being used to validate requests - it's functionality I have to move back into my codebase now, or I have to go back to defining the entire Swagger doc with all of the API Gateway extensions again. 

**Steps to reproduce the issue:**

Create a `AWS::Serverless::Api` resource and associate a model with it.

Create a `AWS::Serverless::Function` resource and associate it with a method-path and the model.

**Observed result:**

The model is associated with that method-path, but request body validation is not enabled. The underlying Lambda functions are invoked even if invalid requests are being performed.

**Expected result:**

The model is associated with the method-path and request body validation is enabled. The underlying Lambda functions are not invoked when invalid requests are performed.

**Comment by praneetap** [comment]
@brysontyrrell This is a known api gateway gap that is being tracked in https://github.com/awslabs/serverless-application-model/issues/931#issuecomment-534463087. Closing this issue in favor of #931
