### ISSUE TITLE
How to reference an existing s3 bucket & prefix

### ISSUE THREAD

**Issue by wliao008** [awslabs/serverless-application-model#124]
From this example: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/s3_processor/template.yaml, it creates a new bucket. However I need to reference an existing bucket, for example, I want to trigger the lambda when a *.yaml file is uploaded to `s3:/mybucket/folder`?

**Comment by vikrambhatt** [comment]
Hi,

At this moment SAM does not support an existing bucket as an event source. It is mentioned in the documentation:
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3

"NOTE: To specify an S3 bucket as an event source for a Lambda function, both resources have to be declared in the same template. AWS SAM does not support specifying an existing bucket as an event source."

**Comment by wliao008** [comment]
Hmm ok, but I do need to have the lambda listen on an existing bucket/folder, what are the walkarounds if I still want to make use of SAM?

**Comment by iconara** [comment]
I just came across this too. Will this be fixed? This makes SAM very hard to use for the S3 event use case.

**Comment by sbarski** [comment]
I want to up-vote this well. At the moment this is a showstopper for me too.

**Comment by vikrambhatt** [comment]
This is not supported in Cloudformation. Basically, cloudformation cannot change any aws resource outside of the stack. Unfortunately, as of now, there is no workaround for this limitation.

**Comment by sbarski** [comment]
@vikrambhatt do you think AWS will come out with any tooling on top of SAM/CFN to assist with cases such as this. It does makes SAM hard to use unfortunately.

**Comment by mwarner1** [comment]
It is possible to have CFT send parameters to and invoke a lambda process where you can programmatically make changes to existing resources. However, note that your lambda has to also be able to delete any changes it makes when the stack is deleted (CF will not know about these changes and cannot auto-delete them).

**Comment by sanathkr** [comment]
Yeah, CloudFormation folks are aware of this limitation and working to solve it. We don't have an ETA yet, but I want to let you guys know that this is in the works. 

I am going to close this Issue because SAM is helpless without the CFN feature.

**Comment by helenoalves** [comment]
I know this issue is closed, but, when will we have some news about it ?

**Comment by sanyer** [comment]
Faced this limitation this limitation recently and workaround with combination of S3->SNS and SAM<-SNS. Works pretty good and completely automated.

**Comment by helenoalves** [comment]
Thanks @sanyer for your feedback !
I never used SNS before, amazon has a lot of amazing tools and I dont know all.
Me and my friend @alexiscviurb , an amazing infrastructure engineer, created a script to automate the task in a Jenkins Pipeline.
This shell script is doing this steps:
1. Create With Cloud Formation The Functions

2. List stack resources:
aws cloudformation list-stack-resources --stack-name analytics-functions --query 'StackResourceSummaries[?LogicalResourceId==`'$1'`].[PhysicalResourceId]' --output text

3. Get Lambda Functions:
aws lambda list-functions --query 'Functions[?FunctionName==`'$FunctionName'`].[FunctionArn]' --output text

4.  Replace in SAM JSON FunctionName
sed -i "s/FunctionName::ARN/$FunctionName/" sam-configuration.json

5. Remove old Functions of Bucket
aws s3api put-bucket-notification-configuration --bucket=bucket-name --notification-configuration="{}"

6. Bind the new Functions with Bucket
aws s3api put-bucket-notification-configuration --bucket=bucket-name --notification configuration file://sam-configuration.json

It's a workauround too, but I hope it helps somebody.
Regards,
Heleno

**Comment by rzijp** [comment]
@sanyer, any chance that you could share more details about your automation? Did you use SAM (not sure if this is limited by #249 as well), or other means?

**Comment by sanyer** [comment]
@rzijp I'll try to remember and find where and how it was done.

**Comment by Eldavid** [comment]
For existing s3 bucket, you can use this [serverless plugin](https://www.npmjs.com/package/serverless-plugin-existing-s3).

**Comment by golharam** [comment]
Well this just sucks.   We should be able to specify arn references to existing buckets.  You allow it for ManagedPolicyArns for IAM ROLE, referencing a bucket shouldn't be an issue...unless a change is being made on the bucket itself?

**Comment by sworisbreathing** [comment]
If that's the case then [the documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#example-awsserverlessfunction) is incorrect, since it gives an example of referencing a bucket that is not managed by SAM.

**Comment by didopop3** [comment]
> If that's the case then [the documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#example-awsserverlessfunction) is incorrect, since it gives an example of referencing a bucket that is not managed by SAM.

it has clearly said "to specify an S3 bucket as an event source for a Lambda function, both resources have to be declared in the same template. AWS SAM does not support specifying an existing bucket as an event source."
 https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#example-awsserverlessfunction

We need the feature to reference an existing s3 bucket

**Comment by metaskills** [comment]
The limitation of CloudFormation makes complete sense to me. I was initially upset to hit this limitation myself and put my head down on what I think is a good workaround that fits both CloudFormation and SAM best practices. Of course, using Bash as a little bit of IaC glue as needed. The solution, first use no event in your template.yaml file and also add permission for the S3 bucket to invoke the function. To also make this work, output the functions arn. Pretty much what @helenoalves shared.

```yaml
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Runtime: ruby2.5
  ImageBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MyFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub arn:aws:s3:::my-bucket-name

Outputs:
  MyFunctionArn:
    Description: My Function Arn
    Value: !GetAtt MyFunction.Arn
```

In order to connect the S3 events a little one time Bash script, I usually put these in the projects `ops` directory, is used.

```shell
FUNCARN=$(aws cloudformation describe-stacks \
  --stack-name "my-stack-name" \
  --query 'Stacks[0].Outputs[0].OutputValue'
)

JSON=$(cat <<-EOF
  {
    "LambdaFunctionConfigurations": [
      {
        "Id": "MyEventsName",
        "LambdaFunctionArn": ${FUNCARN},
        "Events": [
          "s3:ObjectCreated:*"
        ]
      }
    ]
  }
EOF
)

aws s3api \
  put-bucket-notification-configuration \
  --bucket="my-bucket-name" \
  --notification-configuration "$JSON"
```

**Comment by dragonfax** [comment]
Just another "me too". I hit this today.

**Comment by tomcant** [comment]
I hit this issue recently and used the solution proposed above by @metaskills as a workaround. I've written a Bash script to make the whole thing a bit simpler. Hopefully someone else that lands on this thread will find it useful, and if anyone wants to suggest an improvement then please do: https://gist.github.com/tomcant/c31a08123673e91d9560737f4380cff0.

Here's the script usage information:
```
Configure an S3 bucket ObjectCreated notification for the given Lambda function.

Usage: ./configure-s3-lambda-notification.sh BUCKET FUNCTION

Arguments:
  BUCKET     name of the S3 bucket that should trigger the notification
  FUNCTION   name of the Lambda function that should receive the notification
```

The script uses the [AWS CLI](https://aws.amazon.com/cli/) (tested with version 1.14.44) so you'll need to supply valid AWS credentials for the account containing the resources. How you invoke the script depends on how you supply your credentials. I usually set the `AWS_PROFILE` environment variable or a combination of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, like this:
```
AWS_PROFILE=profile ./configure-s3-lambda-notification.sh BUCKET FUNCTION
```
or...
```
AWS_ACCESS_KEY_ID=key AWS_SECRET_ACCESS_KEY=secret ./configure-s3-lambda-notification.sh BUCKET FUNCTION
```
If you provide your credentials in some other way (e.g. EC2 instance metadata) then running the script without the extra environment variables should work just fine.

The script also takes care of adding permissions for S3 to invoke the function, if necessary. I think the biggest limitation right now is that the script doesn't support setting filters on the notification (e.g. path prefix/suffix), but that can easily be updated on the bucket UI afterwards.

Note that the [jq](https://stedolan.github.io/jq/) JSON processor is also required.

**Comment by OscarVanL** [comment]
Ran into this today too, kinda disappointed this isn't supported.

**Comment by sbilello** [comment]
+1

**Comment by NiminU** [comment]
Need this functionality for one of our use cases, hope this will be considered soon.

**Comment by gilshelef** [comment]
+1

**Comment by subzero112233** [comment]
+1

**Comment by valeramaniuk** [comment]
+1

**Comment by IanLeeClaxton** [comment]
+1 The only other option is terraform but this has its issues too.

**Comment by djm** [comment]
Amazon just released [CloudFormation support for importing existing resources into a given stack](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import.html). I haven't tried it yet, but it does sound like this was the upstream feature this thread was waiting for so I thought I'd share.

**Comment by andrx** [comment]
+1

**Comment by ecmonsen** [comment]
+1

**Comment by kaushalye** [comment]
+1

**Comment by mozimos** [comment]
+1

**Comment by johnjichaowei** [comment]
+1

**Comment by IanLeeClaxton** [comment]
+1 Thanks

Ian Claxton
Director | OTIITO LTD
+44 (0)7926 040509

________________________________

**Comment by keetonian** [comment]
@djm I looked into that for this particular problem. It works if you only have one stack that needs to reference the bucket; if you want to reference it from multiple stacks, however, it doesn't work and another solution is needed.

**Comment by CJohnsonLehi** [comment]
Can't believe this is still an issue. It could have simply been solved by adding an extra property to each resource called: `Existing`: <true|false>

**Comment by nicofuccella** [comment]
+1

**Comment by Kinnary-Raichura** [comment]
+1

@CJohnsonLehi : `Existing: <true|false>` works for serverless framework, and not for SAM model

**Comment by maxalbrecht100** [comment]
+1. Just to note that this functionality/issue was requested 2 and a half years ago.

**Comment by austingriff** [comment]
+1

**Comment by austingriff** [comment]
honestly i'm about to abandon SAM and just go straight cloud formation. without this feature SAM is useless

**Comment by maxalbrecht100** [comment]
For anyone looking for a workaround:

I ran my CloudFormation template without the event, and added the event afterward manually on the aws console. It's not ideal, but I only had to do it once, and I have been able to update the code in the lambda function without issues.

**Comment by robin-zhao** [comment]
+1

Still an issue.

**Comment by sahil-gt** [comment]
+1
No updates as to what the situation is regarding this issue?

**Comment by miekassu** [comment]
+1
We need this.

**Comment by robinbernon1** [comment]
+1

**Comment by martimfj** [comment]
+1

Still an issue.

**Comment by adamclark64** [comment]
...Still an issue.

**Comment by keetonian** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/79

**Comment by thenninger** [comment]
+1

**Comment by victor-samson-mo** [comment]
+1

**Comment by adamclark64** [comment]
+1?

**Comment by cellistigs** [comment]
+1

**Comment by mischka** [comment]
+1

**Comment by ranajoyviraj** [comment]
going for a new bucket rather than waiting

**Comment by adfer** [comment]
Check this example: S3-to-EventBridge 
Explaination: Consuming events from existing S3 buckets
 -> https://aws.amazon.com/blogs/compute/using-dynamic-amazon-s3-event-handling-with-amazon-eventbridge/
Source code: https://github.com/aws-samples/s3-to-lambda-patterns/blob/master/eventbridge/2-existing-bucket/template.yaml

**Comment by joshi95** [comment]
Much needed feature !!

**Comment by Go-Pomegranate** [comment]
What a disappointment...  switching to serverless now, sry guys.

**Comment by FilipBartos** [comment]
+1

**Comment by mherma1979** [comment]
+1

**Comment by RajivSah** [comment]
+1 :(

**Comment by armitagemderivitec** [comment]
+1

**Comment by yang-xiaodong** [comment]
+1

**Comment by jfuss** [comment]
Since there is still activity here: Please leave a +1 (not leave a comment but the reaction on the top comment in the issue) on this issue: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/79, as SAM cannot do anything due to the lack of support in CloudFormation.
