### ISSUE TITLE
Support the New Lambda Destinations Feature

### ISSUE THREAD

**Issue by ConnorMinielly-gShift** [awslabs/serverless-application-model#1269]
**Feature Request**
AWS recently announced the ability to point the result of your lambda operations at specific destinations, supported in cloud formation via the [EventInvokeConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventinvokeconfig.html) sub-resource (`AWS::Lambda::EventInvokeConfig`).

This feature allows you to funnel successful and fialed invokation results to different sources, including other lambdas, SQS queues, and more. The release of this feature is detailed [here](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-destinations/) on the AWS blog.
The blog mentions this feature being usable through both cloudformation and AWS SAM, though it doesn't seem that SAM yet supports it or has any mention of it in the docs/PRs that I could find.

Can we get this on the roadmap? It would be extremely helpful for setting up simple SAM application logic flows for which step functions are messy and overkill but manual code invocations require extra dependencies and code.

Thanks team!

**Comment by catolicasc** [comment]
how to add this feature in serverless.yml
