### ISSUE TITLE
S3 Notification to an Aliased Lambda?

### ISSUE THREAD

**Issue by RAbraham** [awslabs/serverless-application-model#128]
Hi,
My intent is to create an aliased Lambda function and have a S3 bucket configured to invoke the aliased lambda when an object is created in that bucket.

Using `AWS::Serverless::Function` and the `Events` subkey, I can configure a non-aliased lambda function to be invoked.

However, I don't know how to make S3 invoke an aliased lambda function using the SAM template. I couldn't find documentation so I am guessing this is a feature request?

I was able to create an alias for my lambda function using `AWS::Lambda::Alias` but am unable to configure S3 with the ARN of the aliased lambda.

**Comment by sanathkr** [comment]
Create the alias using `AWS::Lambda::Alias` resource and use `!GetAtt <logical-id-of-alias>.Arn` in the S3 Event specification to point to the alias.

**Comment by jfuss** [comment]
@RAbraham This is now the default behavior if you use/set the ```AutoPublishAlias``` Property on the ```AWS::Serverless::Function```. Said explicitly, SAM will wire up event sources to the Alias if this field is set, otherwise will connect events to the Lambda Function.

Resolving since this is now fully supported in SAM

**Comment by smber1** [comment]
Awesome, was wondering just this!

**Comment by sharabash** [comment]
"Create the alias using AWS::Lambda::Alias resource and use !GetAtt <logical-id-of-alias>.Arn in the S3 Event specification to point to the alias."

This doesn't make sense. On what property of the S3 Event specification would you set the Arn of the Lambda alias? The documentation only describes 3 possible properties, none of which are relevant:

https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3

"Bucket," "Events," and "Filter"...
