### ISSUE TITLE
CodeUri should accept path outside of the current region

### ISSUE THREAD

**Issue by jolexa** [awslabs/serverless-application-model#129]
Hello,

Since S3 is a global resource, it seems odd that there is a restriction that a CodeUri path must be in the same region as a Function. It seems logical that I can make `s3://some_bucket/artifact.zip` a publically accessible resource and then anyone should be able to use it from any region.

There are also inconsistencies within the AWS ecosystem on this practice. For example, a nested stack (`AWS::CloudFormation::Stack`) cloudformation template can be in any region (publically accessible) and then you use a `https://s3.amazonaws.com/...` url

**Comment by sanathkr** [comment]
It is a limitation on the Lambda service API which doesn't access resources specified in another region. SAM can't do much here. 

It is a common practice in many services to limit cross-region calls.
