### ISSUE TITLE
Missing CORS configuration for HttpApi

### ISSUE THREAD

**Issue by charsleysa** [awslabs/serverless-application-model#1295]
**Description:**

The newly released HttpApi type has support for CORS configuration through CloudFormation but it seems to be missing from SAM ([see CF docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-api.html#cfn-apigatewayv2-api-corsconfiguration)).

**Comment by keetonian** [comment]
Correct. This will be a follow-on item to our launch for HttpApis.

**Comment by hgl** [comment]
When referencing `ApiId` in a HttpApi event source, could I directly reference the api id of `AWS::ApiGatewayV2::Api` to bypass `AWS::Serverless::HttpApi`? What benefits do I lose?

**Comment by ShreyaGangishetty** [comment]
This is released in [v1.22.0](https://github.com/awslabs/serverless-application-model/releases/tag/v1.22.0)
