### ISSUE TITLE
No documented stage return value from AWS::Serverless::Api

### ISSUE THREAD

**Issue by Nalha** [awslabs/serverless-application-model#13]
The event source Api states that RestApiStage 
"Typically, this is set to the stage name attribute of an AWS::Serverless::Api resource defined in this template." 
yet the AWS::Serverless::Api does not have any, at least documented, stage return attribute.

**Comment by sanathkr** [comment]
Refer to #12. This feature is not supported. We have cleaned up the doc to clarify
