### ISSUE TITLE
InlineCode doesn't work for Node JS 12

### ISSUE THREAD

**Issue by mikebroberts** [awslabs/serverless-application-model#1303]
The following resource

```
  DemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      InlineCode: |
        exports.handler = function(event) {
          console.log("Hello World");
        }
```

gives the following CloudFormation error:

"ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, python2.7, python3.6, python3.7."

**Comment by keetonian** [comment]
This is a configuration on Lambda and not in SAM, could you open a case with [AWS Support](https://console.aws.amazon.com/support/home) instead?
