### ISSUE TITLE
Allow setting TimeoutInMillis for API (HttpApi/Api) event types

### ISSUE THREAD

**Issue by Lanchez** [awslabs/serverless-application-model#1317]
### Describe your idea/feature/enhancement

HTTP API integrations have 5000ms default timeout versus 29000ms on REST API. There should be a way to set timout per integration since 5000ms is simply too low for some cases.

### Proposal

It would be perfect if timeout could be configured per API event in function definitions. In Cloudformation AWS::ApiGatewayV2::Integration and AWS::ApiGateway::Method->Integration allows setting TimeoutInMillis. Maybe this could be set in each API/HttpApi events?

**Comment by acm38** [comment]
We are also declaring our HTTP API using SAM and would like this feature.

**Comment by keetonian** [comment]
Looks like there is an OpenApi integration for this: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html

Can add `TimeoutInMillis` as a property here: https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/eventsources/push.py#L937

Then add it into the open api editor for this feature.

**Comment by ShreyaGangishetty** [comment]
This is released in [v1.22.0](https://github.com/awslabs/serverless-application-model/releases/tag/v1.22.0)

**Comment by andrewpatto** [comment]
Just as a note: if the TimeoutInMillis is set to a value greater than 30000 - it will silently fail to deploy the http integration. It is not prevented in SAM, and even worse it does not generate any warnings or errors during the cloud formation deploy - it just fails to connect everything up correctly.
