### ISSUE TITLE
Question on api_swagger_cors example

### ISSUE THREAD

**Issue by huanghke** [awslabs/serverless-application-model#132]
I would appreciate some guidance here from anyone who has managed to successfully deploy api_swagger_cors example. 

I have replaced both <<region>> and <<account id>> as instructed. However, CloudFormation stack creation failed with the following error:
 
**Errors found during import: Unable to put integration on 'ANY' for resource at path '/': Invalid integration URI specified**

I'm not sure what this error mean. Much appreciated for your help.

**Comment by dimitrovs** [comment]
I think it means it can't find your Lambda. I had more luck using inline swagger and referencing my Lambda function with `                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
`

**Comment by sanathkr** [comment]
There is a bug with the template. It should use !GetAtt instead of !Ref to get ARn of the Lambda function.

I have fixed the template. Can you check now?

**Comment by homingli** [comment]
I have my SAM template refer to external swagger yaml file. Following the example...

https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/swagger.yaml#L23

I defined my variable exactly the same way. It didn't work for me. The resulting API for the method shows `${stageVariables.LambdaFunctionName}` instead of the actual function name.

**Comment by homingli** [comment]
Okay, thanks @dimitrovs!

In my subsequent deployment, `LambdaFunctionName: !GetAtt notHotdogFunction.Arn` in SAM template and `${stageVariables.LambdaFunctionName}/invocations` in Swagger definition
seems to have fixed the issue.

**Comment by jfuss** [comment]
This issue is fixed and therefore closing.

**Comment by chroto** [comment]
hey @jfuss . FYI  It looks like the api_swagger_cors example still has the incorrect swagger and template yaml. https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/swagger.yaml#L24 

there should be an output called `LambdaFunctionName` in SAM template and `${stageVariables.LambdaFunctionName}/invocations` in swagger def as described in the comment.

does your team accept PRs?  I can submit a fix if you'd like

**Comment by chroto** [comment]
disregard. i saw my issue.  I didn't notice the `AWS:Include` statement in `DefinitionBody`

https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/template.yaml#L15-L20
