### ISSUE TITLE
Generated IAM role name does not match generated_resources.rst

### ISSUE THREAD

**Issue by folksgl** [awslabs/serverless-application-model#1349]
**Description:**

The IAM role name generated by the AWS::Serverless::Function resource does not match what is described in https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#aws-serverless-function
It appears in my experience that the stack name is prepended to the generated role and that a random suffix is appended to the end of the role name.

**Steps to reproduce the issue:**
1. Define a template per https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#format
2. Run
3. Inspect generated IAM Role names.

I have been using the "List of IAM Policy Document" for the Policies section of the declared function resources.

**Observed result:**
IAM Role Name: my-stack-myFunctionName-RandomSuffix
**Expected result:**
IAM Role Name: myFunctionNameRole

**Comment by chrisoverzero** [comment]
The name of the role is not the same thing as its logical ID. The purpose of the logical ID is for further referencing via `Ref` or `Fn::GetAtt` within the template. This is what SAM generates and what is documented for the generated resources. 

For example, do you see how `ServerlessRestApi` is mentioned in the document? If this were the name of the RestAPI, only one implicit API could be created per account. But that ID _can_ be `Ref`ed elsewhere in the document to attach a base path mapping, regional WAF, or any other resource that needs to reference the RestAPI.

**Comment by folksgl** [comment]
Referencing via the expected name within the template seems to work just fine, which will solve any issue I was having with unpredictable resource names. Thank you for the helpful response.
