### ISSUE TITLE
How to set CORS for requests other than OPTIONS?

### ISSUE THREAD

**Issue by dimitrovs** [awslabs/serverless-application-model#135]
I followed the api_swagger_cors example and it adds the CORS headers to the OPTIONS response, but in order for CORS to work the headers need to be added for all verbs. I tried adding them like this:
```
paths:
              /{resourceType}:
                get:
                  produces:
                  - application/json
                  parameters:
                  - name: resourceType
                    in: path
                    required: true
                    type: string
                  responses:
                    '200':
                      description: 200 response
                      schema:
                        $ref: "#/definitions/Response"
                      headers:
                        Access-Control-Allow-Origin:
                          type: string
                        Access-Control-Allow-Methods:
                          type: string
                        Access-Control-Allow-Headers:
                          type: string
                  x-amazon-apigateway-integration:
                    responses:
                      default:
                        statusCode: 200
                        responseParameters:
                          method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
                          method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                          method.response.header.Access-Control-Allow-Origin: "'*'"
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAllFunction.Arn}/invocations
                    passthroughBehavior: when_no_match
                    httpMethod: POST
                    type: aws_proxy
```

but it doesn't work, the header values are ignored when integrating with Lambda. How are we to set the CORS headers?

**Comment by dimitrovs** [comment]
I figured I just need to add the headers to the response in my Lambda function like so:
```
const createResponse = (statusCode, body) => {
	return {
		"statusCode": statusCode,
		"headers": {
			"Access-Control-Allow-Headers": "Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token",
			"Access-Control-Allow-Methods": "DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT",
			"Access-Control-Allow-Origin": "*"
		},
		"body": body || ""
	};
};
```
It works now.

**Comment by syang** [comment]
@dimitrovs in this way, I think  you will invoke more lambda functions than needed. Right?

Instead, if you define the OPTIONS response at the API GW layer (by using mock), you will save these lambda execution.

my 2c.

**Comment by dimitrovs** [comment]
@syang my question was about adding CORS to the other verbs, I still have OPTIONS at the API GW layer but after options the client calls GET/POST and still checks the headers.

**Comment by syang** [comment]
@dimitrovs, after preflight (which OPTIONS is for), why other verbs need this header? 

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Maybe I miss something here.

**Comment by dimitrovs** [comment]
@syang the page you linked refers to "simple requests" (GET, HEAD, POST) which don't use preflight at all if certain conditions are met. In this case if your API does not provide the CORS headers when a GET/POST request is made it will be rejected by the browser and OPTIONS will not be invoked at all. Other methods used in RESTful APIs (PUT, DELETE) do invoke the OPTIONS preflight. You can also force OPTIONS to be invoked for GET/POST by adding disallowed request headers, but my experience with the AWS example was that even if I force OPTIONS request and it gets the correct headers from the mock, if the subsequent GET request does not have the headers then then browser will still reject it.

**Comment by syang** [comment]
@dimitrovs understood your point now. Yeah, for non-simple requests that won't trigger OPTIONS preflights, your solution is needed. Agreed on this point.

Now I am wondering if the CORS header could be added in SAM template rather than the lambda function, which sounds a better solution (at the end of the day, CORS is not the functional logic, it's purely an API-Gateway layer configuration) to me if it's possible.

**Comment by mohithg** [comment]
I wish to handle CORS in template.yaml file instead of handling it in code. It makes my lambda more cleaner. Any updates on how to handle this?

**Comment by swishstar** [comment]
@mohithg : Here is [an example template](https://github.com/awslabs/aws-serverless-express/blob/master/example/cloudformation.yaml) (if you haven't found it already). Plus, [this thread](https://github.com/awslabs/aws-serverless-express/issues/58#issuecomment-322263402) also has a "fix" for getting the OPTIONS pre-flight call to work and not through a 500 error.

**Comment by rabowskyb** [comment]
Just in case it might be of some use, here's an example of SAM with CORS enabled:  https://github.com/aws-samples/startup-kit-serverless-workload.
