### ISSUE TITLE
[Feature Request] Tags for AWS::Serverless::SimpleTable

### ISSUE THREAD

**Issue by nathanjd** [awslabs/serverless-application-model#136]
DynamoDB tables currently support tags and while `AWS::Serverless::SimpleTable` is meant to be a subset of functionality, I think they should make the cut. It would help when creating resource groups.

Result of running cloudformation deploy:

> Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 2. Resource with id [DeviceTraceApi] is invalid. property Tags not defined for resource of type AWS::Serverless::Api Resource with id [TracesTable] is invalid. property Tags not defined for resource of type AWS::Serverless::SimpleTable

Thank you.

**Comment by nathanjd** [comment]
Sorry, but I cannot find out how to add the required "Feature Request" label.

**Comment by vikrambhatt** [comment]
API Gateway resources do not support tagging at this moment: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html

SAM will add this once the feature is supported by the resources.

**Comment by nathanjd** [comment]
Ah whoops, thanks for pointing that out. I'll modify the request for just `AWS::Serverless::SimpleTable`.

**Comment by sanathkr** [comment]
Yes, tags should be supported for DDB

**Comment by sanathkr** [comment]
I just realized DDB also doesn't support tags - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html

SAM can't do much here until they release support

**Comment by sanathkr** [comment]
Closing this in favor of parent tracking issue #252
