### ISSUE TITLE
Fix Template Specification API Auth Object formatting

### ISSUE THREAD

**Issue by tom139** [awslabs/serverless-application-model#1378]
**Description:**

In the SAM Template Specification (`versions/2016-10-31.md`) the paragraph about the API Auth Object is badly formatted.

**Steps to reproduce the issue:**

1. Go to the [API Auth Object](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api-auth-object) paragraph of `versions/2016-10-31.md` (AKA _SAM Template Specification_)

**Observed result:**

The YAML for the Authorizers section is badly formatted (because the ```` ```yaml ```` block is opened twice).

**Expected result:**

Better formatting.

**Comment by tom139** [comment]
I will submit a PR in a few minutes, addressing this issue.

**Comment by keetonian** [comment]
Released!
