### ISSUE TITLE
Deploy lambda functions from AWS Serverless Repo via SAM

### ISSUE THREAD

**Issue by alexhall** [awslabs/serverless-application-model#1380]
I would like to be able to deploy a third-party lambda function published to AWS Serverless Repo as part of a SAM template, e.g. to configure my application to use the [Datadog Log Forwarder](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:464622532012:applications~Datadog-Log-Forwarder).

I've found documentation on publishing applications to Serverless Repo using SAM (https://docs.aws.amazon.com/serverlessrepo/latest/devguide/using-aws-sam.html) but consuming Serverless Repo applications with SAM doesn't appear to be supported. Is it possible to add support for this use-case?

**Comment by timoschilling** [comment]
Take a look on https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md#awsserverlessapplication

**Comment by alexhall** [comment]
> Take a look on [AWS::Serverless::Application](https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md#awsserverlessapplication)

Ahh, thank you. I don't know how I missed that the first time around.

Is there a way of getting at the ARN of the lambda function associated with the `AWS::Serverless::Application` resource, so that we can reference it when creating additional resources in the SAM template?

**Comment by timoschilling** [comment]
The underlying Stack didn't defines a output, so I think it's not possible. But you can simply copy the function code and put it into your own stack or nested stack.
You can find the source code [here](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/log-sam-template.yaml).

**Comment by keetonian** [comment]
Thank you @timoschilling for answering this! Yes, you can use an `AWS::Serverless::Application` to consume applications directly from the Serverless Application Repository.
