### ISSUE TITLE
Lambda invocation definition, does SAM respect ApiGateway section or Lambda section?

### ISSUE THREAD

**Issue by syang** [awslabs/serverless-application-model#140]
In the following template.yaml, the section of _**ApiGateway --> path: /questions/ --> GET --> x-amazon-apigateway-integration**_ defined that GetQuestionsFunction should be called to serve questions/ GET; at the same time, the section of **_GetQuestionsFunction --> Events_** also defined that it should be invoked whenever the URI of questions/ GET is requested.

Two questions here: 
- Are they repetitive? Can we delete the **_GetQuestionsFunction --> Events_**  section and use the ApiGateway section as the source of truth?
- If the above two sections have conflicts, for example, if _**ApiGateway --> path: /questions/ --> GET --> x-amazon-apigateway-integration**_ defines _AnotherLambdaFunction_ as the triggered handler, while **_GetQuestionsFunction --> Events_** stays the same, which definition Api-Gateway would respect?

```
Resources:
  ApiGateway:
    Type: 'AWS::Serverless::Api'
        ....
        paths:
          '/questions':
            get:
              produces:
              - 'application/json'
              responses:
                '200':
                  description: 'successful'
                  schema:
                    type: number
              x-amazon-apigateway-request-validator: basic # enable validation for this resource
              x-amazon-apigateway-integration: # this section connect the Lambda function with the API Gateway
                httpMethod: POST
                type: 'aws_proxy'
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetQuestionsFunction.Arn}/invocations'
                passthroughBehavior: when_no_match

  GetQuestionsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'index.scanQuestionList'
      Runtime: 'nodejs4.3'
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        Http:
          Type: Api
          Properties:
            Path: /questions
            Method: get
            RestApiId: !Ref ApiGateway
```

**Comment by khnicholas** [comment]
> Are they repetitive? Can we delete the GetQuestionsFunction --> Events section and use the ApiGateway section as the source of truth?

it is not repetitive (at least with the way that SAM currently implement). 
- So the **ApiGateway (Type: 'AWS::Serverless::Api)** is purely to create the API gateway. it doesnt create the function policy on the lambda.
- Whereas **GetQuestionsFunction --> Events section** will generate the function policy to allow the ApiGateway to invoke it.

_p.s: I do agree that there should only be one source of truth._

**Comment by sanathkr** [comment]
@khnicholas is correct. That's how it works. Agreed the syntax looks slightly confusing, but we made this intentional so you can lift and shift any API Gateway valid Swagger to SAM without modifications.
