### ISSUE TITLE
Issue with sam local invoke when EventInvokeConfig

### ISSUE THREAD

**Issue by cbm-saziri** [awslabs/serverless-application-model#1404]
Hello,

I can't invoke my function when I have EventInvokeConfig property defined in my sam template.
It should be supported accordingly this doc : https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventinvokeconfiguration.html
The template is correctly compile and deploy to AWS though.

Error : 'property EventInvokeConfig not defined for resource of type AWS::Serverless::Function
Sam version : 0.40.0

Thank you

**Comment by praneetap** [comment]
This should be available with the next SAM CLI release.
