### ISSUE TITLE
v1.21.0 Release Tracker

### ISSUE THREAD

**Issue by keetonian** [awslabs/serverless-application-model#1421]
### Changelog

1. #1361 fix: add support for string/parameter based Enabled for DeploymentPreference
1. #1365 fix: throw error for apikey false in api event when not defined in api
1. #1359 docs: code documentation of API Auth Key format 
1. #1363 chore: upgrade to nodejs12.x for all examples and tests 
1. #1367 docs: remove comment stating FIFO SQS Queues aren't supported 
1. #1392 docs: update black instructions in dev guide 
1. #1388 docs: update README.md to point to aws sam spec 
1. #1179 feat: usage plans support for Api Auth 
1. #1377 feat(policy-templates): add Textract policies 
1. #1379 docs: fix Template Specication API Auth Object section 
1. #1376 feat: introduce AutoPublishCodeSha256 to allow overriding the lambda version SHA
1. #1405 fix: update policy used for xray tracing 
1. #1420 docs: add README pointing to example apps 
1. #1419 chore: update black version 
1. #1413 docs: add EventBusName for CloudWatchEvent and EventBridgeRule
1. #1396 fix: fix issue when referencing RestApiId by Ref
1. #1408 feat(custom-domains): adds support for HostedZoneName in Domain section of the API
1. #1395 fix: bug fixes in api resource policies

**Comment by keetonian** [comment]
#1452 reverts #1405, since some customers were broken by switching the name of the managed policy (even though the permissions did not change). We will investigate how we can make this change again in the future.

**Comment by openwebsolns** [comment]
Can't this be fixed by adding *both* the legacy policy and the new one in standard partitions, and only the new one outside of it? Seems like the original commit was *almost* there.

This is a substantial parity blocker otherwise.
