### ISSUE TITLE
Usage Plans: support Ref

### ISSUE THREAD

**Issue by keetonian** [awslabs/serverless-application-model#1432]
**Description:**

In #1179, support was added for Usage Plans. However, it is not possible to reference these plans (and associated resources) without knowing their exact logical ids.

**Steps to reproduce the issue:**
1. Create an api using usage plans
2. Try to reference usage plan using `ApiLogicalId.UsagePlan`

**Observed result:**
Error

**Expected result:**
Should work (and reference usage plan/other resources)

**Comment by ShreyaGangishetty** [comment]
This is released in [v1.22.0](https://github.com/awslabs/serverless-application-model/releases/tag/v1.22.0)
