### ISSUE TITLE
Support CloudWatch Log Event Trigger

### ISSUE THREAD

**Issue by oharaandrew314** [awslabs/serverless-application-model#144]
The AWS Lambda console supports CloudWatch Log triggers.  I think it would be very useful to include in SAM.  I need this so that I can automatically stream my logs to SumoLogic without having to manually configure each lambda.

**Comment by sanathkr** [comment]
Yeah, it should be possible to support this.

**Comment by rarsan** [comment]
+1 
Any reason why this is not supported yet?

**Comment by homingli** [comment]
+1 ... workaround is fine, but definitely prefer SAM to directly support (simplify) Cloudwatch Logs as event source! Thanks!

**Comment by eamonnfaherty** [comment]
The docs hint that this has been built and released.  Has it?

**Comment by brettstack** [comment]
Yes this is now available
