### ISSUE TITLE
EventBridgeRule fails to deploy when using content based filtering

### ISSUE THREAD

**Issue by ljacobsson** [awslabs/serverless-application-model#1455]
**Description:**
EventBridgeRule event source can't handle `numeric` or `exists` matching as described [here](https://docs.aws.amazon.com/eventbridge/latest/userguide/content-filtering-with-event-patterns.html)

**Steps to reproduce the issue:**
Create a EventBridgeRule event mapping like
```
"Pattern": {
  "source": [
    "test-source"
  ],
  "detail": {
    "name": [
      {
        "exists": true
      }
    ],
    "age": [
      {
        "numeric": [
          ">",
          25
        ]
      }
    ]
  }
```
**Observed result:**
Deploy fails with the following error from CloudFormation:
```
The following resource(s) failed to create: [TestFunctionEventBridge].          
Resource creation cancelled                                                
Event pattern is not valid. Reason: exists match pattern must be either    
true or false.  at [Source: (String)"{"source":["test-source"],"detail":{" 
name":[{"exists":"true"}],"age":[{"numeric":[">","25"]}]}}"; line: 1,      
column: 56] (Service: AmazonCloudWatchEvents; Status Code: 400; Error      
Code: InvalidEventPatternException; 
```
It looks like the issue is that both `true` and `25` got converted to strings.

**Comment by nikp** [comment]
This bug is actually inside the CloudFormation service, not Serverless Application Model itself.

I have submitted a fix internally, and will update once the fix is deployed globally

**Comment by ljacobsson** [comment]
@nikp 

Any idea when this fix will get deployed? Heard from the AWS support that it should've been rolled out already, but doesn't seem to be the case.

We're getting quite deep into writing over-complicated event patterns as workarounds

**Comment by nikp** [comment]
@ljacobsson unfortunately the CloudFormation deployment had to be rolled back due to an unrelated bug. The new global deployment is starting next Tuesday.

**Comment by robertomoreno** [comment]
Any update on this?

**Comment by OneMuppet** [comment]
We are still getting this error, any updates? 🙏

**Comment by dobeerman7** [comment]
The problem still persists.

**Comment by codesmithtech** [comment]
I am also experiencing this issue when trying to deploy a stack using the latest version of the AWS CLI

**Comment by ErkoKnoll** [comment]
@nikp any idea when the fix will get deployed? It still seems to be failing, and there does not seem to be a good workaround for that.

**Comment by ljacobsson** [comment]
Check [this](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251#issuecomment-670824840) out!

I can confirm that this indirectly fixed this bug :partying_face: 

Made me very happy :-)
