### ISSUE TITLE
Documentation for AWS::Serverless::Api Return Values is missing

### ISSUE THREAD

**Issue by crbunney** [awslabs/serverless-application-model#1457]
I can't find any documentation for what attributes I can access using Fn::GetAtt with a [AWS::Serverless::Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) (or I've not been using the right search terms)

Most documentation pages have a "Return Values" section, but the documentation for Serveless::Api doesn't have one.

I've tried out Fn::Ref and found it returns the RestApiId from the ApiGateway::RestApi resource, but don't know what else is available.

Can the documentation be updated to include that section with details of what you can access using GetAtt (or be clear if GetAtt isn't supported)?

**Comment by ShreyaGangishetty** [comment]
@crbunney Thanks for bringing this! We will fix it.

**Comment by keetonian** [comment]
Fixed!
