### ISSUE TITLE
Contribute to SAM

### ISSUE THREAD

**Issue by dksheffield** [awslabs/serverless-application-model#146]
Might be a stupid question, but any way to see the code and help contribute to the actual SAM project that does the magic instead of just contributing to this repo?

Thanks!

**Comment by sanathkr** [comment]
Not a stupid question at all! The magic is not open sourced yet. We are working on it. Is there a specific feature you were looking to contribute?

**Comment by sanathkr** [comment]
See #46

**Comment by dksheffield** [comment]
My pain points are securing the API using custom authorizors. I have to use inline swagger right now and would love to be able to keep my swagger file separate so it does not junk up my serverless-template.yml but also use cloud formation references throughout the separate swagger file.

Long term I think it would be great if when I define the Function Event that maps to an API I could reference an authorizer in the event.

**Comment by sanathkr** [comment]
Agreed. There is already a feature request #49. Needs more work of course, but the thought is already floating in the air.

**Comment by dksheffield** [comment]
Sounds good. Thanks!
