### ISSUE TITLE
Serverless Transform with YAML removes leading 0 in account number field.

### ISSUE THREAD

**Issue by brjonath** [awslabs/serverless-application-model#1469]
Description:
--------------
When submitting a template to 'AWS::Serverless-2016-10-31' Transform where template has a resource's property corresponding to account number with a leading zero '0', the transfrom just remove this zero '0' and processed template returened by this transform ends up having a wrong account number.

Observations:
----------------
- Issue happens when template is specified using YAML format and account number is specified without using any quotes.
- When specifying within quotes, correct account number is returned but just sometimes - not clear on this why.
- Workaround is to use JSON to specify your template.

Replication:
-------------
- Use below Template to create a stack and comparing Original and Processed templates will show the different values for `TestBucket -> Properties -> ReplicationConfiguration -> Rules -> Description -> Account`
```
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  TestRawBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt 
          - TestReplicationRoleSecure
          - Arn
        Rules:
          - Id: replication-to-S3raw-test
            Status: Enabled
            Prefix: ''
            Destination:
              Bucket: 'arn:aws:s3:::bucket-name'
              Account: 098693111088
              AccessControlTranslation:
                Owner: Destination
  TestReplicationRoleSecure:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref ReplicationRolePolicy
  ReplicationRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:Get*'
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - 'arn:aws:s3:::bucket-name'
              - 'arn:aws:s3:::bucket-name/*'
          - Action:
              - 's3:ReplicateObject'
              - 's3:ReplicateDelete'
              - 's3:ReplicateTags'
              - 's3:GetObjectVersionTagging'
              - 's3:ObjectOwnerOverrideToBucketOwner'
            Effect: Allow
            Resource: 'arn:aws:s3:::bucket-name-dest/*'
```

**Comment by timoschilling** [comment]
You defined the Account as an Number, but it must be a String.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-replicationconfiguration-rules-destination.html

**Comment by dkropman-Slalom** [comment]
I tested this with a similar account number starting with a leading zero. If I run it through SAM, the account number does not load correctly. I can double quote, single quote or no quote the account number and I get the same error. If I remove the Transform and upload template through cloudformation (double quoted), it works.

**Comment by keetonian** [comment]
@brjonath this is a known issue in CloudFormation. See https://github.com/awslabs/serverless-application-model/issues/200#issuecomment-570701231 for more information regarding this bug and possible workarounds. Closing in favor of #200.
