### ISSUE TITLE
Why is this not part of the official AWS documentation?

### ISSUE THREAD

**Issue by ffxsam** [awslabs/serverless-application-model#147]
I'm relieved to have found this repo, but also frustrated that I spent hours going through AWS CloudFormation documentation wondering why I couldn't find any details on `AWS::Serverless::Function`. Just curious why this documentation is separate from the official AWS docs.

**Comment by yyolk** [comment]
`AWS::Severless::Function` is a AWS CloudFormation Transform

You can find out more about it with examples here: https://github.com/awslabs/serverless-application-model

**Comment by yyolk** [comment]
You can learn more about `Transform` here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html

**Comment by ffxsam** [comment]
I understand that much. I'm just wondering why all the documentation for it is here in this repository and not in the official AWS documentation.

**Comment by vikrambhatt** [comment]
It is linked from AWS official documentation: https://aws.amazon.com/about-aws/whats-new/2016/11/introducing-the-aws-serverless-application-model/
and
http://docs.aws.amazon.com/lambda/latest/dg/deploying-lambda-apps.html 

But SAM is an open source effort and thus the description and details on how to contribute are here on github.

**Comment by ffxsam** [comment]
I see. Thanks for clarifying!
