### ISSUE TITLE
Sharing local resources among lambda functions

### ISSUE THREAD

**Issue by GeoffreyZhangfda** [awslabs/serverless-application-model#1482]
Hello,

Would it be possible to share local resources among lambda functions? Searched online and seems that Lambda layers may be used to share resources, which requires to commit resource files to AWS. We do have some constraints at this stage not to send files outside the government network. So, would like to see if there is a solution to share files on local hard drive among lambda functions.

Thanks,

Geoffrey

**Comment by ShreyaGangishetty** [comment]
@GeoffreyZhangfda Post this question in the AWS support forum
