### ISSUE TITLE
Attach functions to externally defined API Gateway?

### ISSUE THREAD

**Issue by WhileLoop** [awslabs/serverless-application-model#149]
I would like to split my API across multiple SAM templates but have the functions attached to the same API Gateway. Currently when using the "RestApiId" property I get the following message: "RestApiId property of Api event must reference a valid resource in the same template."

**Comment by sanathkr** [comment]
How are you trying to do it? Using `ImportValue`? Can you post an example snippet?

**Comment by WhileLoop** [comment]
At first I tried putting the ID of the gateway directly. This failed with the above error.

`
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SamTest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.Handle
      Runtime: python2.7
      CodeUri: package.zip
      Timeout: 10
      MemorySize: 1024
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            RestApiId: abcd123456
            Path: /TimeResource
            Method: POST
`

Then I tried using import value. This created the Lambda without attaching it to the gateway.

`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SamTest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.Handle
      Runtime: python2.7
      CodeUri: package.zip
      Timeout: 10
      MemorySize: 1024
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            RestApiId: !ImportValue MyRestApi
            Path: /TimeResource
            Method: POST
`

**Comment by edwardgale** [comment]
WhileLoop - did you find a solution to this?  I'm having the same issue whereby the API Gateway is configured externally not using a SAM template however it seems that SAM requires the API Gateway to be configured in the same template file.

**Comment by WhileLoop** [comment]
@edwardgale No, I did not.

**Comment by sanathkr** [comment]
Unfortunately CloudFormation doesn't modify resources created outside of your stack. If you have two stacks, one with API Gateway and other with Lambda functions, then you can use Fn::ImportValue to pass the Lambda ARN to APIGW stack to add an integration there. You can't use SAM there unfortunately because SAM operates entirely within the context of one template.

I am closing this issue because unfortunately we can't do anything about it. Feel free to comment or re-open if you have more use cases for something similar.

**Comment by allinwonder** [comment]
@sanathkr I am working on an API that associates with at least 4 functions. Each of these functions is using safe deployment with different pre/post hook functions. This means totally I have 12 functions in one template and plus others resources. These make the template grow to more than 1000 lines 
 which is really ugly and very hard to digest. I want to be able to split the functions and their pre/post Hook functions into its own template, and then use ImportValue or Parameters to inject the function Arn in the APIGW template. Is this too hard to implement in SAM?
