### ISSUE TITLE
Support AWS::ApiGatewayV2::Api in template.yml

### ISSUE THREAD

**Issue by brandonryan** [awslabs/serverless-application-model#1500]
### Describe your idea/feature/enhancement
Right now only apigateway version 1 is supported. I would like to specify my resources using the http api part of apigateway v2.

Specifically I want to be able to use the openapi [cors](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-cors-configuration.html) extension to decouple the api from lambda a bit more.

### Proposal
Support `AWS::ApiGatewayV2::Api` resources in template.yml

**Comment by jfuss** [comment]
See https://github.com/awslabs/serverless-application-model/issues/1486

Closing as this is already in flight and staged
