### ISSUE TITLE
Simplify API Gateway PROXY+ and ANY support

### ISSUE THREAD

**Issue by a-h** [awslabs/serverless-application-model#1502]
### Describe your idea/feature/enhancement

I was working with a colleague to build an API. We wanted to pass any HTTP request on an API Gateway to a Lambda function using the {PROXY+} and ANY features of API Gateway.

I've done this before, but only using other frameworks for Serverless applications. When I came back, my colleague had read the blog post at https://aws.amazon.com/blogs/developer/handling-arbitrary-http-requests-in-amazon-api-gateway/ and added the following YAML to the project, as per the article:

```yaml
Api:
  Type: "AWS::Serverless::Api"
  Properties:
    StageName: Prod
    BinaryMediaTypes:
      - "~1"
    DefinitionBody:
      openapi: "3.0"
      info:
        title: !Ref "AWS::StackName"
        version: "1.0"
      paths:
        /:
          x-amazon-apigateway-any-method:
            responses:
              {}
            x-amazon-apigateway-integration:
              httpMethod: POST
              type: aws_proxy
              uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations"
        /{proxy+}:
          x-amazon-apigateway-any-method:
            responses:
              {}
            x-amazon-apigateway-integration:
              httpMethod: POST
              type: aws_proxy
              uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations"
```

### Proposal

That seems like too much hard-to-understand YAML for a common use case to me, so my feature request is that...

The `AWS::Serverless::Api` and `AWS::Serverless::Function` types should support `PROXY+` for URLs and `ANY` for methods if it doesn't without needing the extra YAML listed above.

**Comment by ShreyaGangishetty** [comment]
SAM supports adding API events which doesn't involve adding extra YAML in the `DefinitionBody.`

Here is an example of using `/{proxy+}` and `ANY` in API event: https://github.com/awslabs/serverless-application-model/blob/c00b8a31d2d4dcad43e16409caa9d4d142966e43/examples/2016-10-31/api_swagger_cors/template.yaml
Docs: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html.
