### ISSUE TITLE
SAM-Templates >50KB not possible?

### ISSUE THREAD

**Issue by Dunedan** [awslabs/serverless-application-model#151]
So we finally hit the problem, that our SAM CloudFormation templates are larger than 50KB.
As 50KB is the limit for CloudFormation if you specify a local template, we needed to look for other solutions than using `aws cloudformation deploy --template-file ...`.

We looked into:
1. Using a template URL for `aws cloudformation deploy` - not possible, because `deploy` has no such option (https://github.com/aws/aws-cli/issues/2461)
2. Using nested stacks - not possible, because transformations in child templates aren't possible (https://github.com/awslabs/serverless-application-model/issues/90)

Are there any other options? Using `create-change-set` and `execute-change-set` instead of `deploy` comes to mind, but that sounds like more or less giving up all the benefits `deploy` offers.

**Comment by dejonghe** [comment]
Man, that's a bummer that deploy doesn't have a template-url option to pull from S3. I've never used deploy but my process goes Upload to S3 > create change set > execute change set.

**Comment by sanathkr** [comment]
Nested stack transformation bug is tracked in #90. I am using this as a feature request for the AWS CLI feature where `deploy` supports S3 template URL

**Comment by pwrmiller** [comment]
I ran into this today while using SAM to deploy a complicated step function using CloudFormation. It seems to me that since SAM already requires a template bucket for its S3 functions, you could easily default to use the same bucket for aws cloudformation deploy. 

Otherwise, we're hitting the following error: 
```
"Transform: AWS::Serverless-2016-10-31", "' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200"]
```

**Comment by sanathkr** [comment]
Closing this issue in favor of https://github.com/aws/aws-cli/pull/2778 which is tracking the `aws cloudformation deploy` feature to support larger templates

**Comment by ramkama** [comment]
@sanathkr  I'm using SAM CLI, version 0.5.0. I'm still seeing the  issue where unable to deploy SAM templates which are >50KB. What's the fix for this issue?
