### ISSUE TITLE
mulitple API gateways resources in CloudFormation 

### ISSUE THREAD

**Issue by mkamel93** [awslabs/serverless-application-model#1512]
**Description:**

When trying to launch more than 1 API gateway with R53 records, only the R53 record of the first API gateway resource will be transformed and the other will be ignored. Nested stack resolves the issue by having 1 API with R53 records per template.

**Steps to reproduce the issue:**
1. create a serverless template with 2 API gateways each has one R53 record
2. when deploying it, the transformation shows one R53 record only of the first API
3. using nested stacks, each stack has one API gateway transformed correctly with the R53 record created for it

**Observed result:**
when deploying it, the transformation shows one R53 record only of the first API
**Expected result:**
2 R53 records should be exist in the template

**Comment by keetonian** [comment]
Closing in favor of #1539, thank you for bringing this up!
