### ISSUE TITLE
Api DefinitionBody Swagger

### ISSUE THREAD

**Issue by chestongo** [awslabs/serverless-application-model#1525]
I have 2 SAM resources of type: _AWS::Serverless::Application_.
The first _AWS::Serverless::Application_ is for my serverless API.
The second _AWS::Serverless::Application_ is for my serverless functions.

Because my serverless function events API uses the, property: RestApiId. I have to define my
API first, and export the value.

However, my serverless api, definition body use a seperate swagger file. In this swagger file, i want
to import my functions ARN dynamically. How can I do this? I guess it is creating a loop now.

I tried to export my functions ARN, and import in using my inline swagger, but it didn't work.

**Comment by ShreyaGangishetty** [comment]
There is an issue #866 for using existing functions. Closing this in favor of #866
