### ISSUE TITLE
Adding support for dynamic reference 'ssm-secure'

### ISSUE THREAD

**Issue by muellerc** [awslabs/serverless-application-model#1528]
As described at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html , Amazon CloudFormation supports the following 3 dynamic references:
- ssm
- ssm-secure
- secretsmanager

Using ssm works as expected in AWS SAM (e.g. by using {{resolve:ssm:MyKey:1}}).

But when I change to ssm-secure (using a different key where the value is a SecureString with the default KMS key) it fails.

I didn't test the dynamic reference secretsmanager.

**Description:**

When I use the ssm-secure (e.g. {{resolve:ssm-secure:MyApiKey:1}}), I'm getting the following exception:

Error: Failed to create changeset for the stack: test, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: SSM Secure reference is not supported in: [AWS::Lambda::Function/Properties/Environment/Variables/API_KEY]

The SAM template I'm using with a simple hello-world Lambda:

  QueryUsageDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: query_usage_data/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          API_KEY: '{{resolve:ssm-secure:MyApiKey:1}}'
      Events:
        QueryUsageDataEveryDay:
          Type: Schedule
          Properties:
            Input: '{"Operation": "query_usage_data"}'
            Schedule: cron(45 2 * * ? *)  # every day at 2.45AM

**Comment by santiagocardenas** [comment]
This isn't supported by CloudFormation. Support for `ssm-secure` is limited to the resources listed here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#template-parameters-dynamic-patterns-resources

**Comment by JamesSoubry-hero** [comment]
Hi @ShreyaGangishetty this isnt supported for ssm-secure but ssm and secretsmanager are supported everywhere in cloudformation but does not work with SAM templates. Please can you reopen this as a request. Thanks
