### ISSUE TITLE
Tags for AWS Glue Job not working

### ISSUE THREAD

**Issue by sahil-gt** [awslabs/serverless-application-model#1554]
**Description:**

When defining tags for AWS Glue Jobs, they are not rendered properly in the rendered CloudFormation Template and hence do not get added to the AWS Glue Job.

Whereas, adding tags for AWS Lambda attaches the tags to the lambda. 

**Steps to reproduce the issue:**
1. Add Tags to AWS SAM Template for Glue Job.
2. Run AWS SAM to deploy the job.
3. Check Glue Job for tags.

Sample AWS SAM Template - 
```
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      GlueVersion: '1.0'
      MaxCapacity: 5
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: s3://test/hello.py
      DefaultArguments: 
        '--extra-jars': 's3://test/jar-with-dependencies.jar'
        '--TempDir': 's3://test/temp'
      Name: my_test_glue
      Description: Glue job created by AWS SAM
      Role: SomeRandomRole
      Tags:
        my_tag_key: my_tag_value
        my_tag_key2: my_tag_value2
```

**Observed result:**
Both tags do not show when checking the glue job on the browser or via CLI.
**Expected result:**
Tags should be added to glue job.

**Comment by keetonian** [comment]
Hi @sahil-gt , thank you for reporting this, but we can't fix this inside of SAM since that is not an `AWS::Serverless` resource. Could you either open an issue in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues or open an AWS support ticket through your AWS account?
