### ISSUE TITLE
Does AWS API-Gateway support the swagger documentation server?

### ISSUE THREAD

**Issue by syang** [awslabs/serverless-application-model#156]
I would like to have a documentation and mock-up server of my api, like the swagger document service provides for a server (in contract to serverless) setup environment, please click this http://petstore.swagger.io for what I meant here.

My customer(s) can use the above link to experience my API in an intuitive way. Does AWS API-Gateway provide such functionality?

**Comment by sanathkr** [comment]
I know APIGW gives you client SDKs, but I am not sure if it supports generating Swagger UI page. You can do it yourself using https://swagger.io/swagger-ui/ from your Swagger template

**Comment by s-nt-s** [comment]
> are you able to do this? even i am looking for the same
me to
