### ISSUE TITLE
Api Gateway cloud formation behaviour

### ISSUE THREAD

**Issue by ahmadsn26** [awslabs/serverless-application-model#157]
Hello..

previously i have been working with api_Swagger_cors example and it worked fine but for some reason when i try to make a deployement via ci/cd while making the deployment it create a seperate Api Group for all functions .. Like my Stack name is CardStack and i have like 8 functions written and i am getting like 8 different Api groups with same name but different physical id's.. When i check my cloud formation stack detail it created only 1 group  with 1 physical id but for some reason there are like 8 stacks with same name but different physical id's in APi Gateway 

I am not sure if its a swagger issue ...

P.S : it was working fine and i made no changes as i believe i just logged in and saw like i had 8 Api Groups instead of one and all had different physical id's i tried to delete them All make a new Code Pipeline new CF stacks and still the problem persist.

i believe the api gateway should never have same Name and it should throw an error so that we can trace out whats going wrong and where..

and if i can get some help regarding this it would be very helpful...

**Comment by kskory** [comment]
@ahmadsn26 I guess it would be helpful if you post the cloudformation template here, maybe also Code Pipeline configuration, created resources etc

**Comment by ahmadsn26** [comment]
This was resolved as i had discussion with the support staff and was told that this is the default behavior and is not a bug i'll close this
