### ISSUE TITLE
Inconsistent examples in specification

### ISSUE THREAD

**Issue by rpgreen** [awslabs/serverless-application-model#159]
Always reverts to primary key name of 'id'

Example:
```
  Table:
      Type: AWS::Serverless::SimpleTable
      PrimaryKey:
        Name: Test
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
```

**Comment by vikrambhatt** [comment]
Its not at all obvious from docs, but you need to specify the PrimaryKey inside 'Properties' for the resource. 
Example:
https://github.com/awslabs/serverless-application-model/blob/888c9085c28fac189ff56b1b3d522e57e80bd3f9/examples/2016-10-31/iot_backend/template.yaml#L24

**Comment by rpgreen** [comment]
Ah, thanks. Some examples in the specification include the top-level "Properties" property but some do not
