### ISSUE TITLE
[Feature request]AWS::Serverless::Api - AuthorizerResultTtlInSeconds 

### ISSUE THREAD

**Issue by furuton** [awslabs/serverless-application-model#1593]
## Description

I want to set AuthorizerResultTtlInSeconds using AWS::Serverless::Api to disable Authorizer cache((Default is enabled cache)
But AWS::Serverless::Api doesn't support setting AuthorizerResultTtlInSeconds.

I know that AWS::ApiGateway::Authorizer supports AuthorizerResultTtlInSeconds.
But I want to only use SAM template.
So I request that AWS::Serverless::Api supports setting AuthorizerResultTtlInSeconds.

## Helpful Links to speed up research and evaluation

Authorizer - Amazon API Gateway API Reference
https://docs.aws.amazon.com/apigateway/api-reference/resource/authorizer/#authorizerResultTtlInSeconds

```
authorizerResultTtlInSeconds

The TTL in seconds of cached authorizer results. If it equals 0, authorization caching is disabled. If it is greater than 0, API Gateway will cache authorizer responses. If this field is not set, the default value is 300. The maximum value is 3600, or 1 hour.
```

AWS::Serverless::Api - AWS Serverless Application Model
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html

AWS::ApiGateway::Authorizer - AWS CloudFormation
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html

## Others

I created Github issue in aws-cloudformation-coverage-roadmap.

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/470

But PatMyron recommend to create Github issue in awslabs/serverless-application-model Github repo.

**Comment by timoschilling** [comment]
Thats already possible, the parameter is named `ReauthorizeEvery` in SAM, take a look on https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md#api-auth-object

**Comment by furuton** [comment]
Thank you so much.
I confirmed that I can set AuthorizerResultTtlInSeconds using `ReauthorizeEvery`.
