### ISSUE TITLE
Release Issue with aws-sam-translator 1.23.0 

### ISSUE THREAD

**Issue by DavidWylie** [awslabs/serverless-application-model#1595]
aws-sam-translator 1.23.0   is deployed with its tests package to pypi.
This causes conflicts with other projects and causes downstream issues with people using other test runners.

Could this be fixed in a patch release please.

**Comment by jfuss** [comment]
Looks like there is different behavior between sdist and whls. Tests are excluded from sdist by our current setup but not whls. 

For now, use the sdist if this is impacting you.

**Comment by jfuss** [comment]
This should no longer be the case with 1.24.0.

Closing
