### ISSUE TITLE
LambdaInvokePolicy does not handle lambda:InvokeAsync

### ISSUE THREAD

**Issue by bendog** [awslabs/serverless-application-model#1607]
Currently the LambdaInvokePolicy only allows for InvokeFunction and not InvokeAsync

It would be good if this could be updated to allow for both, or create a new LambdaInvokeAsyncPolicy.

example below

```json
{
    "LambdaInvokePolicy": {
      "Description": "Gives permission to invoke a Lambda Function, Alias or Version",
      "Parameters": {
        "FunctionName": {
          "Description": "Name of the Lambda Function"
        }
      },
      "Definition": {
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "lambda:InvokeFunction",
              "lambda:InvokeAsync"
            ],
            "Resource": {
              "Fn::Sub": [
                "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${functionName}*",
                {
                  "functionName": {
                    "Ref": "FunctionName"
                  }
                }
              ]
            }
          }
        ]
      }
    },
}
```

**Comment by timoschilling** [comment]
Why did you need this?

I think `lambda:InvokeAsync` is only needed for the deprecated [InvokeAsync](https://docs.aws.amazon.com/lambda/latest/dg/API_InvokeAsync.html) API, each SDK uses only the [Invoke](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html) API with `InvocationType=Event` to make async invokations.

**Comment by bendog** [comment]
Thanks @timoschilling, turns out that this was a red herring and i've just worked out my issue is with the VPC and not permissions.
