### ISSUE TITLE
Error with GatewayResponses

### ISSUE THREAD

**Issue by billbeckett** [awslabs/serverless-application-model#1609]
I get an error when including GatewayResponses in my cloud formation yaml:
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [APIGateway] is invalid. GatewayResponses works only with inline Swagger specified in 'DefinitionBody' property.

Below is a sample cloud formation template we are using.

AWSTemplateFormatVersion: 2010-09-09
Description: 'ApiGateways: ConsumerMessageHandlerGateway'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  APIGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      OpenApiVersion: 3.0.1
      StageName: Prod
      GatewayResponses:
        BAD_REQUEST_BODY:
          StatusCode: 400
          ResponseTemplates: 
            "application/json": '{\"error\": {\"code\": \"BadRequest\", \"detail\": [{\"target\": \"body.data\",\"message\":\"$context.error.validationErrorString\",\"code\": \"BadRequest\"}]}}'
      DefinitionUri:
        Bucket: !Sub 
          - 'payoutv3-${EnvironmentName}-deploy'
          - EnvironmentName: !ImportValue 
              'Fn::Sub': '${VariablesStackName}-Environment'
        Key: !Ref SwaggerKey
      TracingEnabled: true
      MethodSettings:
        - DataTraceEnabled: false
          HttpMethod: '*'
          LoggingLevel: ERROR
          MetricsEnabled: true
          ResourcePath: /*
      Variables:
        lambdaauthoriser: !Ref AuthenticationFunctionName
        messagelambdaapi: !Ref APIFunctionName

I previously had the Gateway responses defined separatly:
GatewayResponse:
    Type: AWS::ApiGateway::GatewayResponse
    DependsOn: APIGateway
    Properties:
      ResponseTemplates: 
        application/json: "{\"error\": {\"code\": \"BadRequest\", \"detail\": [{\"target\": \"body.data\",\"message\":\"$context.error.validationErrorString\",\"code\": \"BadRequest\"}]}}"
      ResponseType: BAD_REQUEST_BODY
      RestApiId: !Ref APIGateway
      StatusCode: '400'

However I find that for some reason the API gateway response keep reverting back to its default. That is why I am trying to include it as part of the AWS::Serverless::Api definition.

What am I doing wrong here?

**Comment by timoschilling** [comment]
You can't use
```yaml
DefinitionUri:
  Bucket: !Sub
    - 'payoutv3-${EnvironmentName}-deploy'
    - EnvironmentName: !ImportValue
```

You must embed the swagger definition with `DefinitionBody` and remove `DefinitionUri`
```yaml
DefinitionBody:
  # you swagger definition
```

**Comment by billbeckett** [comment]
It is not possible to embed the swagger definition within DefinitionBody. Is there a way to do this using DefinitionUri? I can define the GatewayResponse outside of the AWS::Serverless::API definition but as I mentioned above, it somehow keeps reverting back to its default?

**Comment by timoschilling** [comment]
There are to workarounds for you problem:
1. Build a prebuild step to embed you swagger file into DefinitionBody
2. Use an Cloudformation Transformation to embed the swagger file into the DefinitionBody

**Comment by billbeckett** [comment]
Thanks @timoschilling !
