### ISSUE TITLE
CORS example variable interpolation

### ISSUE THREAD

**Issue by nwolverson** [awslabs/serverless-application-model#161]
From commit https://github.com/awslabs/serverless-application-model/commit/fa4ee9dc2b85d51690db29088a45588098338854#diff-da0b252a83f80e3519ab16b324ab2bd9L15 for the api-swagger-cors example using the ARN instead of the function Ref. Using this code together with the API as specified in the swagger.yaml: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/swagger.yaml#L23 results in a doubled up `arn:aws:...:function:arn:aws:lambda:...:function` - alternatively removing the `arn:aws:lambda:<<region>>:<<accountId>>:` gives an error on deploying ("Invalid lambda function") - it seems this ARN cannot just be interpolated entirely.

Using the Ref instead seems to result in the correct stage variable

**Comment by yyolk** [comment]
in that example `<<region>>` and `<<accountId>>` need to be manually replaced by you or your build process...

for example you can use `sed` to replace occurrences of `<<region>>`:

```
sed -i 's/<<region>>/us-east-1/g' swagger.yaml
```

**Comment by nwolverson** [comment]
@yyolk don't think you understand the issue, replacing the region and accountId does not address the fact that the ARN is both constructed in the swagger file and also substituted in the stage variable, resulting in something of the form:

`arn:aws:lambda:<<region>>:<<accountId>>:function:arn:aws:lambda:<<region>>:<<accountId>>:function:<<functionName>>`

**Comment by sanathkr** [comment]
You have to construct the ARN in both places. APIGW does validate integration ARN in Swagger file. Example should actually pass Lambda function name via stage varialbe and not the ARN. Fixed it.
