### ISSUE TITLE
Specify api key  with serverless model

### ISSUE THREAD

**Issue by jasondaicoder** [awslabs/serverless-application-model#162]
I am trying to specify the api key/usage plan into the serverless template, however I couldn't find any properties for them. Does the serverless model support api key/usage plan for the api gateway? Or we will have to use normal restapi resource instead of the serverless model?

Cheers

Jason

**Comment by sanathkr** [comment]
This is not supported yet. You should use normal cloudformation resources until this feature is implemented

**Comment by jfuss** [comment]
We created a parent task to track this. Please see #248 for updates.

Closing as duplicate of #248
