### ISSUE TITLE
EFS permission denied

### ISSUE THREAD

**Issue by MatteoInfi** [awslabs/serverless-application-model#1631]
I am unable to use EFS with lambda and I am getting permission denied following this example: https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/

```
func function() (events.APIGatewayProxyResponse, error) {
	if err := os.Mkdir(fmt.Sprintf("/mnt/efs/%v", "123"), os.ModePerm); err != nil {
		return events.APIGatewayProxyResponse{}, err
	}

	return events.APIGatewayProxyResponse{
		StatusCode:        200,
		Body:              "OK",
	}, nil
}

```

I get this error 

```
mkdir /mnt/efs/123: permission denied: PathError null

```

**Comment by MatteoInfi** [comment]
This example is very misleading: https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/

**Comment by jfuss** [comment]
@MatteoInfi Thanks for letting us know. I reached out to the owner of the blog for him to address this. Closing as we don't own that content.

**Comment by itsmano** [comment]
Hi, In EFS access point my path is /opt/test/packs. I lambda function i can't able to give the full path(/mnt/opt/test/packs). I am getting some error says that we need to give the absolute path. any thoughts?

**Comment by js0805** [comment]
> Hi, In EFS access point my path is /opt/test/packs. I lambda function i can't able to give the full path(/mnt/opt/test/packs). I am getting some error says that we need to give the absolute path. any thoughts? cc @MatteoInfi

Even I am trying to find solution to this issue. 
[ERROR] PermissionError: [Errno 13] Permission denied: '/mnt/efs/foo'  << It shows the availability of folder in this location but denies me from performing read/write operations. (Trying it over aws lambda)
I have configured the requirements for permission for owner as 1000:1000 and for POSIX user as 1000:1000:0777.
