### ISSUE TITLE
Duplicate 'Definition Body' appearing after using aws cli commands.

### ISSUE THREAD

**Issue by prafulmehrotra** [awslabs/serverless-application-model#164]
Hi All,
I am using SAM for one of my projects, link here - https://github.com/prafulmehrotra/startup-kit-serverless-workload. I have inline swagger in my yaml template file so as to enable CORS for my API. However, when using the manual deployment steps as specified in the README, the output template file appears to have two 'Definition Body' attributes appear after using the aws package command. Could anyone here look at this and let me know why this could be happening? Thanks!

**Comment by oharaandrew314** [comment]
I had this problem when my AWS CLI was out-of-date.  Try updating it.

**Comment by jfuss** [comment]
@prafulmehrotra Did updating the AWS CLI resolve this issue or is it still occurring?
