### ISSUE TITLE
make API visible on local network

### ISSUE THREAD

**Issue by tobiasfeil** [awslabs/serverless-application-model#1643]
If I invoke `sam local start-api`, I can't call the API from a different host on the same network - only from the host that started the API. Please provide an option that makes this possible.

**Comment by timoschilling** [comment]
Start ist with `--host <your network address>` or `--host 0.0.0.0`

**Comment by tobiasfeil** [comment]
Oh wow that would have been easy to discover. Thanks for the quick reply.
