### ISSUE TITLE
Set stage names and variables for an implicit API

### ISSUE THREAD

**Issue by cjkent** [awslabs/serverless-application-model#165]
An API created implicitly from `Event` declarations always has a stage called `Prod` with no stage variables. This limits how useful an implicit API can be. 

It would be helpful if the stage name (or names) and variables could be specified for an implicit API.

**Comment by sanathkr** [comment]
StageVariables are often used to pass Lambda function name from CFN template to Swagger file, for explicit APIs. Do you have other usecases?

**Comment by sanathkr** [comment]
Will happen in #248

**Comment by brettstack** [comment]
Our next deployment will allow you to leverage the power of Implicit APIs (primarily, the generated Swagger) by defining an Explicit API and modifying to your needs (set StageName and variables). So long as you don't specify a DefinitionBody, it will use the SAM-generated one for you just as the Implicit API does. See an example in this PR:

https://github.com/awslabs/serverless-application-model/pull/546/files#diff-5b78a96550ed34f747b323760e9e0135R15
