### ISSUE TITLE
Q: How to define MethodSettings stage configuration in SAM?

### ISSUE THREAD

**Issue by piterpong** [awslabs/serverless-application-model#167]
Hi @all

I would appreciate some guidance here from anyone who has managed to successfully configure stage `AWS::ApiGateway::Stage/MethodSettings `using `SAM` (such as `MetricsEnabled`, `DataTraceEnabled`).

Much appreciated for your help.

**Comment by sanathkr** [comment]
Right now this is unsupported. Native support for it in SAM is already implemented. QA and code push remaining. Should be out in a couple of weeks.

**Comment by CrazyBS** [comment]
+1

**Comment by volkodava** [comment]
Hi @sanathkr 
Any updates so far?

**Comment by aripalo** [comment]
What's the status on this?

**Comment by bluepeter** [comment]
Ping.

**Comment by sanathkr** [comment]
It will happen in #248
