### ISSUE TITLE
Q: How to specify a usage plan for API Gateway in SAM?

### ISSUE THREAD

**Issue by piterpong** [awslabs/serverless-application-model#169]
Hi @all

I would appreciate some guidance here from anyone who has managed to successfully configure usage plan using SAM (see: `AWS::ApiGateway::UsagePlan`, `AWS::ApiGateway::UsagePlanKey`).

Much appreciated for your help.

**Comment by rajanarkenbout** [comment]
interested!

**Comment by keenavasan** [comment]
I'm interested too

**Comment by manikandanrs** [comment]
+1.

**Comment by keenavasan** [comment]
Well, I have figured this - the following works.

Parameters:
  DeploymentEnvironment:
    Type: String
    Default: stage
    AllowedValues:
      - prod
      - stage
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ../definitions.yaml
      StageName: !Ref DeploymentEnvironment

  TrialPlan1:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
      - ApiId: !Ref 'ApiGatewayApi'
        Stage: !Ref 'DeploymentEnvironment'
      Description: Trial Plan 50 requests per day
      Quota:
        Limit: 50
        Period: DAY
      UsagePlanName: Trial_Plan50

**Comment by jvanbrunschot-coolblue** [comment]
Hi, I also commented the following solution to other question but the workaround is as followed:

Apparently when using `sam deploy` (aws cloudformation deploy) it uses the transform rule (Transform: AWS::Serverless-2016-10-31) set in your template to generate all kind of "extra" resources. One of them is a `aws::ApiGateway::stage` resource. The name of this resource is ServerlessApiStage where ServerlessApi is the name of the AWS::Serverless::Api resource.

**Comment by jfuss** [comment]
We created a parent task for getting Usage Plan support in SAM, #248. Please track the progress there. 

Closing as duplicate of #248
