### ISSUE TITLE
How to parameterize AWS::Serverless::Function policies?

### ISSUE THREAD

**Issue by edjackson-wf** [awslabs/serverless-application-model#172]
I have an `AWS::Serverless::Function` with a policy block like this:

      Policies:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - !FindInMap [RoleMap, !Ref Role, LoggingPolicy]

It appears that SAM is silently ignoring the `FindInMap` rather than transforming the intrinsic function correctly—the transformed template has only the AWSLambdaBasicExecutionRole in the `ManagedPolicyArns` list.

For what it's worth, I'm using a similar `FindInMap` to populate an environment variable, and it works fine.

I assume this is known behavior, but is there a good workaround to allow parameterization of managed policies?

**Comment by sanathkr** [comment]
This is a bug. Fix is in progress.

**Comment by sanathkr** [comment]
This should be fixed - https://github.com/awslabs/serverless-application-model/releases/tag/1.4.0
