### ISSUE TITLE
simplify examples to use --s3-bucket when running package

### ISSUE THREAD

**Issue by kimsaabyepedersen** [awslabs/serverless-application-model#173]
As the how-to describes (https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md) the examples should reflect that the --s3-bucket argument can be used. 

This simplifies the usage.

**Comment by sanathkr** [comment]
But we want to leave it as S3 paths because this examples is focused on true SAM spec which only supports S3 URIs. Feel free to re-open if you disagree.
