### ISSUE TITLE
DefinitionUri doesnt support Intrinsic Functions

### ISSUE THREAD

**Issue by shivaman** [awslabs/serverless-application-model#181]
I have an external Swagger file (not in S3), and trying to do something like

`DefinitionUri: !Ref SwaggerFile`
or !Join or !Sub results in 

```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyAPI] is invalid. 'DefinitionUri' requires Bucket and Key properties to be specified
```

Whereas `DefinitionUri: swagger_development.yml` works fine. 

https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md#using-intrinsic-functions seems to claim this should work. This makes working with a SAM template with different configs for development and testing difficult.

**Comment by cluggas** [comment]
That error is suggesting that the `DefinitionUri` is not matching an expected regex pattern. It need a bucket and key, which are parts of an S3 Uri.

I think this has to be an S3 bucket Uri, which is why I am surprised that `swagger_development.yml` works.

If you want to parametrise `DefinitionUri`, try building it up from parameters using the `!Sub` function...

`DefinitionUri !Sub s3://${ArtifactsBucket}/swagger_development.yml`

**Comment by badfun** [comment]
I am getting the same error message, but without trying intrinsic functions, just calling the api file. I have done a lot of testing and it seems this part of the documentation is wrong. The example shown here does not work: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#example-awsserverlessapi

A similar example is shown in the Lambda developer guide: http://docs.aws.amazon.com/lambda/latest/dg/deploying-lambda-apps.html

`
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Api: 
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionUri: swagger.yml
`

Has anyone been able to get this to work? Or can it only call an S3 bucket? Interestingly, in CodeStar it references a local file as well, and it works fine.

**Comment by badfun** [comment]
Found the answer here: [https://github.com/awslabs/serverless-application-model/pull/86](url)

> If you use the AWS CLI command aws cloudformation package it will do the uploading job for you. But if you are passing a SAM template directly to CloudFormation, DefinitionUri has to be a S3 URI. Technically, the spec accepts only S3 URI for this property.

**Comment by sanathkr** [comment]
That's correct. "aws cloudformation package" command doesn't de-reference intrinsic functions. Its only the CFN service that can do this.
