### ISSUE TITLE
Update documentation and/or error messaging around lack of support for conditions

### ISSUE THREAD

**Issue by mikecbrant** [awslabs/serverless-application-model#202]
It seems as if conditions are not supported in portions of AWS::Serverless::Function (and perhaps other resource types, but I haven't personally experimented).

Searching this repo has shown that this is in fact a current feature request shown here -
 https://github.com/awslabs/serverless-application-model/issues/142

Until such feature is available, it may be useful to update the documentation to include this lack of support.  Currently inclusion of a condition in such function definition leads to a generic "internal transform failure" error message this is not surfaced until one tries to create a change set (not caught in template validation).

Updating the documentation and/or error messaging may be useful in the interim time until such condition support is available to help others avoid the laborious task of trying to troubleshoot these types of issues in their templates.

**Comment by jfuss** [comment]
This will be handled by the Documentation Revamp issue: #251.

Closing
