### ISSUE TITLE
Swagger + account ID in Lambda URI + Multi-Account setup

### ISSUE THREAD

**Issue by aripalo** [awslabs/serverless-application-model#203]
When using external Swagger file, one must specify Lambda URI for `x-amazon-apigateway-integration`.

Logically one would assume that using stage variables in the `AWS::Serverless::Api` resource would solve this, but annoyingly those do not work due to [some limitation in API Gateway](https://github.com/awslabs/serverless-application-model/issues/87#issuecomment-277775124): So one must hardcode those values into `swagger.yml`.

Which then leads to a following problem when using the same SAM configuration for different account:
> Errors found during import: Unable to put integration on 'GET' for resource at path '/foo': Lambda function ARN must be in same account

I know that this is a duplicate for https://github.com/awslabs/serverless-application-model/issues/87, but I am raising this issue open again, because there is a real reasons for using multi-account setup to separate environments (the main one being "limiting blast-radius"): Even AWS promotes it for example [here](https://aws.amazon.com/answers/account-management/aws-multi-account-security-strategy/) and [here](https://aws.amazon.com/blogs/security/guidelines-for-when-to-use-accounts-users-and-groups/).

My team uses two-account strategy (per product): "`PRODUCTION` + others". Having to [hardcode the account ID](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/swagger.yaml#L22-L23) makes implementing SAM into this multi-account strategy pain in the butt.

Now my only choice (probably) is to do some sed replacing at some point before CloudFormation create/update changeset call, but this gets quite dirty and means I have to add even "another transform step" in addition to SAM's `AWS::Serverless-2016-10-31` transform.

If this limitation in API Gateway cannot be removed, then it should be circumvented by SAM to allow interpolating account ID somehow within `sam package` step.

**Comment by sanathkr** [comment]
Does "AWS::Include" help for you? Example: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/template.yaml#L12

SAM implementation does not have permission to modify the Swagger file saved in S3. As long as the data is inlined in the template, SAM can muck with it.

**Comment by jagu-sayan** [comment]
Use predefined cloudformation [`AWS::AccountId`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-accountid) variable ?

**Comment by saratitan** [comment]
If I understood the problem correctly, we solved it by uploading the swagger-file to a bucket and then reference it in the resource. 
E.g.
`aws s3 cp swagger.yaml s3://some-bucket/swagger.yml`
and then add the Swagger path as a parameter or build it in the cloudformation :
`
ApiGateway:
  Type: AWS::Serverless::Api
  Properties:
    ...
    DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://some-bucket/swagger.yml
`

**Comment by jtanios** [comment]
Why was this issue closed? As I understand, we still have to hardcode the account ID. Any solutions that I'm not aware of?

**Comment by jlhood** [comment]
@jtanios Using the `AWS::Include` transform to reference your OpenAPI (swagger) definition as described in https://github.com/awslabs/serverless-application-model/issues/203#issuecomment-388858910 allows you to use [pseudo parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) like `AWS::AccountId` within your OpenAPI definition instead of hardcoding the accountId. We included an example of this in the realworld serverless application project we open sourced near the end of 2019. Here's the relevant section from the best practices wiki (includes links to the code so you can see what it looks like in practice):

https://github.com/awslabs/realworld-serverless-application/wiki/Amazon-API-Gateway#use-awsserverlessapi-in-your-cloudformation-template
