### ISSUE TITLE
Display ApiKey's key in Output

### ISSUE THREAD

**Issue by themummy** [awslabs/serverless-application-model#206]
Is there a way to display the newly created APIKey in the Output section of the stack? The following code displays the API key's resource ID, but I would like to display the actual key.
```yaml
ApiKey:
    Description: API Key
    Value: !Ref TrackSenseAPIKey
```
I know the `!GetAtt` can be used to display an attribute, but I'm not sure the actual key is an attribute of AWS::ApiGateway::ApiKey

**Comment by nstonesplunk** [comment]
This is more of a CloudFormation related issue I believe. I had a similar need, and it seems like attaching the key to a usage policy makes the key ID and the actual key value the same, so I could just output the API resource ID using Ref. Unsure of if this is a bug or a feature. Maybe some more context here https://github.com/serverless/serverless/issues/2539

**Comment by jfuss** [comment]
This is a CloudFormation specific question, which isn't related to SAM.

@themummy What you attached should work as far as I can tell. According to the CloudFormation docs for [APIKey](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html), Ref on the logical id should return the API key ID. If this is not what you are seeing, I would suggest reaching out to CloudFormation. SAM has no control over this.

**Comment by themummy** [comment]
@jfuss `Value: !Ref TrackSenseAPIKey` displays the Key's ID, but I would like to display the actual KEY to be used in the API call. Is that even possible?

**Comment by jfuss** [comment]
@themummy From what I can tell from the CloudFormation Docs, that isn't supported. I would reach out to them (CloudFormation) directly to see if they can't answer your question for certain. SAM doesn't have control over this resource, as it is a CloudFormation Type.

**Comment by jfuss** [comment]
@themummy Please let me know if you need more help with this. It doesn't look like what you want is supported in CloudFormation (from what I can tell), therefore going to close this issue.

**Comment by themummy** [comment]
Thanks @jfuss. Would this be the right repository to ask the question?
https://github.com/awslabs/aws-cloudformation-templates

**Comment by jfuss** [comment]
@themummy That github repo looks to be only templates. You can try but to me seems like the it might not be that helpful to you.

I did find this post on the [AWS Forums](https://forums.aws.amazon.com/thread.jspa?messageID=742506&#742506). Looks like you are not the only one asking for this feature. 

You can submit a technical support case in your AWS account, but is unavailable for Basic Support Plan.

**Comment by Twobraveheads** [comment]
Hi, dudes!
Did you find the way to output an api key value?

**Comment by ShreyaGangishetty** [comment]
@Twobraveheads  as @jfuss said it is a CloudFormation issue. You can open this issue in the [CloudFormation roadmap](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap) to see if they can address this issue

**Comment by aprilmintacpineda** [comment]
https://github.com/awslabs/aws-cloudformation-templates/issues/332

**Comment by nCubed** [comment]
As this seems to be the top result from google, and there still is not a way of outputting the `ApiKey.Value` in the template, figured someone else may find this useful.

The next best thing is to output the cli command to retrieve the key's value. In the `Outputs` section:

```
# Helper References
CLIApiKey:
  Description: CLI command to get the api key value.
  Value: !Sub "aws apigateway get-api-key --api-key ${ApiGatewayKey.APIKeyId} --include-value --query \"value\" --output text"
```
Replace `ApiGatewayKey` with whatever your logical resource name is for the `AWS::ApiGateway::ApiKey` resource.

The resulting output will be (obviously your key id will be different):
```
Key            CLIApiKey
Description    CLI command to get the api key value.
Value          aws apigateway get-api-key --api-key hj1t5lmck3 --include-value --query "value" --output text
```
