### ISSUE TITLE
Support for resources dependent on stages created by SAM

### ISSUE THREAD

**Issue by nstonesplunk** [awslabs/serverless-application-model#207]
When using CloudFormation resources that depend on a stage being deployed (such as ApiKey and UsagePlan), it seems that the only way to fill in the stage resource value of the DependsOn attribute is to launch the CF template without any of the dependent resources and get the logical ID from the deployed Resources tab (if deploying from the console). I don't see any documentation for the logical ID naming convention of stages deployed through SAM, which is why I ran the template first to find it.

Could there be some documentation on the naming convention or a way to explicitly define/export the logical ID of stages in a SAM template so that dependent resources can use them?

**Comment by themummy** [comment]
Same issue here - ApiKey and UsagePlan create fails because they depend on the ApiGateway::Deployment stage.

**Comment by jfuss** [comment]
We have a Doc Revamp (#251) issue that will/does cover documenting the resource SAM generates.

@sanathkr comment from that issue:
"For those of you following along the Issue, we just pushed a first set of changes to docs branch. Internals of resources generated by SAM is done.

And there is a pretty website as well - https://awslabs.github.io/serverless-application-model/. Still very much a work in progress"
