### ISSUE TITLE
SimpleTable does not support parameterized ProvisionedThroughput r/w capacity

### ISSUE THREAD

**Issue by hoppersoft** [awslabs/serverless-application-model#208]
If you create a template that uses parameters to allow the user to specify read/write capacity, the template will fail validation:

    SimpleTableExample:
        Type: 'AWS::Serverless::SimpleTable'
        Properties:
          PrimaryKey:
              Name: MyPrimaryKey
              Type: String
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref ReadCapacityUnitsParam
            WriteCapacityUnits: !Ref WriteCapacityUnitsParam

Generates the error
`Resource with id [SimpleTableExample] is invalid. Type of property 'ProvisionedThroughput' is invalid.`

I suspect that this is due to the fact that !Ref-ed parameters are converted to string and the schema for the SimpleTable resource specifies the r/w capacity as a number. Hard-coding numbers in there works (but is not desired).

Is there a workaround for this?

**Comment by jfuss** [comment]
@hoppersoft Sorry for the late reply. Things up to re:invent were crazy!

Anyways, to your issue. This is a result of our poor support (at the moment) for intrinsic functions. Currently, we are validating that the ReadCapacityUnits and WriteCapacityUnits' values are int. In your case, they are strings. We should totally be supporting intrinsics in this case. We started realizing this some time ago and have tried to make additions to the template compatible with intrinsics to start but we haven't yet gone back to all the existing ones (one of them being SimpleTable). Glancing at the code, this doesn't seem like a huge change at all. I can't promise I will get to it right away (juggling a couple different things at the moment) but will see how I can get this prioritized in the near future. I will comment back when I start to work on this.

As far as a workaround: Sadly, hardcoding the capacity as a number in the resource is the best I have to offer.

**Comment by jfuss** [comment]
I just picked this up. Working on a fix now.

**Comment by jfuss** [comment]
This support was added in the most recent update. Looks like it got missed in the [Release Notes](https://github.com/awslabs/serverless-application-model/releases/tag/1.4.0). But you can now use intrinsics for ReadCapacityUnits and WriteCapacityUnits.
