### ISSUE TITLE
Log4j2 Incompatibility with SAM

### ISSUE THREAD

**Issue by volodymyr-f** [awslabs/serverless-application-model#212]
Hi Guys,

I'm facing very strange issue that when I'm adding log4j2 configuration my functions stops to work correctly.
1. I have a project that contains dependencies to https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-log4j2 and when everything is done according to instructions My functions stops to work correctly and  returns:

`
 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): invalid character '-' after top-level 
`

2. When I copy log4j2.xml to src/main/resources in maven function works fine but as expected log4j2 configuration can't be found

```
START RequestId: aa632e55-8cd9-4b7e-9d3f-196cdab74f9e Version: $LATEST
Save started...ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
.....
```
End everything is green.

After playing with this issue it looks like that even simple sysout with text breaks overal execution and Error is returned:
`
 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): invalid character '-' after top-level 
`

**Comment by jfuss** [comment]
@volodymyr-f This seems like an issue with your Lambda function and not SAM? Is there something related to SAM that is giving you trouble or your Lambda function itself? We can aid in the former but this wouldn't be the proper channel for aiding with Lambda Function specific issues.

**Comment by volodymyr-f** [comment]
@jfuss Thanks for reviewing it. Before posting an issue to github I double checked that:
1. My Function Correctly work when I deploy it on AWS. 
So, when I execute it on AWS lambda I get logs as expected:

> 2017-12-02 18:05:01 INFO J.....Dao:107  My Log

But when I execute the same function on AWS Sam I've got this error:

> Function returned an invalid response (must include one of: body, headers or statusCode in the response object): invalid character '-' after top-level


It looks like if I put simple sysout in any place of code that will be executed AWS Sam will crash.

e.g.:
Such function works fine:

> public class Function implements RequestStreamHandler {
	
	@Override
	public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException 
			
		//My Code
	}}

And such code crashes:

> public class Function implements RequestStreamHandler {
	
	@Override
	public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException 
		System.out.println("Hi");	
		//My Code
	}}

**Comment by jfuss** [comment]
This isn't a SAM issue. SAM is used to deploy Serverless applications through CloudFormation. This is an issue with your Lambda function that you will have to debug. This isn't the appropriate place for Lambda Function help. 

Closing since this isn't related to SAM.

**Comment by volodymyr-f** [comment]
Ah yes. Sorry wrong project
