### ISSUE TITLE
Template error: IAM role stack-Lambda-XXXXX doesn't exist

### ISSUE THREAD

**Issue by tobiasnygaard** [awslabs/serverless-application-model#2132]
### Description:
This is a re-open of issue #641 as we are experiencing this issue again.

Creating a IAM Role resource and referencing properties (.arn) causes error 
`Template error: IAM role stack-Lambda-XXXXX doesn't exist`

### Steps to reproduce:
Run CFN template with IAM Role resource and resource referencing the IAM Role arn.

### Observed result:
Resource referencing the iam role arn throws error Template error: IAM role stack-Lambda-XXXXX doesn't exist

### Expected result:
Creation of IAM role followed by secondary resource with IAM role arn reference.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: N/A
2. If using SAM CLI, `sam --version`:
3. AWS region: eu-central-1

**Comment by simi-obs** [comment]
same issue - i am directly using Cloudformation.
I have an IAM Role and ECS Task Definition specified within same template. Task definition references the role so the Role obviously gets created before the Task definition.

I do not see any problem on health page yet.

**Comment by dhaval-vithalani** [comment]
Same issue - happening while deploying CF which creates IAM Roles for front end deployment. Verified the health page too, same as @simi-obs nothing yet.

**Comment by ncgisudo** [comment]
To anyone only reading the bottom of the thread - whenever this happens, it's because there's some sort of IAM issue/outage.

See also #641

**Comment by simi-obs** [comment]
I've opened ticket with AWS just to make sure they notice
