### ISSUE TITLE
Support API Gateway endpoint configurations e.g. REGIONAL

### ISSUE THREAD

**Issue by humanzz** [awslabs/serverless-application-model#215]
Hello,

I would like to be able to take advantage of https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-api-gateway-supports-regional-api-endpoints/ using SAM.

From the SAM documentation, I saw no way of setting the endpointConfiguration unlike http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html which gives this ability in basic CloudFormation.

**Comment by jfuss** [comment]
@humanzz Regional Endpoints were just added into CloudFormation (and launched) a couple weeks ago. We haven't had the time to add it into SAM just yet with re:Invent going on. 

Do you have a suggestion on how you would like to this look in SAM?

**Comment by humanzz** [comment]
@jfuss to be honest, I wouldn't mind adding a property matching [RestApi](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html)'s [EndpointConfiguration](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html).

I, however, am a little bit confused by the fact that `Types` is an array of Strings even though from all the documentation I saw, it seems to have a singular value of either `EDGE` or `REGIONAL`. If it really is just one type that we are able to select, then maybe `Type` instead of `Types` would make more sense in SAM.
What do you think?

**Comment by humanzz** [comment]
Are there any updates on this?

**Comment by jfuss** [comment]
@humanzz Sorry, but balancing a couple different things at the moment and lost track of this.

So I don't exactly know the reason but my logical guess is that it give more flexibility into this. The options this gives you is, an ```EDGE``` endpoint, ```REGIONAL``` endpoint, or an ```EDGE REGIONAL``` endpoint. This allows the list to grow without needing to maintain all permutations of values of the list. 

I think having the same format as CloudFormation makes sense here but want to make sure the team agrees. 

This has yet to be prioritized and will take some time for us to pick this up. Once we have a better idea on the timeline on this, I will be happy to share.

**Comment by humanzz** [comment]
@jfuss Appreciate the update and looking forward to hear abt the timeline when team agrees.

**Comment by kennu** [comment]
Do you think SAM should perhaps have a generic way to override any CloudFormation properties in the transformed output?

Progress will be very slow, if we have to first wait for new features to appear in CloudFormation, and then wait even longer for them to appear in SAM.

(Sorry to be negative, but delayed support of new features in CloudFormation is already one of the worst aspects of AWS today. It's honestly hard to understand why there is no coordination.)

**Comment by Nr18** [comment]
@kennu I think it makes sense that you can specify the "native" properties of the resources automatically/by default. Would love to see a more generic way to do that then waiting on each new feature to be supported by SAM.

**Comment by jfuss** [comment]
@Nr18 and @kennu Currently, we are not comfortable adding this type of capability (generic overriding of CloudFormation). If you just override them, then what is the value of SAM? We are working on becoming better with getting features launched on Day 1. We feel this is the correct decision and path forward. We do hear and understand the pain of this and are trying to address it.

I created a parent task (#248) we will be using to track this feature (EndpointConfiguration). Closing as duplicate.

**Comment by Shockolate** [comment]
Thanks @jfuss .
Looking forward to #248.
Will you add EndpointConfiguration as a Checkbox in #248, and not just a title?

**Comment by sanathkr** [comment]
Updated #248 with endpoint configuration as checkbox :)

**Comment by kaitea** [comment]
Are there any updates in supporting private EndpointConfiguration in a SAM file? If so, are there samples or docs on how to set this up?

Thanks

**Comment by anthony-tietjen-navex** [comment]
Any update?

**Comment by jmrapp1** [comment]
Also this ^, you can specify private for the `EndpointConfiguration`, but Cloudformation will fail because it requires a policy to be attached.
