### ISSUE TITLE
Hook function examples?

### ISSUE THREAD

**Issue by steveparker-kcom** [awslabs/serverless-application-model#218]
This page refers to hook function examples in the examples folder, but as far as I can see there are none. The AWS docs don't seem to help either.

https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst

**Comment by steveparker-kcom** [comment]
Found an example here: http://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#reference-appspec-file-structure-hooks-run-order-lambda

**Comment by jfuss** [comment]
This was created by #246. 

Example can be found [here](https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/lambda_safe_deployments)
