### ISSUE TITLE
Policy template for sending task status to Step Functions

### ISSUE THREAD

**Issue by gevial** [awslabs/serverless-application-model#2193]
**Description:**

There is a pattern to coordinate queue-based Lambda function execution from a Step Function: https://aws.amazon.com/getting-started/hands-on/orchestrate-microservices-with-message-queues-on-step-functions/

The worker Lambda function in this approach needs to send task status back to the step function. Currently there is no ready-to-use policy for that in SAM.

I'm going to create a PR which adds the policy with states:SendTaskFailure, states:SendTaskHeartbeat and states:SendTaskSuccess permissions.

**Comment by mildaniel** [comment]
Thank you for your contribution! We really appreciate it. Once a PR is submitted we weigh it against our roadmap, do regression testing, make sure it’s backwards compatible and maintainable. Please watch this channel from more updates, and feel free to reach out.

**Comment by bluenautilus2** [comment]
Looking forward to this!
