### ISSUE TITLE
SAM with DeploymentPreference configuration does not create CodeDeploy deployment

### ISSUE THREAD

**Issue by bluepeter** [awslabs/serverless-application-model#223]
I have a simple SAM with a basic DeploymentPreference setup that, after deployment, in the CloudFormation console shows me the various resources it has created.

![screenshot-us-west-2 console aws amazon com-2017-12-06-04-35-56-200](https://user-images.githubusercontent.com/2158187/33645015-89dd403e-da83-11e7-8c21-d87ca04d1e8c.png)

As the above screenshot notes, no CodeDeploy "deployment" has been created. When I go to CodeDeploy in the console, I can see the Application and Deployment Group have been created... but Deployment is empty.

CodeDeploy Deployment is where the S3 bucket reference, Lambda details, and other deployment configuration should be referenced. So without this piece, when I upload a new zip to S3, no new Lambda version is created.

Here is my SAM for reference. (The S3 bucket is created in a different CF template and its ARN exported. I tried with the explicit S3 bucket + path string with the same result.)

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
    ¦ FunctionName: BigOnion_dummyFunction
    ¦ Role: arn:aws:iam::XXXXX:role/BigOnion_Lambda_Logs_S3_Dynamo_SNS
  
    ¦ AutoPublishAlias: live
    ¦ DeploymentPreference:
    ¦   Type: AllAtOnce
    ¦   Role: arn:aws:iam::XXXXX:role/LambdaDeploy
  
    ¦ Handler: index.handler
    ¦ Runtime: nodejs6.10
    ¦ CodeUri:
    ¦   Bucket: !ImportValue s3BigOnionFunctionsHolder
    ¦   Key: 'BigOnion_dummyFunction.zip'
```

I have tried this in both us-east-1 and us-west-2 with the same result.

**Comment by bluepeter** [comment]
Thanks for the update @jfuss that CodeDeploy does not deploy but routes traffic between two versions. You may want to update some of the [documentation pages](http://docs.aws.amazon.com/lambda/latest/dg/automating-updates-to-serverless-apps.html) as I foolishly went on a multi-day wild goose chase to try to get this working... :(

> With just a few lines of configuration, SAM will do the following for you: [...] Deploy new versions of your Lambda function and automatically create aliases that point to the new version.

**Comment by jfuss** [comment]
@bluepeter Couple of questions:
1. What exactly are you expecting? 
2. Is this the first deployment? What happens when another deployment through CloudFormation happens?

**Comment by jfuss** [comment]
So that is referring what 'SAM' will do for you not what CodeDeploy does. While SAM is using CodeDeploy, you should think about this as an implementation detail.

**Comment by bluepeter** [comment]
@jfuss I was expecting that any change to the underlying zip file would trigger a new Lambda version deployment. This way, I can initially deploy code + settings via CF once; and then do subsequent code deploys more simply via `aws s3 cp ...` to upload and replace the underlying zip (which CD would then deploy to Lambda).

I guess I can have a Lambda trigger on S3 do the same thing, but I was interested in explore an AWS recommended approach, and I mis-read CodeDeploy integration.

**Comment by jfuss** [comment]
@bluepeter I would like to pick your brain here a little. Curious, why not do something more like this:

* CI/CD system uploads to S3
* CI/CD system calls update-change-set and then passes the new s3 location in as a parameter
* CI/CD system executes change-set if the change set was created successfully

Why do you need this extra Lambda? Is there something here missing from SAM that would make it much more valuable for CI/CD systems?

It sounds to me like there is this gap you would like to be filled and I am trying to understand what exactly is missing or you feel is missing.

**Comment by bluepeter** [comment]
I suspect that we will eventually go exactly that route. We're in a heavy dev focused stage, with a manual deployment process using http://apex.run/

We are moving to CloudFormation to better document the increasingly complex relationships between resources. But we're finding it difficult to quickly and easily deploy to a dev environment with CF, particularly for Lambda functions. We have to i) push a new zip to S3 and ii) reflect the new name and aws deploy SAM. Slow.

So a thought is to use SAM to reflect the settings and resource dependencies initially. Deploy. And then, for future code deploys, use `aws cp` to replace the underlying zip. Or `aws lambda`. (Or even `apex deploy`.)

Eager to hear any suggestions/thoughts. CF/SAM is making things easier for Lambda (yet to get to API Gateway which is going to be messy), but, since we're in deep dev territory, we need a way to do quick deploys.

**Comment by jfuss** [comment]
@bluepeter So if your team is going to move to CloudFormation eventually (by the sounds of it, you are moving over to it now), I would encourage you to take the time and move over now. The SAM team here has recognized the pain point you are describing. We have nothing concrete in solving it as of now, but is something we are thinking about. To help in making this faster for devs, you could write a simply script that does what you are describing (zip, upload, reflect). Once you have that, the iteration time will increase and will help in reflecting what will go to production (at whatever time that would be). 

What are you trying to test though? Is it changes to a Lambda function or the entire system? Have you looked or heard about [sam-local](https://github.com/awslabs/aws-sam-local)? The README says it best: "SAM Local can be used to test functions locally, start a local API Gateway from a SAM template, validate a SAM template, and generate sample payloads for various event sources." I think this may help reduce some of the churn you are seeing, even more so than my suggestion above.

**Comment by bluepeter** [comment]
Thanks @jfuss I had not heard of sam-local, and I will definitely check it out... later. Just finished the huge task of moving (mostly) everything to CF/SAM... need a bit of a break before onboarding new tech!
