### ISSUE TITLE
Missing colon generates "Internal Error" in CloudFormation

### ISSUE THREAD

**Issue by dslagle** [awslabs/serverless-application-model#226]
After creating a template with a resource type of "AWS::Serverless:API" (notice the missing colon), I was presented with an "Internal Error" in CloudFormation. Simple mistake on my part, but it took me far longer than I would like to admit to track down the issue. This is likely an issue with CloudFormation itself, but it would be nice to have a helpful error on unrecognized types. I believe this was the issue mentioned in #195.

**Comment by sanathkr** [comment]
I don't know why CloudFormation would do that. This is definitely a validation type issue which a tool like [SAM Local CLI's validate command](https://github.com/awslabs/aws-sam-local) would catch. My worry about adding this to the SAM service is false positives.
