### ISSUE TITLE
Allow creation of DynamoDB Stream with SimpleTable

### ISSUE THREAD

**Issue by SanderKnape** [awslabs/serverless-application-model#227]
A common use case for serverless applications is to attach a Lambda function to a DynamoDB stream. However, it is currently not possible to create a stream using the SimpleTable resource. The workaround right now is to use the native DynamoDB resource in CloudFormation.

Can you add support for creating a DynamoDB Stream using the SimpleTable resource? In addition, it should be possible to easily hook on a Lambda function by referencing the SimpleTable resource.

**Comment by sanathkr** [comment]
Totally. Added to the parent tracking Issue - #252. Closing this one in favor of that.
