### ISSUE TITLE
How to get the ApiId without explicitly creating an AWS::Serverless:Api resource?

### ISSUE THREAD

**Issue by rowanu** [awslabs/serverless-application-model#231]
I want to create my API endpoints via function-based definitions (i.e. in the `Events` property), not via a Swagger definition.

I know I don't need to create a `AWS::Serverless::Api` resource, because the API Gateway `RestApi` will be created for me, but without that resource I can't find a way to get the created API's Id.

**Comment by prestomation** [comment]
The implicitly created resource is called `ServerlessRestApi`

You can see an example of its usage here: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/encryption_proxy/template.yaml#L17

**Comment by rowanu** [comment]
Thanks very much! Just saw #222 is already open, so will follow that.
