### ISSUE TITLE
Mixing Lambda Role with custom policies defined in SAM

### ISSUE THREAD

**Issue by quarryman** [awslabs/serverless-application-model#234]
Hi there.
I have initial Lambda setup provided by CodeStar.

`Role:
       Fn::ImportValue:
             !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]`

That's how Role definition looks like and finally it corresponds to particular role that CodeStar creates with a set of initial permissions.

As I start adding Triggering Events or VPC config I have to provide additional policies to allow Lambda to perform actions.

Is it right to add those permissions to initial Lambda execution role which would mean they are not  in SAM template?

Or is there a way to mix execution Role with Inline Policies within SAM template?
Can I have a single example of that?

Another question is, what if permission should be given not to lambda directly but to another Role, can I create policy and add it to a role with SAM?

**Comment by bluepeter** [comment]
If you add an explicit role, the documentation states this about policies:

> Names of AWS managed IAM policies or IAM policy documents or SAM Policy Templates that this function needs, which should be appended to the default role for this function. If the Role property is set, this property has no meaning.

So, it would seem, you cannot combine an explicit Role with explicit Policies in the template. Adding a role will mean that the policies section is not used.

However, note that it does hint that policies added in the template will be appended to the default role that SAM creates. So, if you do not add a Role, and SAM creates one for you, it will apply any policies.

**Comment by sanathkr** [comment]
@bluepeter  is correct.  If you use the `Role` property, SAM will not touch it altogether. But if you skip your role, you can use `Policies` to add permissions to the role that SAM will implicitly create for you.

Are you trying to refer to a role created in a different stack?

**Comment by quarryman** [comment]
@sanathkr hello
I am not going to reference role other then default one created by SAM.
I think I got answer. The idea is that i use standard role created by sam and add additional permissions by providing additional policies.
