### ISSUE TITLE
[ Question ] Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.

### ISSUE THREAD

**Issue by highwaystar86** [awslabs/serverless-application-model#236]
Hello All,

I'me new to the SAM and also github. Sorry if this is the wrong place to ask, would be happy to be redirected to the correct place.

I created a valid Sam template as below ( as verified from sam validate). When i do a cloudformation deploy, it fails with Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.

Even when I go through UI, I get the same error. How do i debug, as there is hardly any information of the error.

I also tried removing the joins and other unnecessary references and hard coded them, still got the same error.

Thanks in advance for any help.

{
  "AWSTemplateFormatVersion" : "2010-09-09",
  "Transform" : "AWS::Serverless-2016-10-31",
  "Parameters" : {
    "CodeBucket" : {
      "Description" : "The Name of the S3 bucket where the Lambda Package resides",
      "Type" : "String"
    },
    "CodeKey" : {
      "Description" : "The S3 key of the Lambda package",
      "Type" : "String"
    },
    "CodeFileName" : {
      "Description" : "The filename of the actual Python or Java or Node.js code",
      "Type" : "String"
    },
    "CodeFunctionName" : {
      "Description" : "The Name of the function",
      "Type" : "String"
    },
    "InputBucketName" : {
      "Description" : "The Name of the New S3 input bucket. Output bucket would be created with -out",
      "Type" : "String"
    }
  },
  "Resources" : {
    "InputBucket" : {
      "Type" : "AWS::S3::Bucket",
      "Properties" : {
        "BucketName" : {
          "Ref" : "InputBucketName"
        }
      }
    },
    "OutputBucket" : {
      "Type" : "AWS::S3::Bucket",
      "Properties" : {
        "BucketName" : {
          "Fn::Join" : [ "-", [ {
            "Ref" : "InputBucketName"
          }, "out" ] ]
        }
      }
    },
    "LambdaExecutionRole" : {
      "Type" : "AWS::IAM::Role",
      "Properties" : {
        "AssumeRolePolicyDocument" : {
          "Version" : "2012-10-17",
          "Statement" : [ {
            "Effect" : "Allow",
            "Principal" : {
              "Service" : [ "lambda.amazonaws.com" ]
            },
            "Action" : [ "sts:AssumeRole" ]
          } ]
        },
        "Path" : "/"
      }
    },
    "RolePolicy" : {
      "Type" : "AWS::IAM::Policy",
      "Properties" : {
        "PolicyName" : "root",
        "PolicyDocument" : {
          "Version" : "2012-10-17",
          "Statement" : [ {
            "Effect" : "Allow",
            "Action" : [ "logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents" ],
            "Resource" : "arn:aws:logs:*:*:*"
          }, {
            "Effect" : "Allow",
            "Action" : [ "s3:GetObject" ],
            "Resource" : {
              "Fn::Join" : [ "", [ "arn:aws:s3:::", {
                "Ref" : "InputBucket"
              }, "/*" ] ]
            }
          }, {
            "Effect" : "Allow",
            "Action" : [ "s3:PutObject" ],
            "Resource" : {
              "Fn::Join" : [ "", [ "arn:aws:s3:::", {
                "Ref" : "OutputBucket"
              }, "/*" ] ]
            }
          } ]
        },
        "Roles" : [ {
          "Ref" : "LambdaExecutionRole"
        } ]
      }
    },
    "pdfWatermarkLambda" : {
      "Type" : "AWS::Serverless::Function",
      "Properties" : {
        "Handler" : {
          "Fn::Join" : [ ".", [ {
            "Ref" : "CodeFileName"
          }, {
            "Ref" : "CodeFunctionName"
          } ] ]
        },
        "CodeUri" : {
          "Fn::Join" : [ "delimiter", [ "s3://", {
            "Ref" : "CodeBucket"
          }, {
            "Ref" : "CodeKey"
          } ] ]
        },
        "Runtime" : "Python2.7",
        "Role" : {
          "Ref" : "LambdaExecutionRole"
        },
        "Policies" : {
          "Ref" : "RolePolicy"
        },
        "Events" : {
          "FileUpload" : {
            "Type" : "s3",
            "Properties" : {
              "Bucket" : {
                "Ref" : "InputBucket"
              },
              "Events" : "s3:ObjectCreated:*"
            }
          }
        }
      }
    }
  }
}

**Comment by sanathkr** [comment]
Are you still running into this problem? If so, can you post the latest template formatted inside a Markdown `codeblock` so its easier to parse?

Internal Failures are painful to debug, but they usually refer to a bug in your template. I would start by stripping things down to bare minimum and building the template up with deploying to CFN every time.

**Comment by highwaystar86** [comment]
Even i realised i had to go step by step and finally resolved. Wish there was more debugging information available.

There were couple of basic issues in my template
"Type" : "**S**3", (Had to be Caps)
"Runtime" : "**p**ython2.7", (P had to be small)

The first of the 2 was causing the transofrmation error

Another change I had to do was use getAtt in the Role part of the Lambda.

Final working template for reference is as below

{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Parameters": {
    "CodeBucket": {
      "Description": "The Name of the S3 bucket where the Lambda Package resides",
      "Type": "String"
    },
    "CodeKey": {
      "Description": "The S3 key of the Lambda package",
      "Type": "String"
    },
    "CodeFileName": {
      "Description": "The filename of the actual Python or Java or Node.js code",
      "Type": "String"
    },
    "CodeFunctionName": {
      "Description": "The Name of the function",
      "Type": "String"
    },
    "InputBucketName": {
      "Description": "The Name of the New S3 input bucket. Output bucket would be created with -out",
      "Type": "String"
    }
  },
  "Resources": {
    "InputBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": {"Ref": "InputBucketName"}
      }
    },
    "OutputBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": {"Fn::Join" : ["-", [{"Ref" : "InputBucketName"}, "out"]]}
      }
    },
    "LambdaExecutionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Path": "/"
      }
    },
    "RolePolicy": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "root",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:*:*:*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:GetObject"
              ],
              "Resource": { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref" : "InputBucket" }, "/*"]]}
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:PutObject"
              ],
              "Resource": { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref" : "OutputBucket" }, "/*"]]}
            }
          ]
        },
        "Roles": [
          {
            "Ref": "LambdaExecutionRole"
          }
        ]
      }
    },
    "pdfWatermarkLambda": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": {"Fn::Join" : [".", [{"Ref" : "CodeFileName"}, {"Ref" : "CodeFunctionName"}]]},
        "CodeUri": {
          "Bucket": {"Ref" : "CodeBucket"},
          "Key": {"Ref" : "CodeKey"}
        },
        "Runtime": "python2.7",
        "Timeout": 120,
        "Role": {
          "Fn::GetAtt": [
            "LambdaExecutionRole",
            "Arn"
          ]
        },
        "Events": {
          "FileUpload": {
            "Type": "S3",
            "Properties": {
              "Bucket": {"Ref": "InputBucket"},
              "Events": "s3:ObjectCreated:*"
            }
          }
        }

      }

    }
  }

}

**Comment by azee** [comment]
In my case I had an empty Mappings: section. Removed it and transformation succeeded
