### ISSUE TITLE
Log configuration for APIG?

### ISSUE THREAD

**Issue by jsancho** [awslabs/serverless-application-model#243]
I've not been able to find anywhere in the docs how can we go about configuring APIG logging with SAM.

I'm referring to these options in the console.
<img width="652" alt="screen shot 2017-12-30 at 12 21 06" src="https://user-images.githubusercontent.com/1547884/34453749-3a593aa4-ed5c-11e7-88d3-d9b6c8a21e50.png">

Is it possible to set the logging options with the current implementation?
If not, but would you suggest as a workaround. An additional transform in CF for example?

Thanks

**Comment by jfuss** [comment]
We are de-duping all Logging Metrics, Usage Plans, etc into #248. Closing this issue in favor of the parent one created.
