### ISSUE TITLE
Error when using AWS::Serverless Transform in child stack 

### ISSUE THREAD

**Issue by bhaukadam007** [awslabs/serverless-application-model#244]
I am trying to create nested stack in which child stack have AWS::Serverless::Function and AWS::Serverless::Api .But when I use AWS::Serverless transform in child stack I get error that  transform cannot be use in child stack.Also when I remove Serverless transform from child stack and add it to parent stack  I get ' Circular dependency error in child stack'.So how to use Serverless transform in case of nested stack and can we use Serverless function and Api in child stack

**Comment by sanathkr** [comment]
Unfortunately Transforms cannot be used in Nested Stacks scenario. This is a limitation of CloudFormation at the moment. I am marking this as a feature request for CloudFormation team. This repo is not monitored by that team, but I will work with them internally on it.

**Comment by sanathkr** [comment]
Closing this in favor of #90
