### ISSUE TITLE
`RekognitionNoDataAccessPolicy` do not support specific `collectionid` resources

### ISSUE THREAD

**Issue by ronaldwidha** [awslabs/serverless-application-model#245]
On https://github.com/awslabs/serverless-application-model/commit/a9b00e1767cf6233dbe60b1f435d7a11d36b4973 

https://github.com/awslabs/serverless-application-model/blob/e4070b5069c883645c339b38006688cdfadf8d38/examples/2016-10-31/policy_templates/all_policy_templates.yaml#L43

`RekognitionNoDataAccessPolicy` requires parameter of `CollectionId`. However `rekognition:detectlabels` do not. In fact the action does not support specific resource constraints.

**Comment by sanathkr** [comment]
True. this is a bug. We will fix it.

**Comment by bmalnad** [comment]
Is there a workaround for this?  I'm trying to deploy an application to the serverless repository.  My app only uses rekognition.detectFaces.  I've tried using RekognitionNoDataAccessPolicy, but I'm not using collections at all.  Is there another policy template I can use?

**Comment by bmalnad** [comment]
@sanathkr I'd like to submit a pull request to fix this because it's holding me up.  All Rekognition related policies currently require a collection id, even though a collection is not required for things like detecting faces, labels, and text.  Would it be better to create a new Rekognition "no collections" policy that allows users to do everything that doesn't actually require a collection, or would it be best to modify one of the existing policies to not require a collection?

**Comment by sanathkr** [comment]
@brettstack I think you have to split the existing policy into two resources sections.. one that uses collectionid and one that doesn’t..

**Comment by brettstack** [comment]
Yeah this will need to be a separate policy.

**Comment by RobRoseKnows** [comment]
I'm working on the Devpost hackathon and ran into this issue so I submitted a PR to fix it: #571. If someone could review it before the hackathon ends on October 2nd (preferably before), that would be splendid.

**Comment by HCans** [comment]
Hello! When is going to be the "RekognitionDetectOnlyPolicy" ready for publishing on the AWS Serverless Application Repository? I also need it for the Devpost Hackaton. So far it does not accept it as a policy template

**Comment by RobRoseKnows** [comment]
@HCans On #571, @jlhood said they're planning a release "soon", before the end of the hackathon.

**Comment by brettstack** [comment]
@RobRoseKnows you should be able to submit it now 🙌

**Comment by HCans** [comment]
Thank you! 
To submit I still need to wait for: https://github.com/awslabs/serverless-application-model/pull/589 . I hope it gets to a release on time :)

**Comment by keetonian** [comment]
@RobRoseKnows @HCans #571 has been released, we are working on #589 as part of our next release
