### ISSUE TITLE
How to pass custom request header to API Gateway integration using SAM Template?

### ISSUE THREAD

**Issue by idxakshay** [awslabs/serverless-application-model#2510]
I want to pass custom headers to Lambda Integration from Sam Template. Is there any way to do it from the SAM template?

I know this is possible from the parameter mapping from the API Gateway console, but I could not find a way to achieve the same using SAM.

![image](https://user-images.githubusercontent.com/71782108/191766920-9cfe247d-58df-4cf4-87b7-4b7bb0ac9b50.png)

**Comment by sriram-mv** [comment]
Is this what you are looking for: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-requestparameter.html?

**Comment by pethaniakshay** [comment]
> Is this what you are looking for: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-requestparameter.html?

Yes, but how to pass the value?
