### ISSUE TITLE
Use CloudFormation:Stack template with SAM

### ISSUE THREAD

**Issue by stevehouel** [awslabs/serverless-application-model#253]
Hello,

I got an issues when using SAM. I reach the limit of resources to created with CloudFormation (200) on my SAM template. With CloudFormation, the solution is to use Stack template for that case. Can we also do it with SAM ? Something like creating a SAM Stack Template and then call it on main SAM template file.

Thank you for your answer

Rgds

Steve

**Comment by sanathkr** [comment]
Unfortunately SAM does not work with nested stacks. Follow #90 for updates
