### ISSUE TITLE
Reaching CloudFormation resources limit

### ISSUE THREAD

**Issue by stevehouel** [awslabs/serverless-application-model#255]
Hello,

I reach the CloudFormation resources creation limit (200). Is there a way with SAM to do something like Stack with CloudFormation (I know that SAM is not yet compatible with that)

Rgds

Steve

**Comment by jfuss** [comment]
@stevehouel How is this question different from the other issue you created: #253?

**Comment by stevehouel** [comment]
On the previous question I asked about nested stack and I got a link on an
orher issue which answer my questions. That one is about resources limit. I
was guessing that maybe there is a workaround for that problem. If not and
the only solution is nested stack then sorry for my issue you can close it
right now. Sorry for the inconvenience
Le mar. 16 janv. 2018 à 18:48, Jacob Fuss <notifications@github.com> a
écrit :

**Comment by jfuss** [comment]
@stevehouel Got it. SAM is restricted to this like any other CloudFormation Stack. The two ways I know of handling this is:
1. Nested stacks
2. Split the stack and resources yourself in some logical fashion that makes sense for your team/service.

The first option is not available yet and can follow #90 for updates. So your only option would be to split them into stacks yourself, given the current state of things.

**Comment by stevehouel** [comment]
Ok thanks a lot for your answer. I already thought about those 2 solutions
and only the first one could solve my problem. I will follow the issue #90
. Now I am switching back to an old CFN way (sadly) Thanks a lot for your
time
Le mar. 16 janv. 2018 à 19:14, Jacob Fuss <notifications@github.com> a
écrit :

**Comment by jfuss** [comment]
:'( Hopefully the support will be here soon

Closing.
