### ISSUE TITLE
502 Bad Gateway with HOWTO example

### ISSUE THREAD

**Issue by ronaldpetty** [awslabs/serverless-application-model#263]
Hello,

I am no JS expert, but wanted to share what I found today.

Using the following tutorial:

https://github.com/awslabs/aws-sam-local/blob/develop/HOWTO.md

I received the following server (user@ubuntu:~/sam$ sam local start-api) error:

```
2018-01-22T03:39:18.055Z	b6456dd5-7f5a-1c3e-6a50-e31a7956bcf1	TypeError: Cannot read property 'product' of null
    at exports.handler (/var/task/products.js:5:34)
```

And the following curl status/error when following the tutorial.

```
$ curl -v http://localhost:3000/products
*   Trying ::1...
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /products/asdf HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< Content-Type: application/json
< Date: Mon, 22 Jan 2018 03:54:57 GMT
< Content-Length: 38
< 
* Connection #0 to host localhost left intact
{ "message": "Internal server error" }
```

The tutorial uses the following construct:

```
let id = event.pathParameters.product || false;
```

However, if you don't provide beyond the template resource path it chokes.  I had to either add a fake path element after like this:

```
user@ubuntu:~/sam$ curl -v http://localhost:3000/products/asdf
200
```

Or change the code to this:

```
exports.handler = (event, context, callback) => {
    let id = false

    if (event.pathParameters) {
      id = event.pathParameters.products
    } else {
      id = false
    }
...
```

Maybe the short version is some particular version of NodeJS/JS/ECMA/V8, but again I am no expert.  Any thoughts on how to best approach something like that?

Keep up the good work!

**Comment by brettstack** [comment]
Sounds like this belongs over at https://github.com/awslabs/aws-sam-cli/

**Comment by brettstack** [comment]
My guess is that `event.pathParameters` is undefined. So that code should maybe be `(event.pathParameters && event.pathParameters.product) || false`
