### ISSUE TITLE
support for ReservedConcurrentExecutions 

### ISSUE THREAD

**Issue by rgarcia** [awslabs/serverless-application-model#265]
CloudFormation supports [specifying](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-reservedconcurrentexecutions) this, but SAM throws an error:

```property ReservedConcurrentExecutions not defined for resource of type AWS::Serverless::Function```

**Comment by jfuss** [comment]
Couldn't get it out fast enough.... :(

We are currently working on it. Setting the correct Labels and assigning to myself.

**Comment by rgarcia** [comment]
I know AWS doesn't provide ETAs, but any chance you could provide a rough estimate? About to create a custom cf resource as a workaround 🐼

**Comment by jfuss** [comment]
@rgarcia Hey sorry for the late response. My queue is still backed up from when I was out.

Does soon work? :) The change is through CR and waiting to get a testing pass through. I would say a couple weeks, at very most, before it is live.

**Comment by rgarcia** [comment]
@jfuss no worries! We have a custom resource workaround that works for now. Will be happy to remove it in a couple of weeks when this is released

**Comment by etapaza** [comment]
@rgarcia hi! I am running into the same problem, I was wondering what your workaround was?

**Comment by rgarcia** [comment]
@etapaza we created a custom cloudformation resource, here's the code https://gist.github.com/rgarcia/22484855cf7c18c961ab8d2dcad53f7f

**Comment by sanathkr** [comment]
This is now available. Checkout [Release Notes](https://github.com/awslabs/serverless-application-model/releases/tag/1.4.0)
