### ISSUE TITLE
Python Encryption Sample: KMS Key ID not found

### ISSUE THREAD

**Issue by 1123** [awslabs/serverless-application-model#267]
Thanks for the great work in this project. I am trying to get the python encryption/decryption sample running. Seems like the code for encrypting a message cannot find the KMS encryption key. 

Invoking the function with a simple test message gives the following result: 

<pre>
{
  "stackTrace": [
    [
      "/var/task/encryption.py",
      40,
      "post",
      "raise Exception(\"KMS Key ID not found.\")"
    ]
  ],
  "errorType": "Exception",
  "errorMessage": "KMS Key ID not found."
}
</pre>

This is the code that throws the exception: 

<pre>
def post(event, context):

    try:
        key_id = os.environ['keyId']
        message = event['body']
        if message is None:
            raise ValueError
    except KeyError:
        raise Exception("KMS Key ID not found.")
    except ValueError:
        return bad_request
</pre>

Seems like the code expects an environment variable named keyId to be set, yet there is none. 

Looking at the template.yml file, I can see that there should be an environment variable named exactly like this:

<pre>
        Environment:
          Variables:
            keyId: !Ref EncryptionDecryptionKey
</pre>

Also when logging the environment with `print(os.environ)`, I can see that the environment variable is indeed set:

<pre>
{'keyId': '1b2d6...', '_HANDLER': 'encryption.post', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'LAMBDA_TASK_ROOT': '/var/task', 'PATH': '/usr/local/bin:/usr/bin/:/bin', 'LD_LIBRARY_PATH': ... }
</pre>

Any hints?

**Comment by 1123** [comment]
Turns out that only the error message was misleading. The key id was indeed found, but the event was lacking the 'body' attribute. This caused the key error. So it seems like the `if message is None` check is useless.

**Comment by sanathkr** [comment]
Merged the Pull Request. Closing this Issue

**Comment by 1123** [comment]
Thanks for the quick merge!
