### ISSUE TITLE
Permissions to be set-up for S3

### ISSUE THREAD

**Issue by iongion** [awslabs/serverless-application-model#27]
I want to take care of upload myself, because I do not like very much the hashes namings schema that are auto-generated. I did my own uploader but now, when I try to deploy my cloudformation, I see this in my console:
```
Could not unzip uploaded file. Please check your file, then try to upload again.
```
- But the zip is there, what must be done ?
- Another thing that I cannot find out is that I name my packages like this `A.B.C.D.zip` , is this confusing the unzip program ? Should I have `ABCD.zip` instead ?

**Comment by sanathkr** [comment]
The error message doesn't look like a permissions issue. Check if the credentials you use to call CloudFormation has access to the S3 object. 

Can you try uploading your Zipfile through the [Lambda UI](console.aws.amazon.com)?

**Comment by iongion** [comment]
I discovered the uploaded files were not valid because the putObject was not received a stream but a string with the file name at Body parameter. This in case someone has the same issues! Thanks for the help, will close this!
