### ISSUE TITLE
Add instructions to export existing serverless resources to SAM

### ISSUE THREAD

**Issue by omatrot** [awslabs/serverless-application-model#272]
I have an existing API Gateway connected to a node.js lambda.
I would like to be able to import those resources in a SAM template.

So far I've been able to export the lambda to SAM from the cloud9 development environment. But API Gateway export seems restricted to Swagger...

Thanks in advance.

**Comment by brettstack** [comment]
You can recreate your resources in SAM, however, these will be new resources (new API; new Lambda functions) and not the existing ones. Exporting to swagger and defining an AWS::Serverless::API resource which points to that Swagger file is the way to do this.
