### ISSUE TITLE
ReservedConcurrentExecutions from SAM

### ISSUE THREAD

**Issue by rbbhar** [awslabs/serverless-application-model#277]
Is there a way to set `ReservedConcurrentExecutions` from the SAM template?
I see that it can be set in the normal cloudformation script - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-reservedconcurrentexecutions.

**Comment by jfuss** [comment]
Duplicate of #265

**Comment by rbbhar** [comment]
@jfuss - Sorry, didn't find that link. Thanks for the update.

**Comment by jfuss** [comment]
@rbbhar Not an issue at all. :)
