### ISSUE TITLE
Control stage names and other details

### ISSUE THREAD

**Issue by iongion** [awslabs/serverless-application-model#28]
Currently we get Prod and Stag  - can these be customized ?
- the stage name
- the stage variables

**Comment by sanathkr** [comment]
You can use the StageName property in [AWS::Serverless::API](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi) resource to customize

**Comment by iongion** [comment]
Ok :) - but you typically have at least two stages, one for production and development, they have stage variables, how can this be added/configured ?
`StageName` looks like a singular concept, this means the SAM api has just one stage that you can control. From what I've experimented with, if this is not provided, then `Prod` and `Stag` stages are auto-created for you.

**Comment by dinvlad** [comment]
Please take a look at the section on AWS::Serverless::Api in the spec (2016-10-31.md). They document how to set stage variables there. What's yet to come is the ability to set these (and the stage name) through parameters for the CloudFormation template.

**Comment by mgibas** [comment]
I would love to see this configuration option when using implicit API definition.

**Comment by sanathkr** [comment]
This will come as part of #248. Closing this in favor of that issue.
