### ISSUE TITLE
Lambda functions in separate files sharing the same API gateway

### ISSUE THREAD

**Issue by pradeepd12** [awslabs/serverless-application-model#281]
Hello,

I would like to deploy lambda functions (using SAM), each in it's own template.yaml (Doing this for modularity purposes). I am assuming each of these functions would end up in a separate stack. I would also like to deploy APIGateway and would like each one of these functions to reference the same API gateway (maybe provisioned in either of the lambda function stacks or a separate stack). Does SAM support this? Samples would greatly help.

If SAM does not support this, any other alternatives?

**Comment by omatrot** [comment]
Could'nt the API Gateway yaml be put in its own file and referenced in each lambda as show in the [HOWTO](https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md#packing-artifacts?) ?

**Comment by shanranm** [comment]
@omatrot  It literally says the feature is not supported in the documentation. May be a removed in the latest versions? Any workaround??
