### ISSUE TITLE
Get SQS url in SAM template.yml file

### ISSUE THREAD

**Issue by MaxVinogradov** [awslabs/serverless-application-model#284]
How can I set up SQS url into the lambda Environment Variables? For example we can get URN for DynamoDB streams:

` !GetAtt SuperTable.StreamArn`

I want to do something like that for SQS url. If this feature exist it will help me to avoid many configuration issues.
(duplicate of https://stackoverflow.com/questions/48551094/aws-get-sqs-url-in-sam-template-yml-file , maybe here I'll get an answer)

**Comment by oharaandrew314** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-properties-sqs-queues-ref

Use the `Ref` function to get the url of the queue.

**Comment by MaxVinogradov** [comment]
@oharaandrew314 , thank you!

**Comment by mnapoli** [comment]
Just a note for those coming here from Google: this doesn't work locally with `sam local` but it works when deployed.

**Comment by jlhood** [comment]
@mnapoli Right. Function env vars have to be provided to `sam local` explicitly via the `--env-vars` option.

**Comment by mnapoli** [comment]
@jlhood thanks a lot for answering. Do you know why it doesn't work?

From my understanding:

- environment variables in general should be populated with `sam local`
- `!Ref` should work with `sam local`

so I don't get why specifically here it doesn't work.

**Comment by keetonian** [comment]
`!Ref` of template parameters work, but SAM CLI has several issues open like https://github.com/awslabs/aws-sam-cli/issues/573 to support more intrinsic functions.
