### ISSUE TITLE
SAM does not create method responses/parameters

### ISSUE THREAD

**Issue by steveparker-1984** [awslabs/serverless-application-model#288]
I am using SAM to create an API with multiple endpoints, some GET, POST and PUT. The API creates ok and using Postman to invoke all works fine. However exporting the API SDK results in an SDK that doesn't work. None of the path parameters are set up correctly. The first result of this is that the SDK does not correctly inject path parameters - though this is easily fixed by manually updating the generated client code. The second result is that when using AWS_IAM auth, you will get an invalid signature exception.

The response to these things always seems to be to use swagger, but this is far from ideal.

More information is on support case 4815746111 if you guys can access that?

**Comment by brettstack** [comment]
Could you provide more info such as your template? What does the resulting template look like in API Gateway console? Are parameters created as expected?
