### ISSUE TITLE
SAM resource types to AWS' one 

### ISSUE THREAD

**Issue by yunchancho** [awslabs/serverless-application-model#292]
Hi,

First of all, I really appreciate SAM maintainers. 

I have some concerns regarding updating SAM template to CloudFormation.
CloudFormation has three behaviors of template update, which depend on resource type.  
'Interruption', 'No interruption', 'Replacement'.

Documents of CloudFormation explain it for every resource type with 'AWS::' namespace.
[reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html?shortFooter=true)
Unfortunately, I couldn't find any contents about SAM's resource types with 'AWS::Serverless::'.  

I would like to know what behavior each property of the following SAM resource type has on update.

 - AWS::Serveless::Function
 - AWS::Serverless::Api
 - AWS::Serverless::SimpleTable

Could anyone let me know?

**Comment by keetonian** [comment]
We launched official AWS Documentation about these resource types! Check it out at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html
