### ISSUE TITLE
KMS Encrypt Policy Template

### ISSUE THREAD

**Issue by oharaandrew314** [awslabs/serverless-application-model#295]
There is a lovely `KMSDecryptPolicy` SAM policy template, but not one for encryption.  Could this be added please?

It would also be nice to see the [Encryption Example](https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/encryption_proxy) updated to show how you would use these new policy templates in a way that you no longer need to explicitly create the IAM roles for the functions, and not have to define an explicit policy on the Encryption key.

**Comment by brettstack** [comment]
Sounds good to me. Think you could send a PR?

**Comment by keetonian** [comment]
#1192 added this feature
