### ISSUE TITLE
Support method settings for APIGateway stages

### ISSUE THREAD

**Issue by sgarcez** [awslabs/serverless-application-model#297]
Method settings such as `LoggingLevel` or `DataTraceEnabled` don't appear to be supported in `AWS::Serverless::Api`.

These are the workarounds I've found:
1. Enabling logs manually [via the console](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html) as suggested in [this comment (#53)](https://github.com/awslabs/serverless-application-model/issues/53#issuecomment-270262348) by @sanathkr 
2. Enabling logs [via the aws cli](https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-stage.html), e.g:
```
aws apigateway update-stage --rest-api-id xxx --stage-name Prod \
--patch-operations "op=replace,path=/*/*/logging/dataTrace,value=true" \
"op=replace,path=/*/*/logging/loglevel,value=ERROR"
```
3. [AWS::ApiGateway::Stage](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html) supports [MethodSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-stage-methodsetting.html), so there may be a workaround where the Stage is defined via `AWS::ApiGateway::Stage` and `AWS::Serverless::Api`'s `StageName` references it?

I've not tested the third option yet, but that would be preferable since the settings are defined in the template which wouldn't require a post deployment step.

It would be great to see this supported in SAM, in the meantime if anyone has any better suggestions please let me know!

**Comment by jfuss** [comment]
@sgarcez We are currently working on support for this. Please follow along with #248.

As far as workarounds, nothing will give you full metrics and logging for the API. There will be gaps between the time CloudFormation will update your API, and the time your run the cli/console or a custom resource will update the API for you.

I don't recommend your 3rd option. It creates more of a mess than it is worth (imo). If you need this now, either a custom resource or manually doing this is your best option. We are doing our best to get this support out as quickly as we can.

**Comment by sgarcez** [comment]
Thanks @jfuss, the third option is a rabbit-hole I'm happy to avoid, having already spent some time trying to understand how best to use stages and aliases within SAM (incidentally I wrote up some of my findings and quoted you [here](https://medium.com/2pax/managing-multi-environment-serverless-architecture-using-aws-an-investigation-6cd6501d261e))

Will follow #248, apologies for the duplicate.

**Comment by jfuss** [comment]
@sgarcez :)

No reason for an apology. It's a completely valid question!

We should be communicating best practices like this in a better way. I am going to leave this issue open as we should be capturing `how best to use stages and aliases within SAM` easier to consume. 

Given you spend time on this, would you be willing to transform some of those learnings/findings into a best practice or FAQ section in our docs. It has been on my plate for a little while to get that part of the docs started. We are tracking some of this work on #251 and think it would be awesome if you can contribute to what you have investigated so far.

**Comment by sgarcez** [comment]
@jfuss Sure, happy to do that, will take at look #251.

Re docs in general, some of the other issues that we've run up against were not SAM specific, but rather Lambda/APIGW issues, and I think this will be the case for a lot of users for whom SAM is the entryway into serverless on AWS. I suppose that the SAM docs don't need to provide answers for those issues necessarily but you could make the case for them taking a pedagogical role and guiding users to the right places. (e.g issues related to authorizers, pure lambda integration error response mappings, etc).

**Comment by barrett-rob** [comment]
+1 this capability will be very attractive to us

**Comment by jfuss** [comment]
Method settings was added in [1.4.0](https://github.com/awslabs/serverless-application-model/releases/tag/1.4.0). We will need to update the FAQ that @sgarcez add (woot!!) but calling this out of scope of this issue and therefore closing.
