### ISSUE TITLE
AutoPublishAlias deletes other aliases

### ISSUE THREAD

**Issue by Shockolate** [awslabs/serverless-application-model#298]
When specifying the `AutoPublishAlias` field for a Function, CloudFormation will delete all aliases that are not the specified in the single field.

Upon pull request, we'd like to deploy to a "Staging" environment, by creating an alias named "Staging", and an APIGateway Stage named "Staging", and have them point them at each other.
Upon merge, we'd like to deploy to a "Production" environment, by following the same procedure.

If there is an existing deployment to the "Production" environment, a new pull request (i.e. deployment to Staging) will ****delete the "Production" version and alias.****

Is this the intended behavior?
Any suggestions on how to achieve our goal?

We are using the [aws dotnet lambda tools](https://github.com/aws/aws-lambda-dotnet) to deploy, particularly the [DeployServerless](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Tools/Commands/DeployServerlessCommand.cs) command.

### Our SAM File ###
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Description": "The Service running ASP.NET Core in Lambda.",
  "Parameters": {
    "ServiceNameParameter": {
      "Type": "String",
      "Default": "Template",
      "Description": "Enter the service name. Must be the same as the .csproj for it will be used in referencing the namespace & assembly. Default is Template."
    },
    "EnvironmentParameter": {
      "Type": "String",
      "Default": "Development",
      "Description": "Enter the environment. Default is Development."
    }
  },
  "Globals": {
    "Function": {
      "Runtime": "dotnetcore2.0",
      "Timeout": 30,
      "MemorySize": 1024,
      "VpcConfig": {
        "SecurityGroupIds": [
          {
            "Fn::ImportValue": "VpcSecurityGroupId"
          }
        ],
        "SubnetIds": {
          "Fn::Split": [
            ",",
            {
              "Fn::ImportValue": "VpcPrivateSubnetIds"
            }
          ]
        }
      }
    }
  },
  "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "FunctionName": {
          "Fn::Sub": "${ServiceNameParameter}"
        },
        "Handler": {
          "Fn::Sub": "${ServiceNameParameter}::${ServiceNameParameter}.LambdaEntryPoint::FunctionHandlerAsync"
        },
        "CodeUri": "",
        "Role": {
          "Fn::ImportValue": "ServerlessExecutionRole"
        },
        "Description": {
          "Fn::Sub": "Backing Lambda for the ${ServiceNameParameter} in ${AWS::Region}."
        },
        "AutoPublishAlias": {
          "Ref": "EnvironmentParameter"
        },
        "Tracing": "PassThrough",
        "Environment": {
          "Variables": {
            "ASPNETCORE_ENVIRONMENT": {
              "Ref": "EnvironmentParameter"
            }
          }
        }
      }
    }
  }
}
```

**Comment by rvypandey** [comment]
You might want to have a look at https://github.com/awslabs/serverless-application-model/issues/304.

**Comment by Shockolate** [comment]
Thanks @rvypandey
I don't know why #304 was asked while this issue was opened earlier, or why jfuss responded to that one over this one.
I guess this issue will be closed?

**Comment by jfuss** [comment]
@Shockolate My appologizes. I didn't choose that one over this one on purpose. I noticed the email notification for #304 and responded.

Did that issue cover your questions or concerns?

**Comment by Shockolate** [comment]
Yes, I will review #304 closely 😃 
Been on vacation, glad there's progress here!
