### ISSUE TITLE
How to setup body transformation?

### ISSUE THREAD

**Issue by leonkyr** [awslabs/serverless-application-model#3]
Hi,

There are not many example out in the Internet yet. I tried to use this transformation for my existing serverless App where I return html and json in different API+lambda combinations and I use body transformations for requests and responses.

How can I specify these things with this transformation?

**Comment by sanathkr** [comment]
You can define body transformations in the Swagger file using [custom API Gateway integrations](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html#api-gateway-swagger-extensions-integration-responseTemplates). When you specify the API using `AWS::Serverless::Api` resource, upload swagger file to S3 and set `DefinitionUri` property to be the S3 URI of the swagger file.

**Comment by leonkyr** [comment]
Is there a way to not use Swagger?

**Comment by sanathkr** [comment]
Unfortunately not.
