### ISSUE TITLE
Incorrect Version and Alias references with !Ref

### ISSUE THREAD

**Issue by tomyister** [awslabs/serverless-application-model#303]
Hi,
I just wanted to let you know that there seems to be a mistake in the example code to assume a serverless function.

In "Ref": "MyLambdaFunction.Version", Ref is not meant to return a specific attribute but a default value, depending on the resource that is referenced, such as ARN or ID. Ref should be replaced by Fn::GetAtt.

Source:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html

In "Ref": "MyLambdaFunction.Alias", .Alias should be removed as the only return value is Alias ARN which is returned by a simple Ref.

Source:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html

Thank you.

**Comment by benkehoe** [comment]
It is different from the standard CloudFormation syntax. In SAM, "MyLambdaFunction" is the logical id of an AWS::Serverless::Function, and this corresponds to *multiple* standard CloudFormation resources: an AWS::Lambda::Function, an AWS::Lambda::Version, and an AWS::Lambda::Alias (see the in-progress new documentation [here](https://awslabs.github.io/serverless-application-model/internals/generated_resources.html#with-autopublishalias-property). But you only have one logical id. So to give access to these "hidden" resources, SAM is using this special "subresource" syntax of .Version and .Alias.

**Comment by jfuss** [comment]
@tomyister @benkehoe Is correct.

Please let me know if this does answer your questions. I will leave this open to make sure.

**Comment by tomyister** [comment]
Yes, it does. Thank you.

**Comment by jfuss** [comment]
@tomyister Sweet :)

I am going to go ahead and close this since this was answered.
