### ISSUE TITLE
Issue in using parquet file as reference data source in Kinesis Application

### ISSUE THREAD

**Issue by bhaukadam007** [awslabs/serverless-application-model#325]
I want to use **parquet file** as **reference data source** in **Kinesis application .**
I read **AWS documentation** regarding kinesis reference data source and they told that we can use only **JSON or CSV files** as reference data source **not any other format is supported.**
So how to use **parquet** as reference data source in Kinesis application or it is not possible?

**Comment by jfuss** [comment]
This repo is centered around the Serverless Application Model, the `AWS::Serverless::*` resources that can be added to and deployed through CloudFormation. This seems like a general question about what Kinesis supports. Is that correct? If so, this is not the correct place to be asking these types of questions.

**Comment by bhaukadam007** [comment]
Thanks for your valuable reply . But I dont know where I should post this question to get right answer.Can you provide me some **Github** link or **forum** where I should post this question.

**Comment by jfuss** [comment]
@bhaukadam007 You can try the [AWS Forums](https://forums.aws.amazon.com/index.jspa) or StackOverflow.

Doing a quick google search, I found [this](https://stackoverflow.com/questions/45430535/write-parquet-from-aws-kinesis-firehose-to-aws-s3) which seems to suggest it is possible but takes some work to get to. 

I am going to close this issue as it is not related to SAM.
