### ISSUE TITLE
Override StageName of Implicit API using Globals

### ISSUE THREAD

**Issue by stephankaag** [awslabs/serverless-application-model#330]
It *appears* to be impossible to set the properties of the implicitly created API. Am i right or is there a way without having to specify an API explicitly (and having to use Swagger)?

**Comment by sanathkr** [comment]
Nope. You can use `Globals` section to specify properties for Implicit API - https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#implicit-apis 

See this example - https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/implicit_api_settings/template.yaml 

All properties of `Api` section in `Globals` will be applied to Implicit APIs

Does this help?

**Comment by stephankaag** [comment]
Yes i saw that. In my case i want to set the stagename and that property is not supported by the globals.

**Comment by sanathkr** [comment]
Yeah, StageName is not supported at the moment because of some internal architecture limitations. We will remove this limitation soon. I will tag this as a feature request and change the title to describe the issue better. 

Is this a blocker for you?

**Comment by stephankaag** [comment]
Thanks! Not a real blocker for now because i can work around it. However I would like to keep my templates as small as possible :-)

**Comment by dnagir** [comment]
I tried to override the `StageName` as per the [this example](https://github.com/awslabs/serverless-application-model/blob/a6fb61378b87f1b0181c7a5dafe35ed83a3c0d71/examples/2016-10-31/inline_swagger/template.yaml#L8) (only changed the stage to `api`).

But it seems to be ignored and I'm still getting the `Prod` stage (as well as annoying `Stage`).

Does anyone have a working example of a stage name override? Wondering if I'm doing something wrong 🤔

**Comment by kangks** [comment]
I tried to overcome this by explicitly define API, but when I inspect my Lambda function in the console, I noticed the api event to my lambda function has *mixture* of stage, for example, for `GET` Method, the API event is from stage prod (e.g. https://1icye4gf2i.execute-api.us-west-2.amazonaws.com/prod/users), but for `PUT` the API event is from stage Stage (https://1icye4gf2i.execute-api.us-west-2.amazonaws.com/Stage/users)

This is my template
```
    Type: AWS::Serverless::Api
    Properties:
      Cors: 
        AllowOrigin: "'*'"
      StageName: prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "2017-04-26T03:23:48Z"
          title: !Sub "${AWS::StackName}-API"
        paths:
          /users:
            put:
              security:
              - CognitoAuthorizer: []
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses: {}
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                uri: 
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                requestParameters:
                    integration.request.header.X-Amz-Invocation-Type: "'RequestResponse'"
            get:
              security:
              - CognitoAuthorizer: []
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses: {}
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                uri: 
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                requestParameters:
                    integration.request.header.X-Amz-Invocation-Type: "'RequestResponse'"
```

and the Events for `AWS::Serverless::Function`:
```
          Events:
            usersPut:
              Type: Api 
              Properties:
                  Path: /users
                  Method: put
                  RestApiId: 
                      !Ref UserAPI                      
            usersGet:
              Type: Api 
              Properties:
                  Path: /users
                  Method: get
                  RestApiId: 
                      !Ref UsersAPI                      
```
Is this expected? Or is there any way I can specify the stage name for the API event?
`

**Comment by jlhood** [comment]
@kangks I'm not sure what you mean by a mixture of prod and Stage. The resource+methods defined by the swagger definition body should exist in both prod and Stage, meaning both prod and Stage API Gateway stage endpoints should support both GET and PUT methods to /users.

**Comment by kangks** [comment]
The mixed of stage name, for example, `/prod/hello` for `DELETE` and `/Stage/hello` for `GET`, do not affect the functional. 

Confirmed the behavior by testing the Hello World example with successful invocation of API GW on `/prod/hello` for `DELETE`.

**Comment by jlhood** [comment]
@kangks Thanks for the update. Sounds like this isn't a SAM issue then.

**Comment by yskkin** [comment]
With SAM CLI version 0.53.0, the following template could not build.
Is this already implemeted?

```
 Api:
    # https://github.com/awslabs/serverless-application-model/issues/191#issuecomment-515589603
    OpenApiVersion: 3.0.2
    StageName: v1
```

Error:
```
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidGlobalsSectionException('Globals', "'StageName' is not a supported property of 'Api'. Must be one of the following values - ['Auth', 'Name', 'DefinitionUri', 'CacheClusterEnabled', 'CacheClusterSize', 'Variables', 'EndpointConfiguration', 'MethodSettings', 'BinaryMediaTypes', 'MinimumCompressionSize', 'Cors', 'GatewayResponses', 'AccessLogSetting', 'CanarySetting', 'TracingEnabled', 'OpenApiVersion', 'Domain']")] ('Globals', "'StageName' is not a supported property of 'Api'. Must be one of the following values - ['Auth', 'Name', 'DefinitionUri', 'CacheClusterEnabled', 'CacheClusterSize', 'Variables', 'EndpointConfiguration', 'MethodSettings', 'BinaryMediaTypes', 'MinimumCompressionSize', 'Cors', 'GatewayResponses', 'AccessLogSetting', 'CanarySetting', 'TracingEnabled', 'OpenApiVersion', 'Domain']")
```
