### ISSUE TITLE
application publishing fails with 'only policy templates' allowed - even for out of the box AWS templates

### ISSUE THREAD

**Issue by cjlennon** [awslabs/serverless-application-model#331]
Hi there

I cannot currently publish any packages with policies.  Publishing fails with for example `Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [lambdatestharness] is invalid. Only policy templates are supported in 'Policies' property.`

This happens even when I select one of the standard AWS templates such as [serverless-application-model/examples/apps/lambda-test-harness/template.yaml](https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/lambda-test-harness/template.yaml)

This seems to be a new problem.  Has something changed?

Chris

**Comment by sanathkr** [comment]
Are you publishing to Serverless Application Repository? If so, yes. They accept only policy templates and not inline IAM policies

**Comment by cjlennon** [comment]
Hi sanathkr

I am publishing to the Serverless Application Repository yes.  I am aware of only accepting policy templates which is why I have used one of AWS's own templates.  Please refer to the link in my original issue report [serverless-application-model/examples/apps/lambda-test-harness/template.yaml](https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/lambda-test-harness/template.yaml)

Why would an AWS example Serverless Application Repository template not work?

Please consider changing the label to 'bug' unless I am missing something here

Chris

**Comment by sanathkr** [comment]
Undoubtedly a bug. The apps under `apps` folder should be compatible with App Repo. Looks like the app was already published to the repo - https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:077246666028:applications~lambda-test-harness. I am working to get to the bottom of this.

We will get it fixed. Thanks for the issue!

**Comment by eamonnfaherty** [comment]
Is this bug still open?

**Comment by brettstack** [comment]
Yes, but only because that app is invalid for the Senseless App Repo because it has an online policy

**Comment by RobRoseKnows** [comment]
I'm having a similar issue when adapting the `rekognition-python` template. The [example](https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/rekognition-python/template.yaml) in the apps directory is also using Inline policies.

**Comment by keetonian** [comment]
@RobRoseKnows we recently updated that app to use managed policies; that update is still only on the develop branch here: https://github.com/awslabs/serverless-application-model/blob/develop/examples/apps/rekognition-python/template.yaml

**Comment by keetonian** [comment]
Issue is fixed
