### ISSUE TITLE
Example for RateLimit and BurstLimit in SAM

### ISSUE THREAD

**Issue by dirkgomez** [awslabs/serverless-application-model#333]
Is it possible to configure RateLimit and BurstLimit in SAM as described here for Cloudformation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-usageplan-throttlesettings.html

If so, could you provide an example?

**Comment by jfuss** [comment]
@dirkgomez Usage Plans are not yet a first class citizen in SAM. This is being tracked in #248. There have been others who have got this working. I would check out that issue (also has other closed issues linked for how people got this working #169).

Closing in favor of the bigger tracking issue
