### ISSUE TITLE
stageVariables in Swagger are not expanded

### ISSUE THREAD

**Issue by mparaz** [awslabs/serverless-application-model#34]
When trying the serverless-application-model/examples/2016-10-31/api_swagger_cors/ example, the Lambda function name is not expanded.

I edited the swagger.yaml to add Role: to the Lambda as it's required in my environment. and then did packaging and deploying. 

I went to the API Gateway console for Method Execution / ANY - Integration Request. 
In the Lambda Function value,

Expected: the name of the Lambda function, dynamically assigned.
Got: ${stageVariables.LambdaFunctionName} 

This happened when I was testing #20, after https://github.com/awslabs/serverless-application-model/issues/20#issuecomment-265011626

**Comment by sanathkr** [comment]
Were you able to call your API endpoint to invoke your Lambda function? 

Stage variables are stored as a property on the API Stage. You can view its value in the Stage section on console. Even though Console displays ${...}, your API endpoint should work if the stage variable value contains the Lambda function ARN

**Comment by mparaz** [comment]
Thanks. I can call the API endpoint and I confirm that the stage variables are set.
