### ISSUE TITLE
CodeURI optional argument?

### ISSUE THREAD

**Issue by red8888** [awslabs/serverless-application-model#340]
When running locally I have a script pip install to a sub dir, copy the py files to the subdir, then lambda points to that with CodeUri. When the time comes to deploy I dont care about not pulling modules into the working directory and just have deployment automation pip install to the working directory then run the sam local commands to package and deploy.

Can I just pass CodeURL as an arg to "sam local invoke"? That would solve all my problems

I see something called `--parameter-values` but zero documentation or actual examples of how to use that

I tried removing CodeUri from the template and pass as an arg but this does not work: `sam local invoke myfunction --template template.yaml -e event.json --parameter-values "CodeUri=./mybuild"`

**Comment by jfuss** [comment]
@red8888 I think you may have the wrong repo. This sounds like it belongs in the [SAM Local repo](https://github.com/awslabs/aws-sam-local/issues). 

Can you open this issue there?

**Comment by jfuss** [comment]
@red8888 I am closing this. Please create an issue in the SAM Local repo I linked above.
