### ISSUE TITLE
Api property Cors doesn't work

### ISSUE THREAD

**Issue by terma** [awslabs/serverless-application-model#343]
Based on release info [1.4.0](https://github.com/awslabs/serverless-application-model/releases/tag/1.4.0)

```AWS::Serverless::Api``` supports ```Cors``` property. 

I tried stack below and no CORS specific items added to API Gateway:

```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ServerlessRestApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        securityDefinitions:
          sigv4:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: awsSigv4
        paths:
          # smt
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'86400'"
```

Do I need to enable new feature somehow?

**Comment by jfuss** [comment]
@terma Is `ServerlessRestApi`the actually LogicalId of your `AWS::Serverless::Api`?

**Comment by terma** [comment]
@jfuss thx for help. Answer: ```ServerlessRestApi``` is reserved for SAM, so my Api resource should have different name.

**Comment by rabowskyb** [comment]
Just in case it might help, here's a link to the AWS Startup Kit Serverless Workload, which has CORS enabled for its sample RESTful API:  https://github.com/aws-samples/startup-kit-serverless-workload.
