### ISSUE TITLE
Tags feature is not working in the global section of SAM template

### ISSUE THREAD

**Issue by ramanganapathy** [awslabs/serverless-application-model#347]
Based on the [Link](https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#id1) expecting tags to be supported in the global section but it is not working
Status:

FAILED - Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 18. Resource with id [abcd] is invalid. Type of property 'Tags' is invalid.

**Comment by jfuss** [comment]
@ramanganapathy Can you please supply the relevant snippets to help aid us in understanding what your template looks like? The `Globals` section is probably enough but feel free to add extra context if you feel it may be useful.

**Comment by ramanganapathy** [comment]
`---
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Globals:
  Api:
    MethodSettings: [{
            "LoggingLevel": "INFO",
            "MetricsEnabled": True,
            "DataTraceEnabled": True,
            "ResourcePath": /*,
            "HttpMethod": *,
        }]
  Function:
    Runtime: java8
    VpcConfig:
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetIds: !Ref SubnetIds
    MemorySize: 1536
    CodeUri: ./
    Tracing: Active
    AutoPublishAlias: live
    Tags:
      -
        Key: AppCodeTag
        Value: Testing

Resources:
  GetGreeting
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.test.handler.GetGreetingHandler
      Role:  arn:aws:iam::xxxxxxxxxxx
      Events:
        GetEvent:
          Type: Api
          StageName: Prod
          Properties:
            Path: /api/greet
            Method: get

`

**Comment by jfuss** [comment]
@ramanganapathy This is an issue with your template. You are defining tags following the CloudFormation Documentation not SAM. SAM has a simplification of how you define Tags for resources and will produce the correct 'vanilla' CloudFormation. [Here](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#example-awsserverlessfunction) is an example from our docs and the property is explained [here](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#properties).

For you example, you should be defining Tags like below. We will turn it into what you have currently and add it to the SAM generated Lambda Function Resource: 
```
Tags:
      AppCodeTag: Testing
```

**Comment by ramanganapathy** [comment]
Thank you very much. Working great as expected. 
On a side note when deploying through SAM if I specify stage (mystage) then I see three stages created. They are Stage, Prod and mystage. Also I dont find a way to remove unwanted stages that come default. I saw some similar issues around this topic. Is there a fix available for this

**Comment by sanathkr** [comment]
@ramanganapathy Unfortunately no. There is no solution yet to remove the extra Stage. Follow #191 for updates. 

I am closing this issue for now because your question is answered
