### ISSUE TITLE
Link PolicyTemplate Docs to the Code instead of maintaining both

### ISSUE THREAD

**Issue by jfuss** [awslabs/serverless-application-model#362]
**Description:**
Currently we have PolicyTemplates in two different places, [docs](https://github.com/awslabs/serverless-application-model/tree/develop/docs/policy_templates_data) and [code](https://github.com/awslabs/serverless-application-model/tree/develop/samtranslator/policy_templates_data). At the moment, when we update a Policy Template in code we then need to update the template in the docs. To simplify this and keep things always up to date, let's point the docs at the code.

**Observed result:**
We have PolicyTemplates in two places :(

**Expected result:**
We only have to maintain one, which should be the one under the `samtranslator/policy_templates_data/` folder. Our docs should point to the files there.

**Comment by aletheia** [comment]
Personally I do not agree with this position: even if it is convenient for team developing SAM, IMHO it produces a really BAD developer experience. Moreover, used SAM for a while and continuously searching things navigating links pointing to outside references or code is frustrating.

When I am writing SAM services, as a dev I need a fast and quick reference to look up to.

**Comment by brettstack** [comment]
This was done last year.
