### ISSUE TITLE
CodePipelineReadOnlyPolicy is requiring a pipeline name

### ISSUE THREAD

**Issue by cplee** [awslabs/serverless-application-model#368]
**Description:**

Unable to use the `CodePipelineReadOnlyPolicy` policy template since it requires a single pipeline name via the parameter `PipelineName` and the schema for parameters doesn't allow `*`

**Steps to reproduce the issue:**
1. Create a template with:
``` 
  - CodePipelineReadOnlyPolicy:
       PipelineName: '*'
```

**Observed result:**
> Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [PipelineDashboardEventHandler] is invalid. 'CodePipelineReadOnlyPolicy' policy template contains unsupported value for a parameter 'PipelineName'.

**Expected result:**
Should work

**Comment by sanathkr** [comment]
'*' is definitely a valid value and is allowed. I think this might be something to do with YAML formatting.

Can you convert your YAML to JSON (you can do it online here https://www.json2yaml.com/), and post the relevant JSON sections? We want to ensure it looks like `{"CodePipelineReadOnlyPolicy": {"PipelineName": "*"}}`

**Comment by cplee** [comment]
@sanathkr thanks for the quick response.  I converted to JSON and still get the same error.  Complete template is available below:

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Description": "Create pipeline-dashboard application.",
  "Resources": {
    "PipelineDashboardEventHandler": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Description": "Create CloudWatch metrics from CodePipeline events",
        "Handler": "index.handlePipelineEvent",
        "Runtime": "nodejs6.10",
        "CodeUri": "s3://pipeline-dashboard-us-east-1/bc131ad7fd38fd97ecd0387124bb2bda",
        "Events": {
          "PipelineEventRule": {
            "Type": "CloudWatchEvent",
            "Properties": {
              "Pattern": {
                "source": [
                  "aws.codepipeline"
                ],
                "detail-type": [
                  "CodePipeline Pipeline Execution State Change",
                  "CodePipeline Stage Execution State Change",
                  "CodePipeline Action Execution State Change"
                ]
              }
            }
          }
        },
        "Policies": [
          {
            "CloudWatchPutMetricPolicy": {
            }
          },
          {
            "CodePipelineReadOnlyPolicy": {
              "PipelineName": "*"
            }
          }
        ]
      }
    },
    "PipelineDashboardGenerator": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Description": "Build CloudWatch dashboard from CloudWatch metrics",
        "Handler": "index.generateDashboard",
        "Runtime": "nodejs6.10",
        "CodeUri": "s3://pipeline-dashboard-us-east-1/bc131ad7fd38fd97ecd0387124bb2bda",
        "Timeout": 60,
        "Events": {
          "DashboardEventRule": {
            "Type": "Schedule",
            "Properties": {
              "Schedule": "cron(*/5 * * * ? *)"
            }
          }
        },
        "Policies": [
          {
            "CloudWatchDashboardPolicy": {
            }
          }
        ]
      }
    }
  }
}
```

**Comment by jfuss** [comment]
@cplee Where are you running the template at? I was able to take the template you provided and deploy to us-west-2.

**Comment by cplee** [comment]
@jfuss I'm trying to register the template as a new version in Serverless Application Registry in us-east-1

**Comment by sanathkr** [comment]
@cplee This makes sense now! Serverless Application Repository does not allow you to provide a value of `*` for the resource name (in your case, it is the name of CodePipeline resource). 

This might sound a bit counter-intuitive, but it is done to make apps more secure. As a publisher, the best practice is to parameterize the resource name using Template Parameters, and let the consumer decide the pipeline to give access to, at the time of deployment. Consumers could even choose a value of `*`. 

```
Parameters:
  PipelineNameParam:
     Type: String

Resources:
   ...
        CodePipelineReadOnlyPolicy: !Ref PipelineNameParam
```

This way, your app is generic when you publish, and consumers can give access to necessary resources when deploying. This is just similar to how you would write a software library with generic interfaces that consumers will customize for their needs.

Does this make sense?

**Comment by cplee** [comment]
@sanathkr thanks, that makes perfect sense.  For now, i'll add the parameter.  However, I'd argue that the SAM policy templates are very inconsistent in that many do default to `*` for the Resource (examples below).  I propose creating some naming standard for the policy templates that also implies scoping of the resources to one vs all.  For example, `EC2DescribePolicy` vs `EC2DescribeAllPolicy`.

* [EC2DescribePolicy](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json#L82)
* [CloudFormationDescribeStacksPolicy](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json#L331)
* [AWSSecretsManagerRotationPolicy](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json#L1132)

**Comment by sanathkr** [comment]
Good catch. We use `*` for Resources in the policy template definition like [EC2DescribePolicy](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json#L95) because the underlying API like `DescribeRegions` does *not* support resource level scoping. So if we set any value for the resource other than "*", the API would fail. 

This might be worth adding to a documentation section on how Policy Templates are created and how they work, which is lacking today. 

Would you be interested in writing a para or two based on your knowledge and send a pull request? I will be happy to contribute to your Pull Request. We can work together to create a good documentation on how Policy Templates work.

**Comment by keetonian** [comment]
Here's a page on Policy Templates from the AWS SAM Docs: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
