### ISSUE TITLE
Nested Fn::ImportValue in Fn::Sub not working for SAM template

### ISSUE THREAD

**Issue by nomanyaqubny** [awslabs/serverless-application-model#372]
**Description:**
I am trying to define Serverless API resource. But having trouble in defining location of swagger specification file using function ImportValue.
 
**Steps to reproduce the issue:**
I am not able to define `AWS::Serverless::Api` resource having nested function `ImportValue` in Location. I have tried following three ways, none of them work.

Note: Stack parameters are defined properly and export value from other stack exists. Not showing them here for brevity reason. 

```
ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: !Sub ${AWS::StackName}-API
        StageName: !Ref ApiGatewayStageName
        DefinitionBody:
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location:
                Fn::Sub:
                - s3://${BucketName}/${SwaggerSpecificationS3Key}
                - BucketName:
                    Fn::ImportValue:
                      !Sub "${EnvironmentName}-dist-bucket-${AWS::Region}" 
```

```
ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: !Sub ${AWS::StackName}-API
        StageName: !Ref ApiGatewayStageName
        DefinitionBody:
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location:
                Fn::Sub:
                - s3://${BucketName}/${SwaggerSpecificationS3Key}
                - BucketName:
                    !ImportValue 'dev-dist-bucket-us-east-1' 
```

```
ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: !Sub ${AWS::StackName}-API
        StageName: !Ref ApiGatewayStageName
        DefinitionBody:
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location:
                Fn::Sub:
                - s3://${BucketName}/${SwaggerSpecificationS3Key}
                - BucketName:
                    Fn::ImportValue: 'dev-dist-bucket-us-east-1' 
```

Cloudformation shows following error.

FAILED - The value of parameter Location under transform Include must resolve to a string, number, boolean or a list of any of these.

However, if I do not use `ImportValue` it works with a nested `Fn::Sub`

```
ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: !Sub ${AWS::StackName}-API
        StageName: !Ref ApiGatewayStageName
        DefinitionBody:
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location:
                Fn::Sub:
                - s3://${BucketName}/${SwaggerSpecificationS3Key}
                - BucketName:
                    Fn::Sub: dist-bucket-${EnvironmentName}-${AWS::Region} 
```

Is it function ImportValue that cannot be used under function Sub?

or 

Is it yaml format that does not support ImportValue under a Sub?

**Comment by sanathkr** [comment]
This would be a CloudFormation question because SAM does not explicitly parse any of the ImportValue notations. My guess is that nesting import value might not work. I am not sure

**Comment by nomanyaqubny** [comment]
I can create other resource types and output expected value in the output section of my template using nested import value. I even tried using Join function having nested Import value.

**Comment by sanathkr** [comment]
This is probably something specific to the Fn::Include, which is also a transform. Unfortunately we are focused on the SAM Transform here and don't have insights into Fn::Include.
