### ISSUE TITLE
aws cloudformation package command slows down significantly with size.

### ISSUE THREAD

**Issue by jabalsad** [awslabs/serverless-application-model#382]
**Description:**

running `aws cloudformation package` has slowed down significantly as the package got bigger. We have maybe 10 or so lambda functions and a bunch of other resources that add up to a 54MB package. We're using the go1.x runtime which means we have to package individual binaries for each lambda function (not sure if relevant).

**Steps to reproduce the issue:**
1. Create repo with many go1.x lambda function binaries
2. Create serverless cloudformation template with a bunch of lambda functions and API gateway.
3. Run `aws cloudformation package`

**Observed result:**
CLI pauses for ~30 seconds after logging this output string:
`Uploading to jleroux/9168faaec90f8d4ac935401e91b01f3f  54270852 / 54270852.0  (100.00%)`

**Expected result:**
CLI does not hang after uploading package to S3.

**Comment by jfuss** [comment]
This repo is centered around SAM, the code that transforms SAM Resources into CloudFormation. You are describing an issue with the aws cli. Please create an issue in there [repo](https://github.com/aws/aws-cli).

Closing since this issue is an aws cli issue not SAM.
