### ISSUE TITLE
Swagger DefinitionBody Error: map keys must be strings; received numeric [200] instead

### ISSUE THREAD

**Issue by wcharlesm** [awslabs/serverless-application-model#393]
**Description:**

Transformation to cloudformation template converts '200' to 200 causing an invalid template error.

Inside my serverless.template.yaml file the following is transformed into an invalid cloudformation segment.

responses:
  '200':
    description: "200 response"
    schema:
      $ref: "#/definitions/Empty"
    headers:
      Access-Control-Allow-Origin:
        type: "string"
      Access-Control-Allow-Methods:
        type: "string"
      Access-Control-Allow-Headers:
        type: "string"

becomes 

responses:
  200:  
    description: 200 response
    schema:
      $ref: '#/definitions/Empty'
    headers:
      Access-Control-Allow-Origin:
        type: string
      Access-Control-Allow-Methods:
        type: string
      Access-Control-Allow-Headers:
        type: string
**Steps to reproduce the issue:**

1. add the following Resource to SAM yaml template and try to deploy it using the sam cli:

RestApi:
  Type: AWS::Serverless::Api
  Properties:
    StageName: prod
    DefinitionBody:
      swagger: "2.0"
      info:
        version: "2018-04-18T18:37:10Z"
        title: "MyTitle"
      host: "${myurl}.execute-api.${region}.amazonaws.com"
      basePath: "/prod"
      schemes:
      - "https"
      paths:
        /:
          post:
            produces:
            - "application/json"
            responses:
              '200':
                description: "200 response"
                schema:
                  $ref: "#/definitions/Empty"
          options:
            consumes:
            - "application/json"
            produces:
            - "application/json"
            responses:
              '200':
                description: "200 response"
                schema:
                  $ref: "#/definitions/Empty"
                headers:
                  Access-Control-Allow-Origin:
                    type: "string"
                  Access-Control-Allow-Methods:
                    type: "string"
                  Access-Control-Allow-Headers:
                    type: "string"
      definitions:
        Empty:
          type: "object"
          title: "Empty Schema"

**Observed result:**

the generated cloudformation template creates a dictionary key of 200 for the responses object which causes the following error:

map keys must be strings; received numeric [200] instead

**Expected result:**
The dictionary key should stay the same in the generated template as it is in the source template.

**Comment by wcharlesm** [comment]
I realized this is an issue with the dotnet cli extensions I was using. I'm closing this issue.

**Comment by ksingh778** [comment]
I'm facing the same issue. Please let me know what did you do to resolve this.
