### ISSUE TITLE
Switch CodeUri for local and CI templates

### ISSUE THREAD

**Issue by desbo** [awslabs/serverless-application-model#404]
I'd like to use a string for `CodeUri` when invoking locally, and an S3 `Bucket` and `Key` during deployment.

According to [this comment](https://github.com/awslabs/serverless-application-model/issues/22#issuecomment-363966051) this can be achieved with a `Condition` and `Fn::If` – but when I try that, `sam local` behaves as though the file doesn't exist. 

Is it possible to alternate between `CodeUri`s in this way without using `sam package`?

**Comment by vnktsh** [comment]
Post what you have tried, what's the error and your template.yaml file and commands you invoked.

**Comment by brettstack** [comment]
This sounds like a SAM CLI issue. Please open an issue over there if you're still having this problem.
