### ISSUE TITLE
SAM - Lambda Invoke Permission for all Lambda functions for Authenticated Cognito Users

### ISSUE THREAD

**Issue by nirajvbhatt** [awslabs/serverless-application-model#410]
I want to create 3 sets of Lambda functions, DEV, QA and PROD. We are using Cognito authentication/authorization. I have 3 user/identity pools DEV, QA and PROD. I want to restrict users of these pools to their respective DEV,QA,PROD lambda functions. For example,  DEV identity pool authenticated users can execute only DEV lambda functions. QA identity pool authenticated users can only execute QA lambda functions. PROD identity pool authenticated users can only execute PROD lambda functions.
How can I do this? I am trying to use AWS:Lambda:Permission but it's giving error:
"InvokePermission" : {
     "Type" : "AWS::Lambda::Permission",
     "Properties" : {
         "Action" : "lambda:InvokeFunction",
         "FunctionName" :"!Ref ${Environment}*",
         "Principal"    : "arn:aws:cognito-identity:ap-southeast-2:071359012260:identitypool/ap-southeast-2:53791779-b414-40ec-ab29-bd8a755dbadd"
     }

**Comment by juniorclarke** [comment]
@nirajvbhatt  & @niraj-bpsoftware 
It sounds as if you are trying to use one AWS account for handling your DEV, QA, and PROD environments. I would strongly recommend that you do not go down this route as it will cause many problems (one of which you are seeing now).

It sounds like you are in a greenfield project and just getting started. If this assumption is true I would recommend that you use separate AWS accounts to logically separate your environments. This has the added benefits of providing an extra layer of security.

It may seem like more work initially but it will save you lots of headaches if you automate your CI/CD pipeline from the start.
