### ISSUE TITLE
Add MinimumCompressionSize setting for AWS::Serverless::Api

### ISSUE THREAD

**Issue by n3ziniuka5** [awslabs/serverless-application-model#419]
This setting is available for `AWS::ApiGateway::RestApi`. Would be very useful to have it for `AWS::Serverless::Api`

`AWS::ApiGateway::RestApi` docs - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html

**Comment by digioak** [comment]
Our API Gateway model https://github.com/awslabs/serverless-application-model/blob/a09929bcdd7cd6083d5c344ce5a64208a56bc4a6/samtranslator/model/apigateway.py doesn't support this attribute at the moment.  If you are comfortable with submitting a PR that adds support for this attribute, that would be great!  In the meantime, a workaround that you may already be doing is patching the generated swagger definition with this attribute added.

**Comment by keetonian** [comment]
Released!
