### ISSUE TITLE
Does SAM or CF support the Lambda DeadLetterConfig

### ISSUE THREAD

**Issue by gmetzker** [awslabs/serverless-application-model#42]
Recently Dead Letter Queues were introduced as part of Lambda.  [See here.](http://docs.aws.amazon.com/lambda/latest/dg/dlq.html).  

I'm wondering if these are supported by the ServerLess Application model.  Looking at the [documentation on CloudFormation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#d0e85789) it doesn't appear it's supported yet.

Is this something that can be added to SAM or CF?

**Comment by sanathkr** [comment]
Not yet. SAM will support Dead Letter Queues soon after CloudFormation does

**Comment by kylegalbraith** [comment]
Any update on this? Does SAM now supper DLQ config?

**Comment by sanathkr** [comment]
Not yet. We are still waiting for CloudFormation to support DLQ

**Comment by frehner** [comment]
CloudFormation now [supports specifying a DLQ](https://aws.amazon.com/about-aws/whats-new/2017/03/aws-cloudformation-supports-authoring-templates-with-code-references-and-amazon-vpc-peering/)

**Comment by sanathkr** [comment]
Yeah, we are working on adding SAM support for DLQ as well. Should be out soon

**Comment by gertjvr** [comment]
@sanathkr is there a roadmap or release schedule somewhere we can monitor?

**Comment by sanathkr** [comment]
SAM now supports DLQ property. Check the documentation here at https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
