### ISSUE TITLE
microservice-http-endpoint-python3 fails for GET without params

### ISSUE THREAD

**Issue by bedge** [awslabs/serverless-application-model#424]
The GET with empty param list was the real bug. 
The rest of this is a simplification to get up and running more easily.
Removed superfluous index.js as well, which was a duplicate from another example.

Would fail if you provided only the TableName param with a GET. Rearranged to allow no-param GET and moved table creation into template.yaml.

PR: https://github.com/awslabs/serverless-application-model/pull/415

**Comment by brettstack** [comment]
Fixed in #415
