### ISSUE TITLE
duplicated example

### ISSUE THREAD

**Issue by lonsdale8734** [awslabs/serverless-application-model#427]
https://github.com/awslabs/serverless-application-model/tree/develop/examples/apps/algorithmia
https://github.com/awslabs/serverless-application-model/tree/develop/examples/apps/api-gateway-authorizer-python

It seems like the two examples have the same files

**Comment by brettstack** [comment]
Thanks for calling this out. It's just that https://github.com/awslabs/serverless-application-model/tree/develop/examples/apps/api-gateway-authorizer-python should not include `package.json` or `index.js`. Want to send a PR?
