### ISSUE TITLE
Plans to integrate step-functions in this spec?

### ISSUE THREAD

**Issue by include** [awslabs/serverless-application-model#431]
Hi,

We are having lot's of joy working with SAM and sam-cli but... how about step-functions? Is there any plans to integrate them here? We would love to start mocking them up on sam-cli template.yaml.

PS: awesome work. thank you :)

Cheers,
Francisco

**Comment by jfuss** [comment]
Step Functions is now in the Spec for SAM: https://github.com/awslabs/serverless-application-model/releases/tag/v1.24.0 and https://aws.amazon.com/about-aws/whats-new/2020/05/aws-sam-adds-support-for-aws-step-functions/

Closing as Step Functions is now supported.
