### ISSUE TITLE
Inline DefinitionBody always returns "Specify either 'DefinitionUri' or 'DefinitionBody' property and not both"

### ISSUE THREAD

**Issue by yunspace** [awslabs/serverless-application-model#432]
**Description:**

Whenever `DefinitionBody` is used I seem to always get a validation error saying to `Specify either 'DefinitionUri' or 'DefinitionBody' property and not both`

I'm using aws cli 1.15.19 and sam cli 3.0

**Steps to reproduce the issue:**
1. Go to the example given in this repo: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/inline_swagger/template.yaml
2. Run `sam validate`

**Observed result:**
Get the following error:
`Error: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyApi] is invalid. Specify either 'DefinitionUri' or 'DefinitionBody' property and not both`

If I overhook this and try to deploy I still end up getting the same error.

**Expected result:**
Pass validation and can be deployed

**Comment by jfuss** [comment]
@yunspace The issue you are seeing is due to SAM CLI  not SAM. Please move this issue to https://github.com/awslabs/aws-sam-cli/issues

Closing since this is issue was created in the wrong repo.
