### ISSUE TITLE
Unable to set body mapping template for serverless function

### ISSUE THREAD

**Issue by ramanganapathy** [awslabs/serverless-application-model#440]
Description:In sam template for serverless function type unable to provide body mapping template definition when the lambda integration type is used

Events:
        GetEvent:
          Type: Api
          StageName: abc
          Properties:
            Path: /api/test-events
            Method: get

Observed result:

Expected result:

**Comment by keetonian** [comment]
Issue isn't very clear. SAM API events currently provide method definitions for the DefinitionBody of an API if no existing swagger is found by SAM.
