### ISSUE TITLE
A Full-Stack Example of AWS SAM

### ISSUE THREAD

**Issue by tbrunia** [awslabs/serverless-application-model#441]
Please consider incorporating [this full-stack example](https://github.com/xilution/xilution-react-todomvc) of the ubiquitous TodoMVC app using AWS SAM in your reference documentation. The project features a React frontend. The backend is provisioned with AWS SAM and features Webpacked Node.js Lambda functions. Both frontend and backend code is 100% unit test covered and is a great example of how to unit test serverless code.

Thanks for your consideration. Please let me know if you have any questions.

**Comment by jens1101** [comment]
I know that this issue is closed, but I agree with OP. I recently learned AWS SAM and I immediately wanted a full stack example. However, I was surprised that none was available. I think a full stack example would be very welcome and valuable.

**Comment by ShreyaGangishetty** [comment]
@tbrunia wrote a full stack example that he posted above: https://github.com/xilution/xilution-react-todomvc
Here is an another example for full stack in [realworld-serverless-application repository]( https://github.com/awslabs/realworld-serverless-application/wiki)
