### ISSUE TITLE
api_swagger_cors example fails with api event reference error

### ISSUE THREAD

**Issue by efultz** [awslabs/serverless-application-model#45]
Steps to reproduce:
- `cd serverless-application-model/examples/2016-10-31/api_swagger_cors`
- `aws cloudformation package --template-file template.yaml --output-template-file packaged_template.yaml --s3-bucket <bucketname>`
- `aws cloudformation deploy --template-file packaged_template.yaml --stack-name MySamSwagger --capabilities CAPABILITY_IAM`

The deploy step above produces the following output error:
```
Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [LambdaFunction] is invalid. Event with id [ProxyApiRoot] is invalid. RestApiId property of Api event must reference a valid resource in the same template.
```

I'm very confident that this bug was introduced after 2016-12-21T23:00:00Z, because I had a successful deployment around that time.

**Comment by sanathkr** [comment]
Yeah, this bug was introduced recently. As a workaround you can remove the !Ref and use `RestApiId: ApiGatewayId` directly. It should work. 

We will get it fixed soon

**Comment by sanathkr** [comment]
This should be fixed now. Can you check?

**Comment by efultz** [comment]
Yup, this bug is fixed. Thanks for being on top of it
