### ISSUE TITLE
Internal Transform Failure when using SQS as Serverless Function Event Source

### ISSUE THREAD

**Issue by nicklee1990** [awslabs/serverless-application-model#457]
**Description:**

I am trying to deploy an serverless function with SQS as the event source however I keep receiving an error message when attempting to deploy my template saying `Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.`. I've tried removing the event block from the template and it deploys fine so I've narrowed it down to the Event source definition.

I reattempted with the SQS template from the examples folder of this repo and faced the same issue. Is this feature supported yet? Also, what is this event source type setting up in the background so that I can replicate the functionality through ordinary CFN till this is resolved?

**Steps to reproduce the issue:**
1. Attempt to deploy the SQS example

**Observed result:**
Error message is received when attempting to run the deploy command
```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.
```

**Expected result:**
Stack is deployed successfully

**Comment by buggy** [comment]
> Is this feature supported yet?

I don't think SQS is a supported event source for Lambda. They announced it was coming but I haven't seen any announcement that it was now live.

**Comment by brettstack** [comment]
Sorry for the confusion. This has been merged to the develop branch of this
repo in preparation for the Lambda feature launch. I'll update the GitHub
settings to use master branch add default. Once you see this land in
master, you'll be able to use SQS as an event source.

**Comment by nicklee1990** [comment]
yep using develop as the default branch caught me out. thanks!
