### ISSUE TITLE
Deployment package size 

### ISSUE THREAD

**Issue by kurtmaile** [awslabs/serverless-application-model#458]
Hi,

Im using SAM with go.  My template contains multiple lambdas and each refers to their own binary in the code uri.  It seems each lambda functions indiviudal package contains ALL the binarys and is thus quite large and bloated with the other unused ones.

Is there a way to control this?  Serverless framework gives us options but cant see any for SAM.

Thanks

**Comment by brettstack** [comment]
This is an issue with AWS CLI. Please check for or open an issue there https://github.com/aws/aws-cli/
