### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by wjordan** [awslabs/serverless-application-model#46]
I'd like to request making the underlying implementation of the Serverless Application Model available under the same [LICENSE](https://github.com/awslabs/serverless-application-model/blob/master/LICENSE) that governs the specification distributed in this repository.

This would help users by giving them the ability to inspect the underlying implementation to help with debugging unexpected behavior and edge-cases. It would help the project by making it possible for external contributors interested in supporting and advancing this project to submit pull requests with bug and documentation fixes, new tests and feature implementations, etc.

**Comment by wjordan** [comment]
I've noticed that AWS has been representing this Serverless Application Model as having already been made available under the Apache license:

- [Introducing the AWS Serverless Application Model](https://aws.amazon.com/about-aws/whats-new/2016/11/introducing-the-aws-serverless-application-model/):

> As part of this release, the AWS Serverless Application Model is made available under the Apache 2.0 license, enabling others in the ecosystem to adopt and incorporate it into build, deployment, monitoring and management tools with a commercial-friendly license.

- [AWS Serverless Application Model (AWS SAM) Supports Inline Swagger and AWS CloudFormation Intrinsic Functions](https://aws.amazon.com/about-aws/whats-new/2017/02/aws-serverless-application-model-aws-sam-supports-inline-swagger-and-aws-cloudformation-intrinsic-functions/):

> It is available under Apache 2.0.

- [Using the AWS Serverless Application Model (AWS SAM)](http://docs.aws.amazon.com/lambda/latest/dg/deploying-lambda-apps.html#serverless_app):

> The specification is available under Apache 2.0 for AWS partners and customers to adopt and extend within their own toolsets. For details on the specification, see the AWS Serverless Application Model.

These descriptions obscure the fact that the source code of the underlying SAM service implementation is not available under Apache 2.0, only the syntax specification document and some example templates are. Without the underlying transformation code, an Apache-licensed specification document is no more practically useful to AWS customers than the "all rights reserved"-licensed documentation covering the underlying CloudFormation service- it is no easier to "adopt and extend" the SAM than CloudFormation or any other closed-source AWS service.

While I appreciate the bold efforts @sanathkr and others at AWS are making to engage external developers in productive collaboration and discussion through third-party services like GitHub, I'm disappointed this project has been representing itself as an open-source project in AWS announcements and documentation in a way that is rather misleading.

Please, open-source the actual implementation code behind this project and I'll be one of its most enthusiastic supporters and advocates. If this isn't possible, at the very least I hope you update the announcements/documentation referencing this project to clarify that only the specification and examples of the Serverless Application Model are currently open source, and not the actual transform implementation. Looking forward to any response, clarification or updates on this.

**Comment by sanathkr** [comment]
Hey @wjordan, thanks for issue. I agree that open sourcing underlying logic will complete the picture. We hear you and we want to make this happen. I can't promise on when, but we are definitely having that discussion internally. 

Even though SAM isn't "true open source" by your definition, our intention is to actively engage with the community and run this pretty much like any other open source project. So keep the enthusiasm and energy flowing.

**Comment by wjordan** [comment]
Just checking in, since it's been almost a year since I originally opened this request. Any updates on the discussion you're definitely having internally, or should I expect SAM to remain a proprietary implementation for another year?

**Comment by sanathkr** [comment]
Thank you Will for the request! We have officially open sourced the SAM translator implementation.

**Comment by wjordan** [comment]
Hooray! Congratulations on the big public release and thanks so much for making this happen!

**Comment by sanathkr** [comment]
You, and customers like you, made this happen Will 🎉
