### ISSUE TITLE
Configuring test events through SAM template

### ISSUE THREAD

**Issue by indrajra** [awslabs/serverless-application-model#475]
The specification https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md doesn't seem to list one for creating a default test-event for the lambda through SAM template. Am I missing something? 
I'd like to create a lambda function, attach a test-event and deploy it. Soon after, I want to invoke the lambda with its own default test-event as part of the sanity test suite - all through SAM. 

_Can't find the 'aws-sam' tag to post this is StackOverflow first; sorry!_

**Comment by torntrousers** [comment]
Would be a nice feature to have

**Comment by keetonian** [comment]
I think this is out of scope of what SAM can do. SAM can't set up a console test event, like Brett mentioned, but something similar to this could be set up in a CodePipeline workflow. For more information about CodePipeline, see the docs: https://docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html

**Comment by KeesCBakker** [comment]
Would really love it if this was added...
