### ISSUE TITLE
Single Lambda functions contain all binaries for all Lambdas in package

### ISSUE THREAD

**Issue by kurtmaile** [awslabs/serverless-application-model#481]
**Description:**

My lambda functions when deployed are bloated in size and contain other lambdas binaries from the same template.

My SAM template has 6 functions in it, and each lambda functions code when deployed appears to contain ALL the binaries as part of its package, not just the one that is of relevance for that particular function.  Thus the size of the code for a given lambda is 35MB not like 6MB.

Is this a bug or is there a way to control this in settings like the serverless framework does?  

Thanks
Kurt

**Comment by brettstack** [comment]
Is the source for all of the Lambda Functions in the same directory and are you printing to that directory in your SAM template? Pasting your directory structure and template fragment will help

**Comment by brettstack** [comment]
Packaging is not part of SAM. The `aws CloudFormation package` command logic exists in the AWS CLI.

**Comment by keetonian** [comment]
I would recommend having a different `CodeUri` path for each function, that way they are packaged separately and only contain the code relevant to that specific function. This will help with packaging speed as well as cold start times if your code package is unnecessarily large.

If all of your functions share a common library or set of libraries, you should also check out the new [Lambda Layers](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html) feature, which [SAM supports](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template.html#serverless-sam-template-layerversion).

**Comment by jimbo5644535** [comment]
yea, that is what I'm doing as every function is in a different folder inside the handler directory. Layers is not really on option for GoLang as packages are already backed in the compiled binary.

The only thing that kinda bothers me, is that it deploys every function, even if it wasn't updated. I only have 8 functions atm, but if you have hundreds it should slow down deployment significantly
