### ISSUE TITLE
CloudFormation output template getting UTF-8 BOM added

### ISSUE THREAD

**Issue by mattgillard** [awslabs/serverless-application-model#492]
**Description:**

For some reason my Input SAM template YAML had a UTF-8 BOM in it.  When the sam package command is executed, the UTF-8 BOM is duplicated in the output cloud formation template file which causes the sam deploy command to fail.

**Steps to reproduce the issue:**
1. Open any SAM template file and ensure encoding is set to UTF-8 BOM

```
$ od -x filename.yaml 
0000000 bbef 41bf 5357 6554 706d 616c 6574 6f46
<...>
```

2. Execute sam package:

`$ sam package ---template-file sam-template.yaml --output-template-file output.yaml --s3-bucket deployments`

3. Deploy processed sam template:

```
$ sam deploy --template-file output.yaml --stack-name myStack --capabilities CAPABILITY_IAM

Waiting for changeset to be created..
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Invalid template property or properties [???AWSTemplateFormatVersion]
```

3. A file without these codes at the beginning of the file work fine.
eg:
`0000000 5741 5453 6d65 6c70 7461 4665 726f 616d`

**Observed result:**

output.yaml has this at the end of the file and a sam deploy fails:

```
Transform: AWS::Serverless-2016-10-31
"\xEF\xBB\xBFAWSTemplateFormatVersion": '2010-09-09'
```

**Expected result:**

That last line in output.yaml should not be there and the UTF-8 BOM should have been stripped.

Not a huge deal as I changed the file type :-)  But would be nice to just strip it during processing? I did lose some time trying to figure out what happened!

**Comment by jasonycw** [comment]
It will be great if SAM can read all UTF8 encoding .yaml files and package with it properly, pretty annoying have to remember changing encoding to UTF8

**Comment by jasonycw** [comment]
I think maybe the IDE default file encoding is UTF8-BOM?
I was using Visual Studio 2017 (we are using .NET Core 2.1 Lambda) to create an empty text file and rename it to _______.yaml
We now just use powershell script to change it to UTF8 before running `sam package`

Not sure what  @mattgillard was using to generate the .yaml file

**Comment by mattgillard** [comment]
Sorry for late reply...yeah it was vscode

**Comment by keetonian** [comment]
Not being able to read a UTF-8 BOM is an issue with cloudformation, as it seems that this would be an issue even with the original template before `sam package` is run. Closing issue as SAM can't address this issue.

**Comment by jasonycw** [comment]
But I think SAM can at least help translate the template to UTF-8 before
sending to CloudFormation

Keeton Hodgson <notifications@github.com> 於 2019年1月19日 週六 上午2:30寫道：

**Comment by keetonian** [comment]
That would be good; for now, though, the SAM CLI `sam package` command shells out to the `aws cloudformation package` command to package templates to s3.

**Comment by ermiaswalelgne** [comment]
As part of a solution, I use Notepad++ to convert it to non-BOM UTF-8.
Go to `Encoding > UTF-`8  and save the file [ [src](https://stackoverflow.com/questions/18664712/split-function-add-xef-xbb-xbf-n-to-my-list) ]
