### ISSUE TITLE
Add dynamodb:DescribeTable to DynamoDBCrudPolicy

### ISSUE THREAD

**Issue by sliedig** [awslabs/serverless-application-model#509]
**Description:**

Have a template for .NET Core 2.1 function with DynamoDBCrudPolicy.

```json
    ResolveIncidentFunction:
        Type: AWS::Serverless::Function
        Properties:
            Description: DevelopingWithStepFunctions - Marks the  incident as resolved.
            CodeUri: ./artifacts/ResolveIncidentTask.zip
            Handler: ResolveIncidentTask::ResolveIncidentTask.Function::FunctionHandler
            Policies:
            - DynamoDBCrudPolicy:
                TableName: !Ref IncidentsTable
``` 

Function raises exception when trying to invoke `PutItemAsync` operation.

> arn:function... is not authorized to perform: dynamodb:DescribeTable on resource: arn:table...

Adding action to new custom policy resolves the issue. 

Can we please add to action to the DynamoDBCrudPolicy?

**Comment by brettstack** [comment]
Could you submit a PR?

**Comment by turjachaudhuri** [comment]
Any idea when this will be merged into the master branch . I faced the same issue , and for now , I have to manually add the policy from IAM to get it working after my app is deployed from the serverless app repository?
Thanks in advance.

**Comment by keetonian** [comment]
@turjachaudhuri @sliedig This feature has now been released and is available for use
