### ISSUE TITLE
Serverless.Template Json File In Visual Studio Serverless Application Template (.Net Core)

### ISSUE THREAD

**Issue by markchilton** [awslabs/serverless-application-model#510]
When an AWS Serverless Application solution is created in visual studio the traditional template.yaml is replaced with a json template called serverless.template.

The Globals tag can be added inside the Parameters tag or the Resources tag, however, none of it's children are accessible. For example;

```
  "AWSTemplateFormatVersion" : "2010-09-09",
  "Transform" : "AWS::Serverless-2016-10-31",
  "Description" : "An AWS Serverless Application that uses the ASP.NET Core framework running in Amazon Lambda.",
  "Parameters" : {
    "ShouldCreateBucket" : {
      "Type" : "String",        
      "AllowedValues" : ["true", "false"],
      "Description" : "If true then the S3 bucket that will be proxied will be created with the CloudFormation stack."
    },  
    "BucketName" : {
        "Type" : "String",
        "Description" : "Name of S3 bucket that will be proxied. If left blank a new table will be created.",
        "MinLength" : "0"
    },
	"Globals" : {
		"Api" : {
			"Cors" : {
			}
		}
	}
  },
```
And

```
  "Resources" : {
	"Globals" : {
		"Api" : {
			"Cors" : {
			}
		}
	},
}
```
The Api tag is not accessible. Am I placing the Global tag in the correct place or is it not supported in this kind of project?

**Comment by brettstack** [comment]
I'm not familiar with the Visual Studio Template (could you share a link?) But the `Globals` key should be specified as a top-level entry; i.e. on the same level as `Parameters` and `Resources` not as a child of them.

**Comment by markchilton** [comment]
Sure - Here is the link https://aws.amazon.com/blogs/developer/aws-serverless-applications-in-visual-studio/

Globals isn't working at top level so I assume it just isn't supported in this kind of file.

**Comment by niraj-bpsoftware** [comment]
Hi @markchilton ,
Globals section should be different than Parameters or Resources. Just put it as a separate section like Resources. It should work, even though Visual studio will intellisense flag it as an invalid key.
