### ISSUE TITLE
Add accessLogSettings configuration to AWS::Serverless:Api

### ISSUE THREAD

**Issue by kberger** [awslabs/serverless-application-model#516]
Access logs allow API owners to log who and how requests are being made with custom log format that can be used to support feeding the access logs to another analytics engine.

https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html
https://docs.aws.amazon.com/apigateway/api-reference/resource/stage/#accessLogSettings

**Comment by brettstack** [comment]
I've tagged this as a feature request. If you want to have a go at implementing this yourself, I could point you in the right direction. Otherwise we'll prioritize this against other features.
