### ISSUE TITLE
Code pipline fails: ChangeSetNotFound; Request ID: d0519f50-c952-11e6-90c7-533dc3f576eb)

### ISSUE THREAD

**Issue by avizaviz** [awslabs/serverless-application-model#52]
Hi,
My serverless pipline fails due to the following error in the execution phase.
Error:
> Action execution failed
> ChangeSet [ProdChangeSet] does not exist (Service: AmazonCloudFormation; Status Code: 404; Error Code: ChangeSetNotFound; Request ID: d0519f50-c952-11e6-90c7-533dc3f576eb)

Looks like I need to create a changeset in cloudformation service but in the cloud formation under changeset I see the following message

> There are no executable change sets. Your stack must be in an updatable state to use change sets.

**Comment by vikrambhatt** [comment]
Hi,

Can you please describe your setup and post your yaml template? 

When 'aws cloudformation deploy' is invoked, it should create a change set and then execute it to update the stack - you don't need to create a stack or a change set manually.

**Comment by sanathkr** [comment]
Also, if you had updated your stack out-of-band after your changeset was created, you will get this error. When you update a stack, all previously created changesets will be invalidated

**Comment by avizaviz** [comment]
Thanks

**Comment by jfuss** [comment]
Looks like @sanathkr answered the question here. Closing
