### ISSUE TITLE
CodeUri gives a different output depending on if it's declared in Globals or not

### ISSUE THREAD

**Issue by divillysausages** [awslabs/serverless-application-model#537]
**Description:**

I'm creating a serverless application by defining a number of functions. It's based on the example generated when running `sam init`.

The layout is like so:

    src/
        node_modules/
        package.json
        index.js
    template.yaml

As the `CodeUri` is the same for all functions, I declared it in the `Globals` section as declared here: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#supported-resources

The template yaml has the format

	AWSTemplateFormatVersion: '2010-09-09'
	Transform: AWS::Serverless-2016-10-31
	Description: Simple backend
		
	Globals:
		Function:
			Runtime: nodejs8.10
			Timeout: 10
			CodeUri: src/

	Resources:

		SimpleFunction:
			Type: AWS::Serverless::Function
			Properties:
				Handler: index.simple_func_handler
				Events:
					Version:
						Type: Api
						Properties:
							Path: /func	
							Method: get

	Outputs:

		ApiURL:
		Description: "API Gateway endpoint URL"
		Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

However, when SAM builds the file using

    sam package \
        --template-file ./template.yaml \
        --output-template-file ./prod.yaml \
        --s3-bucket my.bucket.url

If you download and unzip the file, the format is

    src/
        node_modules/
        package.json
        index.js

And when you try to deploy and execute, it fails because it can't import `index`.

If you remove `CodeUri` from `Globals` and move it to the `Function`, so your yaml looks like this

    ...
	Globals:
		Function:
			Runtime: nodejs8.10
			Timeout: 10

	Resources:

		SimpleFunction:
			Type: AWS::Serverless::Function
			Properties:
				Handler: index.simple_func_handler
				CodeUri: src/
    ...

The packaged zip has the correct flat file structure of

    node_modules/
    package.json
    index.js

I assumed that items declared in `Globals` would be inherited down the chain (aside from some, such as `Role`). Am I misunderstanding this?

**Steps to reproduce the issue:**

1. Declare the `CodeUri` in `Globals` and package the zip
2. Declare the `CodeUri` in each `Function` and package the zip
3. The generated zips aren't the same

**Observed result:**

When `CodeUri` is in `Globals`, the packaged zip doesn't have a flat structure

**Expected result:**

The packaged zip should have a flat structure, and the result should mimic declaring the `CodeUri` in each `Function`

Thanks

**Comment by tjbaker** [comment]
I've observed the same behavior.

**Comment by brettstack** [comment]
Docs have been updated
