### ISSUE TITLE
Permissions set up incorrectly if path parameter in CloudFormation Lambda api event and api Swagger definition have different names

### ISSUE THREAD

**Issue by otto-urpelainen-enoro** [awslabs/serverless-application-model#540]
**Description:**

Lambda function defined as _AWS::Serverless::Function_ with an event of type _Api_ and a path parameter needlessly requires that the path parameter has the exact same name in Api Gateway definition. If the path parameter names are not identical, calls to Api Gateway result in the following error: _"Execution failed due to configuration error: Invalid permissions on Lambda function"_. SAM should be able to match the two parameter through their identical position in the path and setup permissions correctly, like it does for api events that do not use path parameters and for cases where the path parameters have the same name in both places.

This issue was discovered in a setup where CloudFormation scripts always use _{identifier}_ as path parameter name, so that retrieving the parameters could be done identically for multiple different api calls, while api definition use descriptive names in order to more clearly describe the purpose of the api.

**Steps to reproduce the issue:**
1. Define an _AWS::Serverless::API_ using a Swagger file that contains a call with path parameter called _{identifier}_
2. Define an _AWS::Serverless::Function_ that has an _Event_ with _Type: Api_ and _Path: {another_identifier}_ and couple it to api of previous step with _RestApiId_ parameter.
2. Deploy the application
3. Invoke the call defined in the first step 1.

**Observed result:**
Error message _"Execution failed due to configuration error: Invalid permissions on Lambda function"_ is returned.

**Expected result:**
SAM and CloudFormation setup policy that allows Api Gateway to Invoke lambda. Api call is executed successfully.

**Workaround:**
Define function policy separately, e.g.
```
  ApiPermissions:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - ExampleLambda
      - ExampleApiGateway
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ExampleLambda.Arn
      Principal: apigateway.amazonaws.com
```

**Example files:**

Swagger Test.yml:
```
---
swagger: '2.0'
x-amazon-apigateway-policy:
  Version: "2012-10-17"
  Statement:
    - Effect: "Allow"
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/v1/*
info:
  title: Http Method Value Test
  version: 0.0.3
  description: Testing aws Serverless Application Model
host: api.example.com
basePath: /v1
schemes:
  - https
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
security:
  - bearerAuth: []
paths:
  /{identifier}:
    get:
      summary: GET in parameterized path
      description: GET in parameterized path
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/identifier'
      x-amazon-apigateway-integration:
        httpMethod: post
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HttpMethodValueTestLambda.Arn}/invocations
      responses:
        200:
          $ref: '#/responses/standardResponse'
parameters:
  path_parameter:
    name: identifier
    in: path
    type: string
    required: true
    description: Test path parameter
responses:
  standardResponse:
    description: Standard test response
    schema:
      properties:
        status:
          $ref: '#/definitions/status'
definitions:
  status:
    type: string
    description: Test call result status
    enum:
      - success
      - failed
      - partial
```

CloudFormation:
```
---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: dotnetcore2.1
    Timeout: 60

Resources:
  HttpMethodValueTestLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./publish
      Handler: Test::Test.Rest.LambdaHandler::ApiGatewayHandler
      Role: arn:aws:iam::206640028901:role/services/lambda/TestProcessQueueExecutionRole
      Events:
        GetById:
          Type: Api
          Properties:
            Path: /{another_identifier}
            Method: GET
            RestApiId: !Ref HttpMethodValueTestApiGateway
  FunctionSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "HttpMethodValueTest - Lambda Function SG"
      VpcId: !ImportValue 'Dev-VPCId'
  HttpMethodValueTestApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub >-
              s3://test/test/Test.yml
      StageName: v1
```

**Comment by brettstack** [comment]
Closing this in favor of #110. I recommend watching that issue for updates.
