### ISSUE TITLE
add ' private ' value in the doc for EndpointConfiguration in serverless api

### ISSUE THREAD

**Issue by pabloperfer** [awslabs/serverless-application-model#544]
for serverless api resource , please add in the doc that " private " is also a vaue supported to:

Current doc:
SAM support for creating Private API 
EndpointConfiguration	string	Specify the type of endpoint for API endpoint. Value is either REGIONAL or EDGE.

**Comment by keetonian** [comment]
This is correct according to the AWS docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html

Thank you for bringing this up!

**Comment by brettstack** [comment]
@pabloperfer care to make a PR? 🙏

**Comment by keetonian** [comment]
This is going out in our next release: 1.7.0. Closing issue.
