### ISSUE TITLE
Add Debugging Guide

### ISSUE THREAD

**Issue by sanathkr** [awslabs/serverless-application-model#55]
People [often ask](https://github.com/awslabs/serverless-application-model/issues/20#issuecomment-270496029) about how to debug SAM templates. Add a DEBUGGING guide them through

**Comment by collinforrester** [comment]
What are you looking for?

I went through #20 and found your reference to `aws cloudformation create-change-set` and I plan on adding an `npm test` command to help validate changes.

**Comment by sanathkr** [comment]
Closing it for now in favor of a docs revamp that's happening. See #251
