### ISSUE TITLE
Impossible to connect error for `SecretsManagerRDSOracleRotationSingleUser` serverless application

### ISSUE THREAD

**Issue by jagu-sayan** [awslabs/serverless-application-model#558]
Hello :)
Maybe it's not the good place to report this bug, but I don't find the right place :/

**Description:**

When I try to rotate my mysql aurora credentials with [SecretsManagerRDSOracleRotationSingleUser](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_template_MySql_SingleUser.html) serverless application. If user used to connect to the database require ssl, I always have this error : `setSecret: Unable to log into database with previous, current, or pending secret of secret `

It's because the python library user to connect to the database is not configured to support ssl by default :
```python
    # Try to obtain a connection to the db
    try:
        conn = pymysql.connect(secret_dict['host'], user=secret_dict['username'], passwd=secret_dict['password'], port=port, db=dbname, connect_timeout=5)
        return conn
    except pymysql.OperationalError:
        return None
```

**Steps to reproduce the issue:**
1. Create an aurora database with `admin` user
2. Make use of ssl mandatory with this SQL command : `GRANT USAGE ON *.* TO 'admin'@'%' REQUIRE SSL`
3. Try to rotate mysql aurora credentials with [SecretsManagerRDSOracleRotationSingleUser](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:297356227824:applications~SecretsManagerRDSOracleRotationSingleUser) Serverless application

**Observed result:**
Connection error to aurora mysql

**Expected result:**
Successful secret rotation for aurora mysql

**Comment by jlhood** [comment]
The [docs page](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_template_MySql_SingleUser.html) you linked has a link at the bottom: [Have a question? Try the Forums.](http://forums.aws.amazon.com/forum.jspa?forumID=296).

That link takes you to the forum for Secrets Manager. You can ask your question there to get support with your issue.
