### ISSUE TITLE
APIGateway not created with Event type Api

### ISSUE THREAD

**Issue by jamesthomasdavidson** [awslabs/serverless-application-model#559]
**Description:**

Event Type ```Api``` does not create API

**Steps to reproduce the issue:**
1. ```sam init```
2. ```sam package \
    --template-file template.yml \
    --s3-bucket mybucket \
    --output-template-file exported-template.yaml```
3. view ```exported-template.yaml``` (and there is no API Gateway)

I am trying to do this on a project I am working on.  However, I am not having any luck.  Upon trying the init sam sample project, I still am faced with the same problem

**Comment by brettstack** [comment]
Hi @jamesthomasdavidson, sorry for the confusion but I think this belongs over in this repo https://github.com/awslabs/aws-sam-cli.
