### ISSUE TITLE
Live logging of stack creation process?

### ISSUE THREAD

**Issue by dinvlad** [awslabs/serverless-application-model#56]
Hi team,

I'm not sure if this question belongs here, but would it be possible to enable _colorized_ logging of stack creation messages via the CLI _while_ running `aws cloudformation deploy ...`? I know we can retrieve them after the fact using `aws cloudformation describe-stack-events ...`, but it would be nice to match similar functionality from the Serverless framework. Currently, I find myself opening a separate browser tab to watch progress of stack formation, even though the short summary of the progress is already being output in the CLI:

> Waiting for changeset to be created..
> Waiting for stack create/update to complete
>
> Failed to create/update the stack. Run the following command
> to fetch the list of events leading up to the failure
> aws cloudformation describe-stack-events --stack-name _stack-name_

These messages don't tell us much, and ask us to perform a separate action even though they could just do so themselves. Since stack rollback usually takes a while, I'd prefer to notice any error messages _in color_ (e.g. red) and _as they appear_, and start fixing them right away, instead of waiting for the console to return with the generic message (or relying on a separate tab just for that).

Thanks

**Comment by joekiller** [comment]
I think this feature should be requested here: https://github.com/aws/aws-cli/issues

**Comment by sanathkr** [comment]
I don't know if the AWSCLI supports colored outputs. But it might be good to add a `--watch` flag that prints recent status from describe-stack-events. 

You should file the issue with AWSCLI. As always, PRs appreciated :-)

**Comment by dinvlad** [comment]
Sounds good, I'll try to suggest it there. In the meantime, I've actually automated SAM stack creation through CodePipeline, and deal with any issues through the Console. So having CLI output will only be useful during development.
