### ISSUE TITLE
Link to the website from README

### ISSUE THREAD

**Issue by 0xdevalias** [awslabs/serverless-application-model#564]
Currently the README references the spec, but not the (in progress) documentation website, making it hard to remember where/how to find it. It would be good if we could link to https://awslabs.github.io/serverless-application-model/index.html from the README and/or the repository 'web url' field.

**Comment by brettstack** [comment]
Thanks for the suggestion. We want to improve our docs before we link to them but will be sure to do so once they're ready! 👍
