### ISSUE TITLE
devPost Hackaton - RekognitionFacesManagementPolicy Request

### ISSUE THREAD

**Issue by HCans** [awslabs/serverless-application-model#590]
Hello!
I am submitting the following pull request in order to add a new Policy Template:
https://github.com/awslabs/serverless-application-model/pull/589

I need it in order to manage faces from my AWS Rekognition collection. In specific, I would like to also be able to delete faces from the collection.

Thanks!

**Description:**

**Steps to reproduce the issue:**
1.
2.
3.

**Observed result:**

**Expected result:**

**Comment by keetonian** [comment]
Thank you for posting this an opening https://github.com/awslabs/serverless-application-model/pull/589! We are reviewing your policy template submission.

**Comment by HCans** [comment]
Hello. Any plans of adding this to a release?

**Comment by keetonian** [comment]
Yes, this is staged in the 1.8.0 release, and should be available soon.
