### ISSUE TITLE
conditionally require enum34

### ISSUE THREAD

**Issue by avatarworf** [awslabs/serverless-application-model#591]
https://github.com/awslabs/serverless-application-model/blob/e8f74f56d19af0b5d0e3e534137a7a875f7d1f7a/requirements/base.txt#L2

In Python36 you don't need enum34 install
enum34~=1.1

Perhaps 
enum34~=1.1;python_version<"3.4"

**Comment by keetonian** [comment]
Hi! Thank you for posting this! It was just barely fixed on develop in https://github.com/awslabs/serverless-application-model/pull/582 and will be released to master in our next release.
