### ISSUE TITLE
How to write  synchronous lambda function invocation from api gateway ?

### ISSUE THREAD

**Issue by pravin-d** [awslabs/serverless-application-model#598]
Is it possible ? If so there seems to be not samples for the same.

**Comment by jlhood** [comment]
Yes it's possible. API Gateway's Lambda integration only supports synchronous Lambda function invokes. Here's [an example](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_backend/template.yaml) of using SAM to create a serverless API using API Gateway and Lambda.

See the [API Gateway documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-with-lambda-integration.html) for more details about API Gateway's Lambda integration support, but using SAM greatly simplifies this integration.
