### ISSUE TITLE
Link on Serverless Repo Page

### ISSUE THREAD

**Issue by dougepsotic** [awslabs/serverless-application-model#599]
On the Serverless Repository page for this sample
https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:077246666028:applications~microservice-http-endpoint

the link points to the Python sample, not this Node.js one

**Comment by brettstack** [comment]
Thanks for the report @dougepsotic. I've created an internal ticket and we'll get this fixed.

**Comment by shwetaskatdare** [comment]
Thank for the report. This has been fixed.
