### ISSUE TITLE
Support storing parameters in SSM Parameter Store

### ISSUE THREAD

**Issue by RobRoseKnows** [awslabs/serverless-application-model#603]
Currently there's no policy templates that support the `ssm:GetParameter` permission required to do stuff like [store secret parameters](https://aws.amazon.com/blogs/mt/use-parameter-store-to-securely-access-secrets-and-config-data-in-aws-codedeploy/). There's examples of storing secrets in [some of the examples](https://github.com/awslabs/serverless-application-model/blob/master/examples/apps/cloudwatch-alarm-to-slack/index.js), but it just uses KMS. This is mentioned in #48 after it was closed, but it uses inline policies not supported by the SAR.

I'm not sure if this is an extremely desirable feature but since it's unlikely it could be released before the end of the Devpost hackathon, I wouldn't mind doing this as a Hacktoberfest PR.

**Comment by brettstack** [comment]
This sounds like a useful Policy Template and we'd appreciate the PR.

**Comment by keetonian** [comment]
Released!
