### ISSUE TITLE
No link to docs

### ISSUE THREAD

**Issue by adamchainz** [awslabs/serverless-application-model#607]
**Description:**

Searched everywhere on PyPI page and GitHub README and couldn't see an obvious link to the rendered docs, I had to google to find https://awslabs.github.io/serverless-application-model/

**Steps to reproduce the issue:**

Above

**Observed result:**

Above

**Expected result:**

Should be able to hop from README straight to the docs, rather than just the partial documentation in the example markdown files

**Comment by brettstack** [comment]
Thanks for raising this. We're currently making improvements to our docs and will link to them when complete.
