### ISSUE TITLE
Rendering on PyPI is broken

### ISSUE THREAD

**Issue by adamchainz** [awslabs/serverless-application-model#609]
**Description:**
Rendering of the README on PyPI is broken because it expects RST by default and Markdown is being uploaded.

**Steps to reproduce the issue:**

1. Go to https://pypi.org/project/aws-sam-translator/

**Observed result:**

Raw markdown

**Expected result:**

Links and images working

**Comment by keetonian** [comment]
Thank you for your contribution! This will go out with our 1.8.0 release.
