### ISSUE TITLE
Add support for CFN APIGW changes from Sept. 2018

### ISSUE THREAD

**Issue by keetonian** [awslabs/serverless-application-model#612]
**Description:**

CFN [recently announced](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html) additional support for some APIGW resources. We need to add support in SAM for these new changes. Also see the [forums](https://forums.aws.amazon.com/ann.jspa?annID=6144) for information about the recent update.

In particular, we would like to add the (new) fields `AccessLogSetting` and `CanarySetting` to [`AWS::ApiGateway::Stage`](https://github.com/awslabs/serverless-application-model/blob/a2c69540ee93a673d03fa75bf7be4e4c75b80868/samtranslator/model/apigateway.py#L26) ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html)) inside of SAM as well as decide if any of the other new features should be supported by SAM.

**Comment by tomassommar** [comment]
+1

**Comment by keetonian** [comment]
Released!
