### ISSUE TITLE
S3ReadPolicy for all buckets not working

### ISSUE THREAD

**Issue by Kitemaker** [awslabs/serverless-application-model#616]
**Description:**

I am trying to give read permission to the function in template as following but it throws error
 {
	"S3ReadPolicy": {
		"BucketName": "*"
		}
}

**Steps to reproduce the issue:**
1. Assign policy to function PublishSNSTopicForS3 using the code below
 {
	"S3ReadPolicy": {
            "BucketName": "*"
			}
}
2. When template is loaded to publish application on SAM console error is thrown

Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [PublishSNSTopicForS3] is invalid. 'S3ReadPolicy' policy template contains unsupported value for a parameter 'Bucket'.
3.

**Observed result:**
error when button 'publish version is clicked on SAM console
full code is following for the function:
 "PublishSNSTopicForS3": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "SNS_Image_Labels_Rekognition_S3.lambda_handler",
        "Runtime": "python3.6",
        "CodeUri": "s3://sjalexaskillsvirginea/Code/SNS_Image_Labels_Rekognition_S3.zip",
        "Environment": {
          "Variables": {
            "TOPIC_ARN": { "Fn::GetAtt" : [ "SNSTopic", "TopicName" ] }			
          }
        },
        "MemorySize": 128,
        "Timeout": 5,
        "Policies": [
          {
            "SNSPublishMessagePolicy": {
              "TopicName": { "Fn::GetAtt" : [ "SNSTopic", "TopicName" ] }
            }
          },
          {
            "SNSCrudPolicy": {
              "TopicName": { "Fn::GetAtt" : [ "SNSTopic", "TopicName" ] }
            }
          },
		  {
			"S3ReadPolicy": {
			"BucketName": "*"
			}
		  }
        ],
        "Events": {
          "S3BucketEvent": {
            "Type": "S3",
            "Properties": {
              "Bucket": {"Ref":"S3Bucket"},
              "Events": [
                "s3:ObjectCreated:*"                
              ]
            }
          }
        }
      }
    }    

**Expected result:**
application should be published

**Comment by keetonian** [comment]
Hi! Wildcard (*) values for policy templates are not accepted by design for publishing applications to the Serverless Application Repository. You can use wildcards in your own SAM templates, but, for security reasons, we do not allow wildcard permissions to be published to the repository. Is there a reason why you would like to use a (*) instead of scoping your function to a specific bucket?

**Comment by Kitemaker** [comment]
Thanks for clarification. Actually I am trying to get S3ReadPolicy  for the bucket I created in the template . But it does not work and throws error , I use the following code:

{"PublishSNSTopicForS3": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "Rekognition_S3.lambda_handler",
        "Runtime": "python3.6",
        "CodeUri": "Rekognition_S3.zip"      
        },      
        "Policies": [          
		  {
			"S3ReadPolicy":{
			"BucketName": { "Reft" : "S3Bucket" }
		}
		}		
		],		       
        "Events": {
          "S3BucketEvent": {
            "Type": "S3",
            "Properties": {
              "Bucket": {"Ref": "S3Bucket"},
              "Events": [
                "s3:ObjectCreated:*"                
              ]
            }
          }
        }
      }	,
	"S3Bucket": {
      "Type": "AWS::S3::Bucket"		
    }
}

but I am getting Circular dependency error:  

SAM template is invalid. It cannot be deployed using AWS CloudFormation due to the following validation error: Circular dependency between resources: [S3Bucket, PublishSNSTopicForS3S3BucketEventPermission, PublishSNSTopicForS3Role, PublishSNSTopicForS3]
Is there any other way to give read access  for the bucket created.  
Regards
