### ISSUE TITLE
Add simplified 'auth' (Cognito) support

### ISSUE THREAD

**Issue by 0xdevalias** [awslabs/serverless-application-model#617]
**Description:**

It would be nice to include a 'simplified' cogito-based authentication setup, for example, implicitly creating any required roles/permissions to support email/SMS/similar.

This can currently be manually worked around using CloudFormation directly, or with other projects such as [Amplify](https://aws-amplify.github.io/amplify-js/media/authentication_guide), but it would be nice to be able to use SAM directly for this.

**Comment by brettstack** [comment]
We'll be launching this real soon. The pull request has been merged into a release branch and we're performing the final stages of our release now https://github.com/awslabs/serverless-application-model/pull/546

**Comment by brettstack** [comment]
No, though we may add support for local Dev over on the SAM CLI side eventually.

**Comment by oleersoy** [comment]
Sweet - [I have a request for that here ](https://github.com/awslabs/aws-sam-cli/issues/697).

**Comment by annjawn** [comment]
Any news on Cognito support yet?

**Comment by brettstack** [comment]
This is already available https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/api_cognito_auth

**Comment by annjawn** [comment]
Thanks @brettstack, yes I noticed that later.

**Comment by jhechtf** [comment]
> This is already available https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/api_cognito_auth

I don't see anything on that link; how would I get this to work locally? I really don't enjoy having to continuously build and deploy every time im trying to test something.
