### ISSUE TITLE
Add path support in custom domain

### ISSUE THREAD

**Issue by mburket** [awslabs/serverless-application-model#619]
**Description:**

Currently, the custom domain name in the API gateway only maps the API stages.  This is requesting support to map the API path in custom domain name so the path can be hidden from end users.  Not sure if this is an issue for SAM or API gateway.

**Comment by brettstack** [comment]
Could you provide the current syntax you're using as well as the syntax you want to use and the resulting output?

**Comment by mburket** [comment]
For example, if an API uses `/member` as path.  If I create a custom domain name of `api.example.com/member`, the current API URL becomes `api.example.com/member/member`. You can see `member` is duplicated.  The URL I want to see is `api.example.com/member` without the duplication of the path.  Thank you.

**Comment by brettstack** [comment]
You should be able to achieve this with https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-basepathmapping.html.
