### ISSUE TITLE
API Gateway Forgets Gateway Responses

### ISSUE THREAD

**Issue by chrisoverzero** [awslabs/serverless-application-model#623]
**Description:**

When defining an "AWS::Serverless::API", associating an "AWS::ApiGateway::GatewayResponse" with the API is forgotten after the initial deployment.

**Steps to reproduce the issue:**
1. Define a SAM API with an endpoint protected by a Lambda Authorizer. (Because "Auth" isn't available yet, use "securityDefinitions" in Swagger.)
2. Include a resource of type "AWS::ApiGateway::GatewayResponse" associated with the API. For example:

```json
"UnauthorizedResponse": {
  "Type": "AWS::ApiGateway::GatewayResponse",
  "Properties": {
    "ResponseParameters": {
      "gatewayresponse.header.Access-Control-Expose-Headers": "'WWW-Authenticate,Link'",
      "gatewayresponse.header.Access-Control-Allow-Origin": "'*'",
      "gatewayresponse.header.Link": "'<Some valid header>'",
      "gatewayresponse.header.WWW-Authenticate": "'<some valid header>'"
    },
    "ResponseType": "UNAUTHORIZED",
    "RestApiId": { "Ref": "Api" },
    "StatusCode": "401"
  }
}
```

(`DependsOn` is optional, it fails with or without.)

3. Deploy the API.
4. Contact the protected endpoint, and note the response headers.
5. Update the code for the protected endpoint and redeploy.
6. Contact the protected endpoint, and note the response headers.

**Observed result:**

401 response lacks the specified headers. Oddly, the AWS console nevertheless reports the Gateway Response as customized and associated with the API.

**Expected result:**

401 response contains the specified headers.

This was once brought up in #390, but the reporter there found a workaround of defining the Gateway Responses in Swagger. Now that the "Default Definition Body" feature exists, this workaround is detrimental.

**Comment by brettstack** [comment]
We plan on adding a new feature which will be useful in conjunction with the recently released default definition body on explicit APIs feature. This feature will allow you to specify Swagger that gets merged into the default swagger generated for you by SAM, allowing you to easily patch things like this without having to rewrite your entire Swagger by hand.

Until then, you have several options:

1. Grab the generated swagger from your transformed template (check the CloudFormation console) and copy/paste it into your template. Modify with necessary Gateway Responses.
1. Create a CloudFormation Macro which takes a JSON fragment and merges it into the transformed output of SAM (similar to what I described above). Bonus points if you submit this as a Serverless App http://serverlessrepo.aws.amazon.com/applications
1. Send a PR for the feature I described 🙌

**Comment by chrisoverzero** [comment]
>Grab the generated swagger from your transformed template (check the CloudFormation console) and copy/paste it into your template. Modify with necessary Gateway Responses.

Because the SAM nouns for Auth aren't available yet, we are already doing effectively this. 👍

>Until then, you have several options:

All of these things sound great. But it doesn't sound as though any of them will fix "AWS::ApiGateway::GatewayResponse". Is this _intended_ to be broken/unsupported? It's confusing to me that it will work on the initial deployment, then silently fail to take effect thereafter.

**Comment by brettstack** [comment]
I assume what's happening is, the first time it creates the API using the Swagger and then creates the GatewayResponse resource and applies that. Then, on update, it sees the Swagger has changed and applies that which overrides everything else. Since there were no changes to the GatewayResponse resource, it doesn't then get reapplied.

**Comment by brettstack** [comment]
Does API Gateway support defining GatewayResponse in Swagger? If so, you will be able to specify it there. If not, we'll need to put in a feature request.

**Comment by brettstack** [comment]
Looks like it supports it: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-gateway-responses.html

**Comment by chrisoverzero** [comment]
>Looks like it supports it:

Yes, that's what we're writing as the workaround:

```json
"x-amazon-apigateway-gateway-responses": {
  "UNAUTHORIZED": {
    "statusCode": 401,
    "responseParameters": {
      "gatewayresponse.header.Access-Control-Expose-Headers": "'WWW-Authenticate,Link'",
      "gatewayresponse.header.Access-Control-Allow-Origin": "'*'",
      "gatewayresponse.header.Link": "'<Some valid header>'",
      "gatewayresponse.header.WWW-Authenticate": "'<Some valid header>'"
    },
    "responseTemplates": {
      "application/json": "{ \"message\": $context.error.messageString }\n"
    }
  }
}
```

>I'd be interested in learning what custom Swagger you need to write.

Just Auth and Gateway Responses. If not for those, we could leave `DefinitionBody` off entirely. I know that Auth is coming, and I'm champin' at the bit for it. Thus this issue -- I _want_ to leave `DefinitionBody` off entirely. 😛 I'm using "AWS::ApiGateway::GatewayResponse" in order to write less (and someday no) Swagger. But it sounds as though it's fundamentally incompatible with SAM?

**Comment by brettstack** [comment]
Yes, most `AWS::ApiGateway::*` CloudFormation resources (at least those related to an Api resource) are incompatible not just with SAM but with API Gateway + Swagger in general.

Hopefully you'll soon be able to reduce your Swagger to simply:

```yaml
# NOTE: For example only; we haven't yet discussed the syntax
MergeDefinitionBodyWithDefault: true
DefinitionBody: {
  "x-amazon-apigateway-gateway-responses": {
    ...
  }
}
```

**Comment by chrisoverzero** [comment]
Ah, OK, I get it now. 💡 I had no conception until now how much SAM relied on transformation-to-Swagger. Is there an extant issue for `MergeDefinitionBodyWithDefault` (or whatever) which I can throw client weight behind? No searches of terms obvious to me brought one up.

That said, it's weird to me that Auth will be supported in "native" SAM, but the ability to respond with correctly formed 401-class responses will be a "fall back to raw Swagger" feature. Do you think there would be any traction to an `AWS::Serverless::GatewayResponse` (or whatever)?

**Comment by brettstack** [comment]
Absolutely. The "fallback to Swagger" should be a stop-gap solution until we implement native support for Gateway Responses.

We don't yet have a GitHub Issue for the merge feature I mentioned, though there has been internal discussion. We'll post an Issue for community feedback and +1s soon.
