### ISSUE TITLE
Renaming a Serverless::Function used by an Api Gateway does not deploy the Gateway

### ISSUE THREAD

**Issue by jceloi** [awslabs/serverless-application-model#634]
**Description:**

Only renaming (no code change) a Serverless::Function using a FunctionName property does not trigger an Api Gateway stage deploy and the API Gateway stage still points to the previous lambda, which in that case does not exist anymore, generating an internal server error.

Manually triggering an API Gateway deploy does solve the problem, but according to me that should be done automatically when the FunctionName changes.

**Steps to reproduce the issue:**
1. Using cloudformation, create an AWS::Serverless::Api pointing at a AWS::Serverless::Function . Deploy it, check that the calls are correctly triggering the lambda.
2. Add a static FunctionName property to the Function, different than the one previously generated during the first deploy. Redeploy the stack.
3. Try to call the lambda through the api gateway again.

**Observed result:**
* Error 500, Internal Server Error code
* No event is routed to the lambda function

**Expected result:**
* Correct invocation of the lambda function

**Comment by jvanbrunschot-coolblue** [comment]
We're running in the same issue. Renaming functions (without a code change) results in permission errors when invoking functions. 
`Execution failed due to configuration error: Invalid permissions on Lambda function`

**Comment by brettstack** [comment]
You should be able to change the logical resource id instead of setting `FunctionName` (which is best practice) and should trigger an API Gateway deploy. We have also discussed adding a new property to *always* deploy your API even if we can't detect a change to the API.

**Comment by keetonian** [comment]
Closed in favor of #660

**Comment by eliottparis** [comment]
> You should be able to change the logical resource id instead of setting `FunctionName` (which is best practice) and should trigger an API Gateway deploy.

I'm facing the same issue here, but I need my `FunctionName` to be dynamically computed depending on an input template parameter.

```yml
Parameters:
  Stage:
    Type: String

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "", [ "MyFunction-", !Ref Stage]]
```

#660 could be an option in the future, but is there a way to achieve that for now?

**Comment by jlhood** [comment]
Actually, it looks like a draft PR had been put up to make this change, but wasn't completed. https://github.com/awslabs/serverless-application-model/pull/1134
