### ISSUE TITLE
sam validate - missing error for misspelled parameter "type" keyword

### ISSUE THREAD

**Issue by robinandeer** [awslabs/serverless-application-model#666]
**Description:**

My project was not building in AWS (failing on cloudformation step) and complaining about validation error for the template.

`sam validate` didn't complain about any errors.

**Steps to reproduce the issue:**
1. Define a top level parameter:
	```
	Parameters:

        ApiKey:
			type: String
  			Description: My api key to the api
    ```
2. Run `sam validate`

**Observed result:**

No errors reported.

**Expected result:**

Some error message that the "type" keyword is unknown perhaps since it should be spelled with capital T - "Type".

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac OS Mojave, Python 3.

**Output of `sam --version`**:

SAM CLI, version 0.6.1

**Optional Debug logs**:

`Add --debug flag to command you are running`

**Comment by keetonian** [comment]
Closing in favor of https://github.com/awslabs/serverless-application-model/issues/675
