### ISSUE TITLE
How to pass a secret, e.g. API key, to lambda function via a variable, without hardcoding it in the template.yaml file

### ISSUE THREAD

**Issue by holtc** [awslabs/serverless-application-model#668]
Is there any example of how to pass a secret, such as an external API key, to a lambda function as an environment variable, without hardcoding said secret in the template file?  Or is there a better way to retrieve this key within the lambda function? Thanks!

**Comment by jlhood** [comment]
The recommended pattern for doing this is to store the value as an encrypted string in [SSM Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html) and give the Lambda function permission to decrypt the value. [This blog post](https://aws.amazon.com/blogs/compute/sharing-secrets-with-aws-lambda-using-aws-systems-manager-parameter-store/) describes how to do that.

For future reference, StackOverflow is a more appropriate place to ask general serverless questions like this so others can benefit from the answer. You can tag your question with [serverless-application-model](https://stackoverflow.com/questions/tagged/serverless-application-model) and/or [aws-serverless](https://stackoverflow.com/questions/tagged/aws-serverless).

**Comment by holtc** [comment]
Great, will do from here on out, thanks!
