### ISSUE TITLE
Possible to use with Amplify

### ISSUE THREAD

**Issue by holtc** [awslabs/serverless-application-model#671]
Is it possible to use this with AWS Amplify?  Linking [this](https://github.com/aws-amplify/amplify-cli/issues/155).  I'm trying to integrate my Angular frontend with my SAM template, and I'd like to use the functionality provided by Amplify to allow Cognito authentication on the frontend.

**Comment by brettstack** [comment]
Absolutely. Check out the Amplify docs on how to configure your app to use specific resources https://aws-amplify.github.io/docs/js/api#manual-setup. My recommendation is to use SAM for managing your infrastructure, and leverage Amplify for improving the front end DX/UX of your application.

Let me know if you had something else in mind.

**Comment by holtc** [comment]
Sounds great, thanks!
