### ISSUE TITLE
Stack creation error: Requires capabilities : [CAPABILITY_NAMED_IAM]

### ISSUE THREAD

**Issue by kukrejashyam** [awslabs/serverless-application-model#676]
Hi Team,
I am facing issue while writing CF template to create rolese as it now requires "CAPABILITY_IAM" parameter. i got lot of answers over how to slve this by CLI but am looking for answer of what code do i include in my CloudFormation template to get over this.
Thanks.

Below is my code that fails while creating stack using CF yaml template.
=======================================
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Function from Cloud Formation by Shyam - Code in S3 ZipFile'

Resources:
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties:
        Code:
            S3Bucket: "test-source-bucket"
            S3Key: "lambda-function.zip"
        Description: Test with Cloud Formation
        FunctionName: lambda-function
        Handler: lambda_function.lambda_handler
        ## enter your role arn here
        Role: arn:aws:iam::<acount id>:role/service-role/role-name
        Runtime: python2.7
=======================================

**Steps to reproduce the issue:**
1. Run the above YML template using CF.

**Observed result:**
![image](https://user-images.githubusercontent.com/19922253/48882447-5ff4da80-ee40-11e8-811f-53a0e70d5a62.png)

**Comment by keetonian** [comment]
It looks like you are using the CloudFormation console to deploy this stack, is this correct?

The [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html#using-iam-capabilities) has the following instructions for granting this capability via the console: 
>In the AWS CloudFormation console, on the **Review** page of the Create Stack or Update Stack wizards, choose **I acknowledge that this template may create IAM resources**.

This should fix this capability issue.
