### ISSUE TITLE
Offer a way to get the ARN of the AWS::Serverless::Function IAM role

### ISSUE THREAD

**Issue by Dunedan** [awslabs/serverless-application-model#678]
Currently `AWS::Serverless::Function` offer `Ref` and the `Arn` as only possible return values. When creating a `AWS::Serverless::Function` and directly attaching IAM policies to it, there is no way to get the ARN of the automatically created `AWS::IAM::Role`.

That's e.g. a problem when trying to grant a `AWS::Serverless::Function` access to a KMS key via the key policy of that key. In that case the key policy requires the role ARN of the function as principal, but there is no way to get the ARN of this role.

The current workaround is to create an `AWS::IAM::Role` separately and use the `Role` attribute of the `AWS::Serverless::Function` to attach it to the function, but it would be easier to be able to define the policies directly in the `AWS::Serverless::Function` and do something like `!GetAtt my_serverless_function.RoleArn` to get the ARN of the automatically created role.

**Comment by samallisonds** [comment]
You should be able to do `!GetAtt my_serverless_functionRole.Arn`

At first it is a little weird referring to Resources that aren't specifically defined in your template, but it works fine. You may find it interesting to take a look at the fully expanded transformed template in the CloudFormation console.

**Comment by Dunedan** [comment]
Ok, that's interesting. Thanks for pointing it out. [It's even documented](https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#aws-serverless-function), so I guess it's somehow officially supported?! Are there any guarantees, that the implementation won't change in future, thus breaking templates using it?

Even if that's the case it still feels weird referencing a resource which isn't defined in the template.

**Comment by samallisonds** [comment]
Personally I can't see them making a breaking change just to rename a role, especially as it's part of the documentation. And if they ever did it'd fall over before you could deploy it anyway

**Comment by keetonian** [comment]
@samallisonds is correct, this is a valid way of referencing the arn of the generated role. This is a supported feature of SAM.
