### ISSUE TITLE
Is it possible to config an api authorizer of type aws_iam?

### ISSUE THREAD

**Issue by OndeVai** [awslabs/serverless-application-model#685]
In the serverless framework, I can specify an authorizer of type aws_iam like this:
create:
    handler: create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          **authorizer: aws_iam**

Is it possible to do this in SAM yaml? I only see support for custom authorizers or or cognito user pool authorizers.

**Comment by keetonian** [comment]
Related issues and requests for this feature:
https://github.com/awslabs/serverless-application-model/issues/512#issuecomment-420324817
https://github.com/awslabs/serverless-application-model/issues/248#issuecomment-393660831

**Comment by brettstack** [comment]
Closing in favor of #781
