### ISSUE TITLE
References to Swagger should say OpenAPI

### ISSUE THREAD

**Issue by dbenhur** [awslabs/serverless-application-model#7]
[Starting January 1st 2016 the Swagger Specification has been donated to the Open API Initiative (OAI) and is the foundation of the OpenAPI Specification.](http://swagger.io/)

All references to Swagger in our docs should reflect its current name (or both, eg "OpenAPI (fka Swagger)") and link the [OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification).

**Comment by sanathkr** [comment]
We want to keep the nomenclature in this spec close to the language in [CloudFormation's documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-body) to avoid confusion. We can make the change as soon as CloudFormation doc changes

**Comment by mig281** [comment]
The CFN docs are now updated.
