### ISSUE TITLE
Authorization using SAM template without swagger

### ISSUE THREAD

**Issue by dilippatidar123** [awslabs/serverless-application-model#713]
Hi Team, 
We are trying to configure Authorization using following code. 
But its throwing the below error. 
**FAILED - Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyApi] is invalid. Auth works only with inline Swagger specified in 'DefinitionBody' property 
For reference we are using following example form below** 

url :-
[]( https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/api_lambda_request_auth )

Documentation says if we will not provide DefinitionBody or url then it will create automatically then still its giving error. 

Also we tried using CLI command as suggested in example. Still giving the same error.

**Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyApi] is invalid. Auth works only with inline Swagger specified in 'DefinitionBody' property**

Please suggest. 

Thanks,
 Dilip

**Comment by keetonian** [comment]
Could you share a sample template that reproduces this issue?

**Comment by jhappoldt** [comment]
Hi @keetonian,

I was able to reproduce this by running `sam validate` on the authorization sample included in the repository here:  https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_lambda_token_auth/template.yaml

Output:

```sam validate
2018-12-13 13:39:13 Found credentials in environment variables.
Template provided at '/Users/joshhappoldt/projects/serverless/template.yaml' was invalid SAM Template.
Error: [InvalidResourceException('MyApi', "Auth works only with inline Swagger specified in 'DefinitionBody' property")] ('MyApi', "Auth works only with inline Swagger specified in 'DefinitionBody' property")```.

It appears this issue makes it impossible to have a template with both an autogenerated swagger document and an authorizer.  Is anyone aware of a workaround for this issue?

**Comment by keetonian** [comment]
This is a known issue with `sam validate`. This issue can be tracked here: https://github.com/awslabs/aws-sam-cli/issues/803. Please add a +1 to that issue!

The authorization examples included in this repository are valid SAM syntax and work, so go ahead and use those examples.
