### ISSUE TITLE
Make a GUI for SAM

### ISSUE THREAD

**Issue by feinstein** [awslabs/serverless-application-model#734]
Nowadays the technology landscape is changing so frequently that keep up to date with all the new stuff is tiresome. The more AWS can help up us to enroll with their services the better.

Instead of sitting down for learning all aspects on how to format a SAM template for deployment and having the remember all the little details about its formatting, AWS could just provide a GUI where we could just instinctively point and click, selecting our options so this way all the cumbersome YAML writing is hidden from from us.

We could run locally an API Gateway that calls a Lambda function and deploy it to the cloud as easily as when we do it in the AWS Console website.

I understand it's a LOT easier for you guys to develop and update a CLI program, but seriously, for the rest of us common humans, AWS has a very steep learning curve, which translates in uncertainty, insecurity, doubt, and a lot wasted time-to-market.

**Comment by keetonian** [comment]
I thought about this same thing when I was first learning about AWS and SAM in particular. I think that this would be great to have, if done right. 

It sounds moderately difficult to build and maintain, especially if you consider all of the features and applications that can be used via Serverless Applications and the Serverless Application Repository as well as the other Serverless resources and resources offered by CloudFormation. 

What thoughts do others have about this proposal? Would love to get some community input on this as well as thoughts on how feasible and/or helpful this would be.

**Comment by feinstein** [comment]
Well, I may be getting this wrong, but I don't think it's that much difficult as it looks at first analysis.

Most serverless services are already released and their yaml interface won't change, since this will break many applications. What does change are new services that are released and aren't coupled with previous yaml templates. 

This way, the GUI just has to have a compatibility chart, indicating which services aren't supported yet. 

So when there's a new feature for SAM, it will be released first as a yaml command/CLI command, and later it will be incorporated into the SAM GUI.

I can't imagine SAM having a major release that breaks previous versions and thus breaking the GUI. 

But I am not very much experienced and would love to hear other people's comments as well.

If AWS could get some UI/UX designers into a SAM GUI task force would be amazing and speed things up considerably, not even mentioning the quality of and usability of the final product.

**Comment by keetonian** [comment]
We'll leave this issue open to for additional feedback and +1's. 

In the meantime, there are some 3rd party solutions that offer GUI design of SAM or CFN templates. One example is https://www.stackery.io/
