### ISSUE TITLE
Support for third party python modules

### ISSUE THREAD

**Issue by ryanwhitehouse** [awslabs/serverless-application-model#735]
I am not sure if there is an easier way to achieve this, but I want to be able to separate my source and distribution files and utilize sam build --use-container to build my libraries. 

The problem is that sam build and sam package are both using code uri to decide where to start collecting files.  I want to be able to tell sam build to use src and sam package to use dist.  I will then use sam build --use-container to create the .aws-sam/build/{functionName} folder, copy the contents to my dist folder and package and deploy it.  This could all be done in one script which I plan to run in my CI/CD pipeline.

I have been playing around with different options here https://github.com/ryanwhitehouse/pySAM.  This is works with a single script, but since I need two code uri's, I have used two identical template.yml (except for the different code uri).  This would be a whole lot less hacky if I could just have a single template.yml and have it specify a distributionUri as well as my codeUri.

Proposed solution: 
Optional distributionUri parameter to override codeUri when using sam package.

Note, similar to https://github.com/awslabs/aws-sam-cli/issues/53
```
You can write a script with a task runner that monitors source code and creates a build directory where you have your source code as well as dependencies flattened. Set CodeUri in SAM file to point point to the build directory
```
However, I still do not see a solution to needing two different codeUris

**Comment by timoschilling** [comment]
Maybe you can solve your issue with [Layers](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html).

**Comment by keetonian** [comment]
Layers are a great way of bundling dependencies and library code. I think that this task is also easily scripted to build+package+deploy code; keeping the build directory separate from the working (development) directory is a nice feature so that build artifacts do not get in the way of normal development.
