### ISSUE TITLE
Feature Request: cloudwatch-logs-to-slack request

### ISSUE THREAD

**Issue by e-moshaya** [awslabs/serverless-application-model#736]
Hi,

Can we have a new Lambda blueprint similar to cloudwatch-logs-to-loggly but send logs to slack based on a filter?

cloudwatch-logs-to-slack

**Comment by keetonian** [comment]
Interesting idea. I added relevant tags to this issue, and would be willing to review code and work with someone to get it done.

**Comment by keetonian** [comment]
I have a WIP version of this here: https://github.com/keetonian/cw-logs-to-slack

Posting logs to a slack channel is done (I need to write up instructions in the README about how to do it), I'm looking into other slack integrations and commands now.

**Comment by Buffer0x7cd** [comment]
@keetonian  I would like to work on this issue. but it looks like you have already worked on the initial application. let me know if there are any other additions to this feature that needs to be worked upon.

**Comment by jlhood** [comment]
@Buffer0x7cd Thanks for offering to contribute! We think the app Keeton wrote is a sufficient example of this use case. Closing this issue.
