### ISSUE TITLE
Lambda authorizers are badly broken in SAM right now.

### ISSUE THREAD

**Issue by elver** [awslabs/serverless-application-model#756]
This example template fails to validate and demonstrates the issue I'm having with my own template: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_lambda_token_auth/template.yaml

sam validate returns with:

`Error: [InvalidResourceException('MyApi', "Auth works only with inline Swagger specified in 'DefinitionBody' property")] ('MyApi', "Auth works only with inline Swagger specified in 'DefinitionBody' property")`

I swear this kind of a template used to deploy cleanly to aws just a week ago, despite failing sam validation, but now cloudformation seems to be running "sam validate" as part of its thing and that's failing with the same error message:

`Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyAPI] is invalid. Auth works only with inline Swagger specified in 'DefinitionBody' property`

But when I add a DefinitionBody to the API resource, then cloudformation fails with the following:

`Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyAPI] is invalid. Specify either 'DefinitionUri' or 'DefinitionBody' property and not both`

What's the best way to define a lambda token authorizer right now?

**Comment by keetonian** [comment]
Which region is this in? And could you provide a sample of what you're trying to deploy?

`sam validate` failing on the authorizer examples is a known issue: https://github.com/awslabs/aws-sam-cli/issues/803

**Comment by GeekOnGadgets** [comment]
I am trying to deploy lambda token authorizer and can't find any documentation on what is the best way to include in sam `template.yml` file. Any example  can you please point me to? Currently looking at this https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_lambda_token_auth/template.yaml but not working. Some how `!GetAtt` are failing. Any help is appreciated.

Thanks

**Comment by Bratkartoffl** [comment]
Same here.. I do attach a Cognito Authorizer to a Ressource in my template.yaml. This worked 1 week ago. Since today i notices, that the authorizer does not get attached to the ressource. Any ideas?

**Comment by jlhood** [comment]
@elver Using SAM's support for API Gateway Authorizers only works with inline swagger, i.e., defined in the DefinitionBody property, not swagger defined in an external file. The example you link will not pass sam validate due to the issue @keetonian linked, but it does deploy successfully in CloudFormation.

Other customers are working around this using a pre-build step that injects the swagger definition from the external file into the template before validate/deploy.

**Comment by LacikIgor** [comment]
@jlhood Any plans to allow the use of **DefinitionUri** instead of the inline swagger?

Thanks

**Comment by jlhood** [comment]
@LacikIgor Not currently.

The key difficulty is SAM would need a way to modify the swagger definition referenced by `DefinitionUri`. SAM is implemented as a pure transform in that it only modifies the given template and not any externally referenced files. It would be setting a new precedent to have it try to download the referenced swagger file, modify it and use the modified version instead. `DefinitionUri` today is the customer's way of saying they want to hand-manage the Swagger document themselves. Not sure if we could introduce SAM modifications to a hand-managed Swagger document in a safe and intuitive way.

**Comment by brettstack** [comment]
Closing in favor of https://github.com/awslabs/aws-sam-cli/issues/803
