### ISSUE TITLE
ReservedConcurrentExecutions in Globals section

### ISSUE THREAD

**Issue by joeythomaschaske** [awslabs/serverless-application-model#760]
Doesn't look like you can declare the ReservedConcurrentExecutions in the global section.

This is not listed [in the unsupported properties documentation](https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#unsupported-properties)

`Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. 'Globals' section is invalid. 'ReservedConcurrentExecutions' is not a supported property of 'Function'.`

**Comment by keetonian** [comment]
Good catch, I don't see anything wrong with supporting that property in the globals. It would be a simple PR if you wanted to submit one.

Add the property [here](https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/plugins/globals/globals.py#L17) and update relevant tests and that should be all.

**Comment by keetonian** [comment]
Released with [SAM v1.11.0](https://github.com/awslabs/serverless-application-model/releases/tag/v1.11.0)!
