### ISSUE TITLE
No way to set stage variables for auto-generated "Stage" stage

### ISSUE THREAD

**Issue by leagerl1** [awslabs/serverless-application-model#78]
The AWS::Serverless::Api resource allows you to specify a single stage name and variables to be set but it also auto-generates a "Stage" stage. There is no way to set stage variables for that stage and there is no way to add another stage. It makes it impossible to use that stage based on how the examples in this repo recommend using them.

**Comment by Dunedan** [comment]
Relates to #67 I'd say.

**Comment by sanathkr** [comment]
Yeah, don't rely on the autogenerated stage called "Stage". It might be removed soon

**Comment by jfuss** [comment]
As @sanathkr said, do not rely on the stage 'Stage'.  We will add some control over Stage names and such with #248. It is unclear what we will be doing with the stage 'Stage' though. 

Closing in favor of #248
