### ISSUE TITLE
Confusion about Authorizer: NONE and Auth in general

### ISSUE THREAD

**Issue by jzjones** [awslabs/serverless-application-model#784]
**Description:**

I have an API and a Function defined, I have an authorizer defined on the API and am trying to figure out how to apply it to certain functions only. 

`Resources:

    AppApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: dev
            DefinitionBody:
                swagger: 2.0
                info:
                    title:
                        Ref: AWS::StackName
                paths:
                    "/hello":
                        get:
                            x-amazon-apigateway-integration:
                                httpMethod: POST
                                type: aws_proxy
                                uri:
                                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
                            responses: {}
            Auth:
                DefaultAuthorizer: CognitoAuth
                Authorizers:
                    CognitoAuth:
                        UserPoolArn: !GetAtt UserPool.Arn
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello-world/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Events:
                AppApi:
                    Type: Api
                    Properties:
                        Path: /hello
                        Method: get
                        RestApiId: !Ref AppApi
                        # Auth:
                        #     Authorizer: 'NONE'
`

The above snippet works and applies the CognitoAuth to the HelloWorldFunction, however when I try to remove the auth for a specific function using Authorizer: NONE, like in the commented out lines, it doesn't seem to do anything. I think this might be a bug as the documentation indicates this should now make the function public

**Steps to reproduce the issue:**
1. Add default authorizer to API
2. Add Authorization: NONE to function Auth object

**Observed result:**
Function still has authorizer applied

**Expected result:**
Function should be public

**Comment by jzjones** [comment]
Was able to get this working by removing DefinitionBody property from the API

**Comment by praetp** [comment]
Any other solution besides removing the DefinitionBody ? Still smells like a bug to me.

**Comment by praetp** [comment]
Adding
```
   security: 
              - NONE: []
```
to the DefinitionBody is an alternative workaround.
