### ISSUE TITLE
InvalidChangeSetStatus when using CloudFormation in CodePipeline to package and deploy SAM

### ISSUE THREAD

**Issue by tangerinedream** [awslabs/serverless-application-model#789]
**Description:**

In the Build Action of CodePipeline, I am using CF to package and deploy a SAM template.  

The execution of the deployment is successful 100% of the time.  However, on a random frequency, cloudformation reports the deploy failed (even though it succeeded), which causes the Pipeline to fail in the Build Action.

Here is code from buildspec.yaml.  

      - echo "+++++ Transforming SAM to CF +++++"
      - aws cloudformation package --template-file SAM.cf.yaml --s3-bucket codepipeline-us-west-2-****** --output-template-file packagedSAM.yaml --kms-key-id *******

      - echo "+++++ Deploying Scheduler-Workload-Stack +++++"
      - aws cloudformation deploy --template-file packagedSAM.yaml --stack-name ****-Workload-Stack --capabilities CAPABILITY_IAM

The build log reports the SAM template deployment failed due to an InvalidChangeSetStatus / OBSOLETE.

The pipeline fails (although the deployment actually succeeds).

**Steps to reproduce the issue:**
1.  Use CF to package and deploy a SAM template within CodePipeline's Build's Action
2.  Run the pipeline some number of times (unfortunately this is indeterminate, but happens repeatedly over time)
3.  Check the pipeline status for failure

**Observed result:**

[Container] 2019/01/16 06:19:06 Running command echo "+++++ Transforming SAM to CF +++++"
+++++ Transforming SAM to CF +++++
**[Container] 2019/01/16 06:19:06 Running command aws cloudformation package --template-file SAM.cf.yaml --s3-bucket codepipeline-us-west-2-++++ --output-template-file packagedSAM.yaml --kms-key-id ++++**
 Uploading to f42b95e75fff10cd9ad362e45cdba5c4 262144 / 513771.0 (51.02%)
Uploading to f42b95e75fff10cd9ad362e45cdba5c4 513771 / 513771.0 (100.00%)
Successfully packaged artifacts and wrote output template to file packagedSAM.yaml.
Execute the following command to deploy the packaged template
aws cloudformation deploy --template-file /codebuild/output/src275823309/src/buildDir/packagedSAM.yaml --stack-name <YOUR STACK NAME>
 [Container] 2019/01/16 06:19:08 Running command echo "+++++ Deploying *****-Workload-Stack +++++"
+++++ Deploying *****-Workload-Stack +++++
 [Container] 2019/01/16 06:19:08 Running command aws cloudformation deploy --template-file packagedSAM.yaml --stack-name *****-Workload-Stack --capabilities CAPABILITY_IAM
 Waiting for changeset to be created..
 **An error occurred (InvalidChangeSetStatus) when calling the ExecuteChangeSet operation: ChangeSet [arn:aws:cloudformation:us-west-2:+++:stack/+++-Workload-Stack/52750660-0c0d-11e9-b866-06a411f6609a] cannot be executed in its current execution status of [OBSOLETE]**
 **[Container] 2019/01/16 06:19:19 Command did not exit successfully aws cloudformation deploy --template-file packagedSAM.yaml --stack-name ++++-Workload-Stack --capabilities CAPABILITY_IAM exit status 255**
[Container] 2019/01/16 06:19:19 Phase complete: POST_BUILD Success: **false**
[Container] 2019/01/16 06:19:19 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: aws cloudformation deploy --template-file packagedSAM.yaml --stack-name *****-Workload-Stack --capabilities CAPABILITY_IAM. Reason: **exit status 255**

**Expected result:**

Success result code from Build Action in CodePipeline
exit status 0

**Comment by brettstack** [comment]
Hi @tangerinedream, this doesn't sound like a SAM issue. I think you might get a better response over on StackOverflow.

**Comment by tangerinedream** [comment]
Hi @brettstack, what do you see that rules this out from being a SAM issue?  I'm simply calling cloudformation package and cloudformation deploy command of a basic SAM file, sequentially in the Pipeline (within 2 seconds per the output shown above).   _Is it perhaps a CloudFormation proper issue?_

**Commands:**
aws cloudformation package --template-file SAM.cf.yaml --s3-bucket codepipeline-us-west-2-****** --output-template-file packagedSAM.yaml --kms-key-id *******

aws cloudformation deploy --template-file packagedSAM.yaml --stack-name ****-Workload-Stack --capabilities CAPABILITY_IAM

**SAM File w/sanitized names**
Transform: 'AWS::Serverless-2016-10-31'
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Sam template for Workload Lambda'
Resources:
  myFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: myFunction
      Runtime: python3.6
      Handler: MyFunc.lambda_handler
      Timeout: 30
      AutoPublishAlias: DEV
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LambdaRole
      CodeUri: myFunc.zip
      Environment:
        Variables:
          DYNAMODB_REGION: us-west-2
          LOG_LEVEL: logging.DEBUG
          SNS_TOPIC: mySNSTopic
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        WorkloadProxy:
          Type: Api 
          Properties:
            Path: /workloads/{workload+}
            Method: any
#
Outputs:
  myAPI:
    Description: "API Gateway endpoint URL for Prod stage for myFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/workloads/{workload+}"

  myFunction:
    Description: "myFunc Lambda Function ARN"
    Value: !GetAtt myFunc.Arn

  myIamRole:
    Description: "Implicit IAM Role created for WorkloadProxy function"
    Value: !GetAtt myFunc.Arn
