### ISSUE TITLE
Dynamic URI in Swagger file

### ISSUE THREAD

**Issue by joshm91** [awslabs/serverless-application-model#79]
Hi,
Is there a way that I'm missing to have a more dynamic URI to the lambda function defined in a swagger file.

I've tried passing in region and arn/accountId variables in the same way that the function name is passed in in [this](https://algithub.pd.alertlogic.net/alertlogic/cd15-pipeline-docker-jenkins/pull/4/files#diff-3fc7094f116e5511cb146bc3a36d2202R22) example but it never works, even though I've confirmed that the variables contain the correct values.

The error I keep getting in the cloudformation console is
```
Errors found during import: Unable to put integration on 'GET' for resource at path '/preapproved-service/{service-name}': Invalid ARN specified in the request
```

Thanks for any advice

**Comment by sanathkr** [comment]
Unfortunately not. This is a API Gateway limitation and SAM does not have any control over it. You have to hard-code AccountId and Region in APIGateway until this limitation is fixed.

**Comment by mmuppidi** [comment]
Is this changed yet ? I have the same issue.

**Comment by joshm91** [comment]
I believe it's still the same. We've resorted to using inline swagger definitions being as our APIs are fairly simple.

**Comment by mkochco** [comment]
@sanathkr Following the api_swagger_cors example (minus cors) I'm still seeing 'Invalid Arn' when creating the stack.  Do we still need to hard code the account and region when using a separate swagger.yml file?

**Comment by taylorp36** [comment]
+1, do we still have to in-line swagger?

**Comment by sparrowt** [comment]
It seems swagger files referenced by `DefinitionUri:` still do not support substitution; neither `!Sub` or `Fn::Sub:` work, and AmazonApiGateway produces one of the following non-specific errors:
```
Errors found during import: Unable to put integration on 'GET' for resource at path '/foo': AWS ARN for integration must contain path or action (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: ...)
```
```
Errors found during import: Unable to put integration on 'GET' for resource at path '/foo': Invalid ARN specified in the request
```
```
Unable to parse API definition because of a malformed integration at path /foo. (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: ...)
```
depending on exactly how you try - all somewhat lacking in clarity / line number of error.

However there does appear to be a solution which doesn't involve inlining the swagger: [this example template.yaml](https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/api_swagger_cors/template.yaml#L15) uses `Fn::Transform` & `AWS::Include` to bring in a swagger.yaml file from S3 like so:
```
        DefinitionBody:
          'Fn::Transform':
            Name: 'AWS::Include'
            # Replace <bucket> with your bucket name
            Parameters:
              Location: s3://<bucket>/swagger.yaml
```
and [the accompanying example swagger.yaml](https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/api_swagger_cors/swagger.yaml) contains substitutions which will be filled in with the relevant values.
