### ISSUE TITLE
AWS::Serverless::Api Definition swagger vs open api 3

### ISSUE THREAD

**Issue by joeythomaschaske** [awslabs/serverless-application-model#790]
The AWS::Serverless::Api resource has a `DefinitionUri/Body` property for a swagger definition. I did some research and I see that Swagger 2 has been super ceded by Open Api 3. 

Can we use Open Api 3 specifications, are there plans to allow usage, or do we still have to user Swagger 2 definitions?

https://swagger.io/specification/#versions

**Comment by keetonian** [comment]
As of right now, you still need to use Swagger 2.0 definitions in SAM. It's in our backlog to support Open Api 3.0; this has been brought up in https://github.com/awslabs/serverless-application-model/issues/7 and https://github.com/awslabs/serverless-application-model/issues/627.

**Comment by joeythomaschaske** [comment]
Awesome, I'll close this guy out.
