### ISSUE TITLE
Implement AWS_IAM Authorizers

### ISSUE THREAD

**Issue by brettstack** [awslabs/serverless-application-model#802]
Based on the RFC #781, we need to implement the AWS_IAM Authorizers feature.

Requirements:

1. Implement Transform
1. Add tests
1. Add example(s)

Some code areas to get started for any interested contributors:

1. Add `InvokeRole` as a valid property of `Auth` https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/api/api_generator.py#L20
1. Add an exception for `AWS_IAM` `DefaultAuthorizer` here https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/api/api_generator.py#L321
1. Ensure this section is working and only a single sigv4 security definition gets added https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/swagger/swagger.py#L343
1. Add 'sigv4' to `securityDefinitions` if it's defined as DefaultAuthorizer or if it is specified on any of the Methods https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/swagger/swagger.py#L289
1. Update Integration with credentials https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/swagger/swagger.py#L101

**Comment by rhboyd** [comment]
Is the idea that it would look something like:

    Auth:
      DefaultAuthorizer: MyCognitoAuth # OPTIONAL
      Authorizers:
        AWS_IAM: some:arn:aws:1

and the serverless macro would transform that into specifying AWS_IAM for the auth type and add the policy to the resource policy on the API?

**Comment by rhboyd** [comment]
or possibly

    Auth:
      Authorizers:
        AWS_IAM: NOT_AN_ARN

And the macro would create an IAM Role and substitute that role where applicable in the previous comment?

**Comment by brettstack** [comment]
@rhboyd check out the RFC #781

**Comment by horike37** [comment]
Hey @brettstack, I would like to start working on this since this feature is needed for my job.
No problem?

**Comment by brettstack** [comment]
Absolutely! We look forward to a PR. ❤️

**Comment by horike37** [comment]
Hey @brettstack, My PR #827 is just ready for review!
Please go ahead 👍 😄 Thanks!

**Comment by brettstack** [comment]
Thanks @horike37! This has been merged to develop and we'll get it out to production asap.

**Comment by horike37** [comment]
Great! Can't wait to release 😄

**Comment by keetonian** [comment]
Released with [SAM v1.11.0](https://github.com/awslabs/serverless-application-model/releases/tag/v1.11.0)!
