### ISSUE TITLE
Updates to swagger definition not reflected

### ISSUE THREAD

**Issue by Dunedan** [awslabs/serverless-application-model#82]
When I deploy a `AWS::Serverless::Api` and want to update it by changing the swagger file containing its definition, after a `aws cloudformation package ... && aws cloudformation deploy ...` API Gateway still shows the old definition. The changes in the API are not reflected at all.
Am I doing something wrong or is that a known bug?

**Comment by sanathkr** [comment]
Yeah, this is a known bug. It should be fixed this week

**Comment by sanathkr** [comment]
This should be fixed by now. See #53

**Comment by Amanfavas** [comment]
If I change the swagger file is not reflcting in apigateway.Once I deleted the stack or update the url of DefinitionUri.Please help me

**Comment by Amanfavas** [comment]
@sanathkr, Still this issues their, Let me fixed update
