### ISSUE TITLE
Cant load Api Gateway definition (Open API 3.0.1) via AWS::Include from bucket

### ISSUE THREAD

**Issue by deser** [awslabs/serverless-application-model#829]
Hi Guys,
I have very strange error.
When I try to setup it so it fails:
```
    DataDictionaryAPI:
        Type: AWS::Serverless::Api
        Properties:
            StageName: dev
            DefinitionBody:
                Transform:
                  Name: 'AWS::Include'
                  Parameters:
                    Location: 's3://<mybacket>/openapi3.yaml'
```
Error is: `Invalid OpenAPI input. (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: 204ce2a8-3b76-11e9-ba5c-637fcce65ff2)`

In file I'm calculating ARNs of lamdas defined in main template:
```
      x-amazon-apigateway-integration:
        uri: !Join
          - ''
          - - 'arn:aws:apigateway:'
            - 'us-east-1'
            - ':'
            - 'lambda:path/2015-03-31/functions/'
            - !GetAtt
              - DDNameFunction
              - Arn
            - /invocations

```

When I just `unwrap` contents of `s3://<mybacket>/openapi3.yaml` and put to `DefinitionBody` **it works.** 

Could someone help me?

P.S.
I tried everything:)
1. Convert to JSON
2. Replace ARNs calculation with direct links to lambdas
3. Removing single quotes,
etc...

**Comment by keetonian** [comment]
I think this is the same issue as #305 

When the swagger or OpenApi definition is merged from some other source, it seems like CFN is not able to resolve references to other resources. In your case, this is your reference to:
```yaml
            - !GetAtt
              - DDNameFunction
              - Arn
```

Closing in favor of other issue.

**Comment by deser** [comment]
Thanks!
