### ISSUE TITLE
Lambda trigger always points to Prod stage

### ISSUE THREAD

**Issue by Dunedan** [awslabs/serverless-application-model#83]
When creating a new API Gateway API by using the implicit functionality of `AWS::Serverless::Function` two stages `Prod` and `Stage` get created. As mentioned in #78, we shouldn't care about `Stage`, so let's have a look at `Prod` only, because if you create an API explicitly via `AWS::Serverless::Api` with a different name than `Prod`, everything gets deployed successful and works as expected, but the trigger for the Lambda functions still refer to a (not existing) `Prod` stage.
Is that a bug or intentional?

**Comment by sanathkr** [comment]
That's a bug. it will get fixed in a couple of weeks.

**Comment by sanathkr** [comment]
@Dunedan This bug should be fixed now. Can you verify?

**Comment by Dunedan** [comment]
I did an update to an existing stack and it updated the Lambda functions which had `Prod` triggers to refer to a stage which actual exist instead.
So it seems to work. :+1:
