### ISSUE TITLE
Is 1.9.1 an official release?

### ISSUE THREAD

**Issue by yan12125** [awslabs/serverless-application-model#833]
Version 1.9.1 can be found on PyPI [1], while in this repo the latest version appears to be 1.9.0 [2].

Is 1.9.1 an official release?

[1] https://pypi.org/project/aws-sam-translator/1.9.1/
[2] https://github.com/awslabs/serverless-application-model/releases

**Comment by jlhood** [comment]
@yan12125 Thanks for bringing this up. 1.9.1 was a quick patch release to unblock SAM CLI. We did not publish official release notes for the release since it didn't change existing SAM functionality. Our next official release is 1.10.0, coming very soon.

**Comment by yan12125** [comment]
I saw 1.10.0 out. Thanks for the efforts!
