### ISSUE TITLE
Lambda Custom Deployment configurations in CodeDeploy cant be referenced in SAM template under DeploymentPreference

### ISSUE THREAD

**Issue by dan-schw** [awslabs/serverless-application-model#836]
**Description:**

When creating a Lambda function with a deployment configuration (DeploymentPreference) you need to specify a Type. There are some defaults as defined here: https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html#deployment-configurations-predefined-lambda

However we are unable to use a custom deployment configuration from CodeDeploy. When we make the Type of the DeploymentPreference the name of the custom deployment configuration (eg TestDeploymentConfig) then Cloudformation looks for the deployment configuration CodeDeployDefault.LambdaTestDeploymentConfig. 

**Steps to reproduce the issue:**
1. Create a custom deployment configuration in CodeDeploy called TestDeploymentConfiguration
2. Try to reference it in DeploymentPreference - Type
3. The CF stack made from SAM shows the following error: No deployment configuration found for name: CodeDeployDefault.LambdaTestDeploymentConfiguration

**Code**

This naming seems hardcoded here:

serverless-application-model/samtranslator/model/preferences/deployment_preference_collection.py
Line: 113

```
deployment_group.DeploymentConfigName = fnSub("CodeDeployDefault.Lambda${ConfigName}",
                                                      {"ConfigName":  deployment_preference.deployment_type})
```

With this naming we wont be able to point our deployment preferences to a custom deployment configuration because it always places "CodeDeployDefault.Lambda" in front of the name.

Here (https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html#deployment-configuration-lambda)
 it says "You can also create your own custom canary or linear deployment configuration."

How do we reference a custom deployment configuration in SAM?

**Comment by dan-schw** [comment]
SAM Template

```
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: s3://bucket/code.zip
      AutoPublishAlias: live
      MemorySize: 1024
      Timeout: 15 
      Policies:
        - AWSLambdaExecute # Managed Policy
      DeploymentPreference:
        Enabled: true
        Type: TestDeployment

```

CF Processed template:

```
{"Resources":{"MyLambdaFunctionDeploymentGroup":{"Type":"AWS::CodeDeploy::DeploymentGroup","Properties":{"ApplicationName":{"Ref":"ServerlessDeploymentApplication"},"AutoRollbackConfiguration":{"Enabled":true,"Events":["DEPLOYMENT_FAILURE","DEPLOYMENT_STOP_ON_ALARM","DEPLOYMENT_STOP_ON_REQUEST"]},"ServiceRoleArn":{"Fn::GetAtt":["CodeDeployServiceRole","Arn"]},"DeploymentConfigName":{"Fn::Sub":["CodeDeployDefault.Lambda${ConfigName}",{"ConfigName":"TestDeployment"}]},"DeploymentStyle":{"DeploymentType":"BLUE_GREEN","DeploymentOption":"WITH_TRAFFIC_CONTROL"}}},"CodeDeployServiceRole":{"Type":"AWS::IAM::Role","Properties":{"ManagedPolicyArns":["arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda"],"AssumeRolePolicyDocument":{"Version":"2012-10-17","Statement":[{"Action":["sts:AssumeRole"],"Effect":"Allow","Principal":{"Service":["codedeploy.amazonaws.com"]}}]}}},"MyLambdaFunctionAliaslive":{"Type":"AWS::Lambda::Alias","UpdatePolicy":{"CodeDeployLambdaAliasUpdate":{"ApplicationName":{"Ref":"ServerlessDeploymentApplication"},"DeploymentGroupName":{"Ref":"MyLambdaFunctionDeploymentGroup"}}},"Properties":{"FunctionVersion":{"Fn::GetAtt":["MyLambdaFunctionVersion43f46c25a9","Version"]},"FunctionName":{"Ref":"MyLambdaFunction"},"Name":"live"}},"MyLambdaFunctionRole":{"Type":"AWS::IAM::Role","Properties":{"ManagedPolicyArns":["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole","arn:aws:iam::aws:policy/AWSLambdaExecute"],"AssumeRolePolicyDocument":{"Version":"2012-10-17","Statement":[{"Action":["sts:AssumeRole"],"Effect":"Allow","Principal":{"Service":["lambda.amazonaws.com"]}}]}}},"ServerlessDeploymentApplication":{"Type":"AWS::CodeDeploy::Application","Properties":{"ComputePlatform":"Lambda"}},"MyLambdaFunction":{"Type":"AWS::Lambda::Function","Properties":{"Code":{"S3Bucket":"bucket","S3Key":"code.zip"},"Tags":[{"Value":"SAM","Key":"lambda:createdBy"}],"MemorySize":1024,"Handler":"index.handler","Role":{"Fn::GetAtt":["MyLambdaFunctionRole","Arn"]},"Timeout":15,"Runtime":"nodejs6.10"}},"MyLambdaFunctionVersion43f46c25a9":{"DeletionPolicy":"Retain","Type":"AWS::Lambda::Version","Properties":{"FunctionName":{"Ref":"MyLambdaFunction"}}}}}
```

**Comment by jlhood** [comment]
@dan-schw Thanks for reporting this issue. You're correct, SAM's support for Lambda canary deployments only supports the predefined deployment configurations provided by CodeDeploy and does not support custom deployment configurations.

For backwards-compatibility reasons, we cannot change the existing behavior to remove that prefix. However, we could make a change so the predefined lambda deployment configurations (without the prefix) get the prefix added to them and all others do not. The only downside to this approach would be we would have to maintain a list of predefined lambda deployment configurations and keep it in sync if CodeDeploy service adds more. The alternative is to make a ListDeploymentConfigs API call to CodeDeploy service to dynamically fetch the list of predefined lambda deployment configurations, but in general, we try to minimize the number of API calls the SAM transform makes.

For now, the hardcoded list approach should be fine. This would be a relatively simple change to make if someone wants to give it a go.

You would add a constant set of the existing Lambda deployment preference config names, then if `deployment_preference.deployment_type` is in that list, do the existing `Fn::Sub` behavior, otherwise, just add the name without the `Fn::Sub` and `CodeDeployDefault.Lambda` prefix.

https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/preferences/deployment_preference_collection.py#L112-L113

**Comment by dan-schw** [comment]
Thank you for the response. 

All makes sense. I had considered those different approaches to fixing this. Maybe someone can look into attempting this as it has been a requested feature in the past. 

Thanks again,
Dan

**Comment by Buffer0x7cd** [comment]
@jlhood I would like to work on the above issue :smile:

**Comment by jlhood** [comment]
@Buffer0x7cd Great! Looking forward to the PR. 😃

**Comment by Buffer0x7cd** [comment]
@jlhood my PR is ready for review. please let me know anything that needs to be changed.

**Comment by jlhood** [comment]
@Buffer0x7cd Yes we saw. Thank you so much! It's on our list to review. We'll get to it as soon as we can.

**Comment by jsuna** [comment]
@jlhood any idea when this will get released!?

**Comment by jlhood** [comment]
@jsuna We're not able to comment on exact dates, so the best I can say is it's coming soon!

**Comment by jsuna** [comment]
@jlhood fair enough! I'll keep my eyes peeled, thanks!

**Comment by jlhood** [comment]
Note, this change didn't make the cut in our latest release (v1.11.0), so it will be in the next release.

**Comment by keetonian** [comment]
Feature is released! @jsuna
