### ISSUE TITLE
Request: Support Single Unzipped Source for AWS::Serverless::Function

### ISSUE THREAD

**Issue by FrancescoRizzi** [awslabs/serverless-application-model#84]
In the simplest case, a serverless Lambda function may be a single source code file with no external dependencies. eg (yeah, Python):

```
import os
import boto3

import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def handler(event, context):
    logging.info("Hello World")
```

Under these conditions it would be nice for the SAM Template to let me point to this unzipped source file.
Currently, [the template's CodeUri](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/hello_world/template.yaml) expects me to point to a zip archive, requiring me to add a step to our build pipeline to take the source and zip it up.

It would be nice for either CodeUri to recognize when it is pointed to a non-zip file, or have the ability of using a different property (eg: SimpleSource) for these cases, and have SAM or awscli or CloudFormation zip that file up for me (it seems CloudFormation expects it to be zipped by the time the change set is executed)

**Comment by sanathkr** [comment]
There is a PR for this already - https://github.com/aws/aws-cli/pull/2335. We will get that reviewed soon
