### ISSUE TITLE
Transparency around release cycle

### ISSUE THREAD

**Issue by samuel02** [awslabs/serverless-application-model#842]
We are building a project based on SAM and are in need of some features that are already merged to `develop` but not in `master`. There hasn't been a release since November last year and it would be nice to understand more when we can expect the next release. Looking at https://github.com/awslabs/serverless-application-model/compare/master...develop there are quite a few things waiting to be released.

Is this the correct place to ask? Do you document the plan anywhere? Would it be possible to get more transparency around the release cycle?

**Comment by jlhood** [comment]
Hi @samuel02. Thanks for your feedback regarding transparency around release cycles. I'm happy to say we just released v1.10.0 of SAM today, so the features you're waiting for have just been merged to master. 😊

Currently, the best way to be notified of new SAM releases is to watch this repo for release notifications. We hear your feedback and are looking at other ways to increase transparency around the release process.

**Comment by samuel02** [comment]
@jlhood that's really good news, thanks! 😄
