### ISSUE TITLE
Can't publish templates that contain (or leverage) CloudFormation Macros

### ISSUE THREAD

**Issue by pofallon** [awslabs/serverless-application-model#859]
**Description:**

SAM throws an error when attempting to publish a template containing an `AWS::CloudFormation::Macro` resource.  It also throws an error when attempting to publish a template that leverages an existing Macro via a `Transform` section.

**When trying to publish a template _containing_ a Macro resource:**
**Steps to reproduce the issue:**
1.  Create a template that contains an `AWS::CloudFormation::Macro` resource
2.  Package the template and run `sam publish`

**Observed result:**
A response containing the phrase: `Error: The template contains unsupported resource types. [AWS::CloudFormation::Macro]`

**Expected result:**
Successful publishing of the template

**When trying to publish a template _leveraging_ an existing Macro:**
**Steps to reproduce the issue:**
1.  Create a template that leverages an existing Macro via a Transform section similar to: `Transform: [MyMacro, 'AWS::Serverless-2016-10-31']`
2.  Package the template and run `sam publish`

**Observed result:**
A response containing the phrase: `Error: Resource with name [Transform] is invalid. Provided Transform ['MyMacro', 'AWS::Serverless-2016-10-31'] is unsupported, use one of the following ['AWS::Serverless-2016-10-31']`

**Expected result:**
Successful publishing of the template

For what it's worth, both of these scenarios work just fine when packaging and deploying them -- they  just can't be **published** to the Serverless Application Repository.

**Comment by keetonian** [comment]
Closing, as this is an issue with the Serverless Application Repository and what resources they allow or don't allow and not with SAM. I'll bring this up with that team, this is a known limitation.

**Comment by jlhood** [comment]
Note, you can find the list of resource types supported by SAR here:

https://docs.aws.amazon.com/serverlessrepo/latest/devguide/using-aws-sam.html#supported-resources-for-serverlessrepo
