### ISSUE TITLE
Rebase and refactor ApiKeyRequired feature

### ISSUE THREAD

**Issue by brettstack** [awslabs/serverless-application-model#867]
This feature (https://github.com/awslabs/serverless-application-model/pull/444/files) was merged into a feature branch (https://github.com/awslabs/serverless-application-model/tree/feat/auth) while we worked on the design for Auth as a whole. Now that we have that, we should rebase this change and refactor it to use the `Auth` property so that we can get this merged into develop.

**Comment by jlhood** [comment]
@tylersouthwick Would you be willing to do this? We'd love to get this out into an official release!

**Comment by cfbarbero** [comment]
This has come up at my company so I'd like to jump in on this.  

Here is what I'm proposing to do:
Update the ```Auth``` property to include a new sub-property ```ApiKeyRequired: <boolean>```.  This will be supported on both the [Api Auth Method](https://github.com/cfbarbero/serverless-application-model/blob/master/versions/2016-10-31.md#api-auth-object) and the [Function Auth Method](https://github.com/cfbarbero/serverless-application-model/blob/master/versions/2016-10-31.md#function-auth-object).  The function level specification will override the API level.

**Comment by jlhood** [comment]
@cfbarbero Awesome!! What you're proposing looks like what we're expecting. Looking forward to seeing your PR! Feel free to reach out on this issue if you have questions.

**Comment by jlhood** [comment]
Pending v1.14.0 release

**Comment by ShreyaGangishetty** [comment]
Closing this issue as this is released in v1.14.0
