### ISSUE TITLE
Map Nested Stack to Single API Gateway

### ISSUE THREAD

**Issue by j** [awslabs/serverless-application-model#882]
With current nested stacks & SAM, when I create an Api event type, each service then has it's own API gateway.  Can I have everything be assigned to one API gateway?

**Comment by brettstack** [comment]
This Issue aims to solve this problem #866. Please close this one and follow over there if that sounds right.

**Comment by j** [comment]
@brettstack yep I think that'd work.  I was thinking of the inverse way of doing it, where the sibling template could reference an API gateway from another stack, but I think the FunctionReference way could act as more of a "router" vs being magical (you can create a single place of truth for API routes).
