### ISSUE TITLE
CodeUri - FnSub

### ISSUE THREAD

**Issue by bschneider1216** [awslabs/serverless-application-model#89]
It doesn't look like i am able to use aws intrinsic functions, specifically Fn::Sub, in the CodeUri property.

e.g.
CodeUri: !Sub "s3://${S3Bucket}/${S3Key}"

This will resolve properly in the description property e.g.
Description: !Sub "s3://${S3Bucket}/${S3Key}"

Is this something hat could be supported? I know the docs say it MUST be a valid s3 :)

**Comment by sanathkr** [comment]
Yes, this is a known bug. Intrinsics are not yet supported. #22 will fix this.
