### ISSUE TITLE
Role property in Globals section not supported

### ISSUE THREAD

**Issue by pofallon** [awslabs/serverless-application-model#890]
**Description:**

Attempting to elevate a function's `Role` property to a global value results in a template that can't be deployed.

**Steps to reproduce the issue:**
1.  Create a SAM template with a `Globals` section that includes a Role reference, for example:
```
Globals:
  Function:
    Role: !GetAtt MyLambdaRole.Arn
```
2.  Attempt to `deploy` this template, which  results in an error with the following:  "'Globals' section is invalid. 'Role' is not a supported property of 'Function'. Must be one of the following values..."

**Observed result:**

Attempting to deploy the template fails

**Expected result:**

Deploying the template should succeed, with the global role value being applied like any other SAM Function property.

**Comment by chrisoverzero** [comment]
This was a decision made purposefully, according to the [globals guide][]. Of the given reasons, I would guess that “opened scope for potential security issues“ is what applies to `Role`.

> […] being applied like any other SAM Function property.

I hope you can see now that this is not the case.

[globals guide]: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#unsupported-properties

**Comment by pofallon** [comment]
Thanks for the reply!  I didn't notice that in the guide until after I'd created the issue (my bad!)  In my environment, I can't let SAM create the role(s) for me (due to organizational guidelines) so I have to manage them myself.  Repeating this one parameter multiple times really isn't a big deal.  However, I'd be interested to know the security motivations behind the decision -- for my own learning as well as others that may come along and find this later.  Thanks again!

**Comment by keetonian** [comment]
Our typical guidance is giving lambda functions the "least necessary privilege", which means having one role for all functions would in most cases violate this guidance. 

Closing this issue, as we [intentionally](https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#unsupported-properties) don't support `Role` in globals.
