### ISSUE TITLE
Can you add an example Swagger.yml file?

### ISSUE THREAD

**Issue by axpence** [awslabs/serverless-application-model#9]
In the examples I'd like to see an API that is using swagger. Thanks!

**Comment by sanathkr** [comment]
Thanks for the request. We will add one

**Comment by JasonQuinn** [comment]
It would be very useful if it showed how to reference a lambda created with AWS::Serverless::Function as I'm currently having issues working it out.

**Comment by dinvlad** [comment]
A related question (hope I don't intrude): does SAM automatically create Lambdas referenced in Swagger.yml? I.e. do we still need to have relevant functions defined in sam.yaml, or is Swagger template going to be sufficient as long as we specify Lambdas there?

**Comment by ahausamm** [comment]
Is there any progress with an example template? 

I have some issues with the integration (integrate lambda from cloudformation template to a path in the swagger file). The problem i have is that if im creating a x-amazon-apigateway-integration i have to use the arn etc. from the lambda function. Is there any example?
