### ISSUE TITLE
SAM validate crashes on improperly formatted function Events

### ISSUE THREAD

**Issue by xrendan** [awslabs/serverless-application-model#915]
**Description:**

sam validate crashes on invalid template,

SAM CLI, version 0.15.0
Windows 10

**Steps to reproduce the issue:**
1. Use the following template file (sorry for .txt extension, github insists on it)
[crash-template.yaml.txt](https://github.com/awslabs/serverless-application-model/files/3173554/crash-template.yaml.txt)

2. run `sam validate -t crash-template.yaml.txt`
3. Watch as SAM crashes and burns (see debug output) 
[debug.txt](https://github.com/awslabs/serverless-application-model/files/3173579/debug.txt)

**Observed result:**
Sam validate crashes with `TypeError: Resource dict has missing or invalid value for key Type. Resource Dict is: None`
**Expected result:**
Error Validating, not crashing of the valiadate method

**Comment by keetonian** [comment]
@xrendan Thank you for reporting this! We fixed part of this in the v1.11.0 release, but this particular template caused another error that @praneetap just submitted a fix for. This will go out with our next release.

**Comment by xrendan** [comment]
Awesome, happy to help :)
