### ISSUE TITLE
Example for AWS Service Integrations ( S3 ) 

### ISSUE THREAD

**Issue by ashishusoni** [awslabs/serverless-application-model#921]
**Description:**

I do not find any documentation or example how we can define the sam template for AWS service integration such as S3

**Comment by keetonian** [comment]
@ashishusoni SAM has an easy integration between Lambda Functions (AWS::Serverless::Function) and S3 buckets. 

The spec for AWS::Serverless::Function can be found here: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

S3 event structure: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3

Here's a sample application that uses S3 events: https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/image_resize_python
