### ISSUE TITLE
jsonschema~=2.6 dependency causes DeprecationWarning under Python 3.7

### ISSUE THREAD

**Issue by jmehnle** [awslabs/serverless-application-model#922]
The `jsonschema~=2.6` dependency causes a `DeprecationWarning` under Python 3.7:

```
  …/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping, Sequence  # noqa
```

This was [fixed in `jsonschema` 3.0.0](https://github.com/Julian/jsonschema/pull/465). Can you please bump your `jsonschema` dependency to allow (or require) 3.0? ([See also](https://github.com/Julian/jsonschema/issues/487).)

**Comment by keetonian** [comment]
Yes! We can totally do that, thank you for bringing this up!

**Comment by moseb** [comment]
Any chance to get a new release?

I see 9 other issues waiting for a release at https://github.com/awslabs/serverless-application-model/labels/stage%2Fwaiting-for-release as well.

**Comment by jlhood** [comment]
@moseb We have a new SAM release coming soon!

**Comment by moseb** [comment]
Related: a01fae53e1ab3140b2b6ee146c3ee57b14d5b1f0
