### ISSUE TITLE
Error Updating Stack referencing inline Lambda and Node v10 runtime

### ISSUE THREAD

**Issue by mattmar10** [awslabs/serverless-application-model#926]
**Description:**

Seeing CREATE_FAILED error when template defines an inline lambda function against the nodejs10.x runtime

**Steps to reproduce the issue:**
1. Lauch a cloud formation stack referencing a template with an inline lambda function against the nodejs.x runtime. (example attached)
<img width="973" alt="cloudformation-error-nodev10" src="https://user-images.githubusercontent.com/4678850/57951617-2a412380-78b0-11e9-8df2-bfe3864de469.png">

**Observed result:**

CREATE_FAILED error along with this error:  **ZipFile can only be used when Runtime is set to either of nodejs, nodejs4.3, nodejs6.10, nodejs8.10, python2.7, python3.6, python3.7.**

Seems similar to https://forums.aws.amazon.com/thread.jspa?messageID=841075&tstart=0

**Expected result:**
An updated stack and associated lambda function running against nodejs10.x runtime

**Comment by keetonian** [comment]
This is an issue with the CloudFormation resource. I brought this up internally with the CloudFormation team.

The only workaround that I can suggest in the meantime is to deploy a function using NodeJS 8 then switch the runtime to 10 via the console or AWS CLI.

Closing as we can't do anything more about this; this feature will work once CFN releases support for the new runtime.

**Comment by mattmar10** [comment]
Thank you, @keetonian for the explanation. Do you know where I might be able to track this issue with the CloudFormation team and/or get an ETA?

**Comment by keetonian** [comment]
@mattmar10 I would recommend opening a case with AWS Support; they should be able to notify you when the feature is released.
