### ISSUE TITLE
Environment Variables get ignored without errors if it is not under the properties section

### ISSUE THREAD

**Issue by emetwall** [awslabs/serverless-application-model#938]
**Description:**

**Steps to reproduce the issue:**
1. Create a AWS::Serverless::Function resource and 
2. Put the Environment: section on the same level as the Properties section under the Resource Logical Id.
3. Package & Deploy the template via CodePipeline.

**Observed result:**
The execution of the CloudFormation update & the Pipeline as well succeeds without any errors and the variables are ignored.
**Expected result:**
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [xxxxx] is invalid. property Environment not defined for resource of type AWS::Serverless::Function

**Comment by brettstack** [comment]
Thanks for the report. We discussed how we might fix this and haven't come up with a good solution. One way would be for us to detect any unexpected items at the top-level of AWS::Serverless::* Resources, however, while this would be a good validation for new templates it would mean users who have "junk" at this level will start seeing failures.

**Comment by cyrfer** [comment]
I can think of some ideas:
* Show the validation violation with bright colors in console.
* allow users to pass a flag for more strict or less strict validation.

**Comment by praneetap** [comment]
We discussed this issue in more detail. Currently we don't validate properties under resource logical id, other than the ones SAM uses. To start doing so would be backwards incompatible.
