### ISSUE TITLE
Documentation surrounding Lambda Aliases and CodeUri is unclear

### ISSUE THREAD

**Issue by SparkClark** [awslabs/serverless-application-model#942]
**Description:**

The documentation in the section "Instant traffic shifting using Lambda Aliases" is unclear about what conditions surrounding the CodeUri property trigger a version.    The documentation states "When the CodeUri property of AWS::Serverless::Function changes, SAM will automatically publish a new version & point the alias to the new version", but this seems to imply a new version will be published only if the _value_ of CodeUri property changes when the actual behavior is to publish a new version of the _contents referred to_ by CodeUri changes.

**Steps to reproduce the issue:**
1.
2.
3.

**Observed result:**

**Expected result:**

**Comment by keetonian** [comment]
@SparkClark I agree that a new version should be deployed when the value of the contents referred to by CodeUri changes, however, that would involve maintaining state on SAM for all templates to compare the previous and current code values in the bucket location referred to by CodeUri and granting SAM access to read your bucket contents. This is out of scope for SAM.

Instead, what SAM does is use the CodeUri property, and lets CloudFormation update the stack if the CodeUri property has changed. You can ensure that a different CodeUri is used if you use tools such as the AWS CLI or AWS SAM CLI which package artifacts into an S3 bucket using a SHA of the code artifacts as the object key. This way, if the code has changed, the SHA will change, forcing a new deployment and a new version to be created. If you are using your own tooling, you could consider doing something similar.
