### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by gliptak** [awslabs/serverless-application-model#945]
Is the development guide up-to-date on Python versions supported?

https://github.com/awslabs/serverless-application-model/blame/master/DEVELOPMENT_GUIDE.rst#L20

Travis does have Python 3.6 build:

https://github.com/awslabs/serverless-application-model/blob/master/.travis.yml#L7

**Comment by jlhood** [comment]
@gliptak Thanks for pointing this out. You're correct, Python 2.7 and 3.6 are the current officially supported python versions. We'll get that guide updated.

**Comment by gliptak** [comment]
@jhood would you be interested in a PR to add Python 3.7 to Travis?

**Comment by jlhood** [comment]
@gliptak Thanks so much for the offer! I would definitely be interested, but I actually went ahead and did that already as part of #968. Sorry, should have offered to let you do it! 😊

**Comment by gliptak** [comment]
@jhood no worries. maybe I can add ```Python 3.8``` whemn time comes :)

**Comment by jpangburn** [comment]
@gliptak Looks like you have your chance :-) 3.8 is available for Lambda on AWS as of a few days ago.
