### ISSUE TITLE
Pre-warmup Lambda function

### ISSUE THREAD

**Issue by hoang-innomizetech** [awslabs/serverless-application-model#951]
Is there any way we can configure pre-warmup Lambda function likes this plugin https://github.com/FidelLimited/serverless-plugin-warmup

**Comment by jlhood** [comment]
@hoang-innomizetech No, SAM does not have pre-warmup functionality built in.

**Comment by hoang-innomizetech** [comment]
But if we wanted pre-warmup, what are your suggestions @jlhood ?
