### ISSUE TITLE
Support for TriggerConfigurations

### ISSUE THREAD

**Issue by kevinslin** [awslabs/serverless-application-model#955]
**Description:**

Use SAM as part of code pipeline which uses a cloudformation action to deploy a SAM template. We need to support email notification on deployment success/failure. Currently, there does not seem to be a way to configure this in SAM. Currently resorting to creating the deployment group and manually adding trigger configuration using CLI which is far from ideal.

**Steps to reproduce the issue:**
1. [SAM 2016-10-31 Spec for deployment preference](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#deploymentpreference-object)
2. No mention of [TriggerConfigurations](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide//aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-triggerconfigurations)

**Observed result:**

No Trigger Configurations

**Expected result:**

Supporting Trigger Configurations in SAM

**Comment by jlhood** [comment]
@kevinslin Thanks for this feature request. This shouldn't be too hard to add, but we have limited bandwidth so adding information on where to make the relevant changes so someone from the community can hopefully add it.

TriggerConfigurations is a property of [AWS::CodeDeploy::DeploymentGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide//aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-triggerconfigurations). In SAM, this resource is modeled [here](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/codedeploy.py#L17) and populated [here](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/model/preferences/deployment_preference_collection.py#L112).

**Comment by sridk** [comment]
Hey @jlhood can I work on this?

**Comment by jlhood** [comment]
@sridk Absolutely! Looking forward to your PR. 😊

**Comment by arshanq** [comment]
@jlhood Can i work on this ?

**Comment by jlhood** [comment]
@arshanq Yes, thank you! See the [Development Guide](https://github.com/awslabs/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.rst) to help get you started if this is your first contribution. Make sure to base your changes off of the `develop` branch, not `master`. Thanks again and looking forward to your PR!
