### ISSUE TITLE
Unable to deploy API with inline swagger -- Either 'DefinitionUri' or 'DefinitionBody' property is required

### ISSUE THREAD

**Issue by senthil-versent** [awslabs/serverless-application-model#96]
Inline Swagger template would not deploy  with the below error.  I have confirmed that the "DefinitionBody" is present in the output template for deploy. 

Resources:
  StockQuoteApi:
    Properties:
      DefinitionBody: 
      StageName: dev
    Type: AWS::Serverless::Api
Transform: AWS::Serverless-2016-10-31
basePath: /dev
definitions:

>> aws cloudformation deploy --template-file inlineswagger-template-output-v2.yaml --stack-name SAM-inlineswagger-api-v2 --capabilities CAPABILITY_IAM --profile saml
Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [StockQuoteApi] is invalid. Either 'DefinitionUri' or 'DefinitionBody' property is required

**Comment by vasylk** [comment]
Hi,

I am experiencing the same issue.

I tried also to run an adapted version from the provided example 

` ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              "/get":
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyFunction.Arn}/invocations
                  responses: {}
            swagger: '2.0'`


https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/inline_swagger/template.yaml

Error is:

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ApiGatewayApi] is invalid. Specify either 'DefinitionUri' or 'DefinitionBody' property and not both

**Comment by vasylk** [comment]
This is the same as https://github.com/awslabs/serverless-application-model/issues/93

It was a bug in awscli and it seems to be fixed now in the latest version.
Upgrade your awscli to 1.11.54

**Comment by senthil-versent** [comment]
thanks @vasylk. I did update CLI and the issue went away.
