### ISSUE TITLE
s3 bucket name doesnt get substituted in the sam template output

### ISSUE THREAD

**Issue by senthil-nathan** [awslabs/serverless-application-model#98]
s3 bucket name doesnt get substituted in the sam template output

Cli version
aws-cli/1.11.54 Python/3.4.4 Darwin/16.3.0 botocore/1.5.17

**template**:
 LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: `s3://<bucket>/auth.zip`
      Description: Lambda Function 
      Handler: index.handler
      Runtime: nodejs4.3
      Timeout: 30

**I am packaging as below:**
aws cloudformation package --template-file ips-v1.yaml --output-template-file ips-template-output-v1.yaml --s3-bucket test_bucket

**In the output template it is:**

AWSTemplateFormatVersion: '2010-09-09'
Description: Simple API Endpoint configured using Swagger specified inline and backed
  by a Lambda function
Resources:
  LambdaFunction:
    Properties:
      CodeUri: `s3://<bucket>/auth.zip`
      Description: Lambda Function 
      Handler: index.handler
      Runtime: nodejs4.3
      Timeout: 30
    Type: AWS::Serverless::Function
  ipsApigw:

**Comment by jolexa** [comment]
In `template` the `CodeUri` is a local path, not s3:// uri

From the man page:

> 
>        For example, if  your  AWS  Lambda  function  source  code  is  in  the
>        /home/user/code/lambdafunction/    folder,    specify    ``    CodeUri:
>        /home/user/code/lambdafunction``  for   the   AWS::Serverless::Function
>        resource.  The  command  returns a template and replaces the local path
>        with the S3 location: CodeUri: s3://mybucket/lambdafunction.zip.

**Comment by mk2130** [comment]
I am running cloudformation package command through codebuild and it is referring code from s3 bucket what i need to do in this case.because in my case it aslo copying the same codeUri from previous template

**Comment by miguelaustro** [comment]
same issue, it doesn't work. My template has:
`
Telephony.Service.API/Telephony.Service.API/serverless.template:
        "CodeUri": "./Telephony.Service.API.zip"
`
(that file exists in Telephony.Service.API/Telephony.Service.API/  directory )
So my command is:

`aws cloudformation package --template-file ./Telephony.Service.API/Telephony.Service.API/serverless.template --s3-bucket callconnect-dev-deployment --s3-prefix "test" --output-template-file /tmp/output-serverless.template`

But, in /tmp/output-serverless.template  it is transformed to:
`  Get:
    Properties:
      CodeUri: s3://callconnect-dev-deployment/test/cd6a69d250df7e596b7f1aa7e8df5daf
`

**Comment by jarreds** [comment]
@miguelaustro if you look in your S3 bucket, you’ll notice that the file “cd6a69d250df7e596b7f1aa7e8df5daf” and “Telephony.Service.API.zip” are identical. The package command renames the original file to a hash of itself when uploading to S3.

**Comment by PhungXuanAnh** [comment]
@jarreds It's good if "sam package" command keep name 'Telephony.Service.API.zip' while upload to s3, instead of rename zip file. 
Because each time I run "sam package", it will create another file in s3, I don't want that happen
Is there any way to specify zip name while run "sam package" to upload to s3?

**Comment by keetonian** [comment]
@PhungXuanAnh It is actually meant to create another file in S3; see https://github.com/awslabs/serverless-application-model/issues/942#issuecomment-497794963
