### ISSUE TITLE
Still getting Error: StageName cannot be updated

### ISSUE THREAD

**Issue by pkordes** [awslabs/serverless-application-model#997]
Although Issue #168 is the only issue referencing this error and says it is closed, I am still getting this today.  It seems to be somewhat intermittent and I do NOT see the other stages called "Stage" referenced in some of the comments.

I have a pretty simple CFN with SAM API functions.  The API Gateway, Deployment, and Stage, however, were all pure CFN because I needed advanced functionality related to the gateway.  Some changes allow me to update, but the recent change which wants to update all of the functions is now continually giving an error updating the API Gateway Deployment with "StageName cannot be updated".  No changes were made to the Gateway or anything related other than the functions themselves

**Comment by jlhood** [comment]
@pkordes I'm sorry you're experiencing this issue. Can you provide a sample template and detailed steps to reproduce this issue so we can investigate further?

**Comment by praneetap** [comment]
Closing due to no response

**Comment by suraj-kc-idexx** [comment]
I am getting the same error. Here is part of the template:
 Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateWayRestApi
The template is already deployed, and a stage already exists. I made some changes to AWS::ApiGateway::RestApi and I am just trying to run the template using SAM, and it fails with the error - "StageName cannot be updated"

**Comment by keetonian** [comment]
@suraj-kc-idexx SAM makes deploying and updating API resources easier if you use a `AWS::Serverless::Api` resource.

Here's a working example: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/api_resource_policy/template.yaml

If you use the `AWS::Serverless::Api` resource, SAM will generate `AWS::ApiGateway::RestApi`, `AWS::ApiGateway::Stage`, and `AWS::ApiGateway::Deployment` resources for you.

**Comment by pkordes** [comment]
Please note that the issue is the error that occurs when updating with no
explanation and no recourse.  I ended up giving up and working around the
issue by removing SAM altogether and just using pure Cfn.  There is
absolutely a bug here that SAM is behaving differently on update per the
original ticket and Suraj's experience as well.  Unfortunately, I could not
afford to wait for a response and had long since torn down the
infrastructure having the issue.  I urge you to work with Suraj if the
infrastructure is still available to see this error in action.

**Comment by ShreyaGangishetty** [comment]
I am sorry you are facing this error and you have to move away from SAM. It really helps us understand better if you could post the full template here. From the template snippet posted in https://github.com/awslabs/serverless-application-model/issues/997#issuecomment-534614788 it seems like they were not using Serverless resources, so SAM directly passes everything onto CloudFormation.
